### ISSUE TITLE
Is there any one to help me with this question?

### ISSUE THREAD

**Issue by clearcodecn** [gonum/gonum#1000]
---
name: Question
about: Ask at the Gonum discussion list https://groups.google.com/forum/#!forum/gonum-dev

---

# :no_entry_sign: INVALID :no_entry_sign:

https://stackoverflow.com/questions/56590792/how-do-i-refactor-the-code-from-python-to-golang-using-scipy-to-gonum

**Comment by kortschak** [comment]
Please ask at the mailing list, the issue tracker is for bugs, proposals and feature requests.
