### ISSUE TITLE
how to support  type Mat of opencv

### ISSUE THREAD

**Issue by orange-jacky** [gonum/gonum#1011]
i want to write opencv program by golang, i choose package  "github.com/hybridgroup/gocv",
it can NewMat(),  gonum can NewDense(), whether you plan to support NewDense with input param NewMat()?

**Comment by kortschak** [comment]
That is a wrapper around [this](https://docs.opencv.org/master/d3/d63/classcv_1_1Mat.html). No, we aren't going to do that.

**Comment by vladimir-ch** [comment]
As @kortschak wrote, we're not going to support that directly but it looks like you could use `gocv.Mat.DataPtrFloat64` to get the matrix data slice and pass it to our `mat.NewDense`. However, I cannot tell whether it's a good idea (at least it seems that OpenCV has matrices stored in row-major order).

**Comment by sbinet** [comment]
I guess we could also put somewhere a link to an implementation providing this kind of feature.

**Comment by deadprogram** [comment]
Hello, maintainer of GoCV here. 

If this seems like something generally useful, we could put some sample code somewhere in our repo.

Probably the use case is GoCV to capture/cleanup images, and then Gonum to analyze the data. Does that seem correct?

Based on your comment @vladimir-ch sounds like the data needs to be x<->y axis transformed in order for the row/column ordering to be correct? If there was a PR submitted with an example of translation from OpenCV's Mat to the Dense used here, we'd gladly accept it.

Let me know what anyone thinks. If I can offer any assistance, let me know.

**Comment by vladimir-ch** [comment]
Hi @deadprogram , I meant that OpenCV's Mat seems to be row-major, just as Gonum's mat.Dense, so no transformation is necessary. Then the slice from `gocv.Mat.DataPtrFloat64` could be passed to `mat.NewDense` provided the stride (step in OpenCV terminology) is exactly the number of columns. The documentation for `cv::Mat::isContinuous` says that _"... But if you extract a part of the matrix using Mat::col, Mat::diag, and so on, or constructed a matrix header for externally allocated data, such matrices may no longer have this property."_ On the other hand, GoCV does not seem to provide access to this API, so it could work?

**Comment by WendelHime** [comment]
Hi guys, probably is a little late comment but I've tested the proposal from @vladimir-ch using a grayscale image and it works!

I don't know too much about gonum lib, but I didn't find anything related to multidimensional arrays, so I don't have any clue about how to implement with colored images, any suggestions?

```go
package main                                                                                                            
                                                                                                                        
import (                                                                                                                
    "fmt"                                                                                                               
                                                                                                                        
    "gocv.io/x/gocv"                                                                                                    
    "gonum.org/v1/gonum/mat"                                                                                            
)                                                                                                                       
                                                                                                                        
func main() {                                                                                                           
    // read image as grayscale                                                                                          
    img := gocv.IMRead("/home/wotan/Pictures/Screenshots/Screenshot from 2019-08-19 17-25-43.png", gocv.IMReadGrayScale)
    fmt.Printf("this image have %d rows and %d cols and have the type: %s\n", img.Rows(), img.Cols(), img.Type())       
    // this image have 1080 rows and 1920 cols and have the type: %!s(gocv.MatType=0)                                   
                                                                                                                        
    // convert image to float64                                                                                         
    convertedImg := gocv.NewMat()                                                                                       
    img.ConvertTo(&convertedImg, gocv.MatTypeCV64F)                                                                     
    imgArray, err := convertedImg.DataPtrFloat64()                                                                      
    if err != nil {                                                                                                     
        fmt.Printf("Error converting image to float64: %v\n", err)                                                      
        return                                                                                                          
    }                                                                                                                   
                                                                                                                        
    fmt.Printf("imgArray length: %d == %d\n", len(imgArray), img.Rows()*img.Cols())                                     
    // imgArray length: 2073600 == 2073600                                                                              
                                                                                                                        
    // create a new mat.Dense                                                                                           
    dense := mat.NewDense(img.Rows(), img.Cols(), imgArray)                                                             
                                                                                                                        
    rows, cols := dense.Dims()                                                                                          
    fmt.Printf("Dense: %d %d\n", rows, cols)                                                                            
    // Dense: 1080 1920                                                                                                 
}
```

**Comment by vladimir-ch** [comment]
In gonum/mat we support only 1d (vectors) and 2d (matrices) arrays of float64. The latter can be used for grayscale images, as you're already doing, but for color images there is a variety of approaches that I'd hesitate to suggest something without understanding the use-case or the problem you're trying to solve. Can you share more details?

**Comment by vladimir-ch** [comment]
Closing because all open questions were answered and there has been no update in long time.
