### ISSUE TITLE
mat: VecDense.CopyVec panics when copying another VecDense of diffrent length

### ISSUE THREAD

**Issue by xiegeo** [gonum/gonum#1012]
### What are you trying to do?
Use CopyVec to copy a smaller vector into a bigger vector

### What did you do?

https://play.golang.org/p/BWgtRJx9vDC

### What did you expect to happen?
Copy the smaller VecDense into the head of the bigger one should be allowed according to documentation of CopyVec.

### What actually happened?
Code panics

### What version of Go and Gonum are you using?

go version go1.12.6 windows/amd64
gonum.org/v1/gonum v0.0.0-20190628223043-536a303fd62f

### Does this issue reproduce with the current master?
yes

**Comment by kortschak** [comment]
Thanks. This is a result of a new check in `blas64.Copy`. I'll send a PR soon.
