### ISSUE TITLE
mat: Move LFromCholesky into Cholesky

### ISSUE THREAD

**Issue by btracey** [gonum/gonum#102]
We forgot this one when we moved the other types.

**Comment by kortschak** [comment]
There were three there that were obviously missed. `LFromCholesky` => `LTo`, `UFromCholesky` => `UTo` and `FromCholesky` => `To` (this may want elaboration in the name - or not). There is also `InverseCholesky` which could be rewritten as `InverseTo` on `*Cholesky`.
