### ISSUE TITLE
r2/r3: flesh out Vec API

### ISSUE THREAD

**Issue by odsod** [gonum/gonum#1049]
### What are you trying to do?

We want to do some simple vector math on the r3.Vec type (cross product, dot product, etc): https://github.com/golang/geo/blob/master/r3/vector.go

### What did you try?

We've added common operations as helper functions. It works, but might be useful to more people (and simplify reuse) to include them as member functions on the Vec type.

### How does Gonum not allow you to achieve your goal?

Gonum helps us, but we are proposing to add some of the most common vector operations to as member functions. 

### What version of Go and Gonum are you using?

go version go1.12.7 linux/amd64
gonum: 3ce8ac2a2fb11ca0240b45098d1f4393d3912a71

### Is this feature absent from the current master?

Yes.

### Are you able to help contribute the feature?

Yes.

**Comment by odsod** [comment]
@kortschak I can see you recently added the r2/r3 packages. Do you think additions like this are in scope for these packages?

**Comment by kortschak** [comment]
I think this is where they would go if they do. I'd like to hear others' opinions though; we rushed into the set operations on `r1` and then decided it was too complicated for what we intended and then had to back them out. I'd like to avoid that happening again.

/cc @btracey @vladimir-ch @sbinet

**Comment by odsod** [comment]
@kortschak Understood!

If you give the go-ahead, I can submit PRs for the most common operations like:

* Mul
* Cross (included in the example PR #1050)
* Dot
* Norm
* anything else you suggest

**Comment by sbinet** [comment]
I guess that's a good set of minimal operations one would want to apply on r3.Vec.

I'd be fine with it.

**Comment by btracey** [comment]
I think that's a good set as well. 

In the past I've also implemented `[2][2]float64` matrices and `[3][3]float64` matrices to do common operations (i.e. determinant, splitting in various ways). Would those kinds of operations belong here as well? If that is true, would we want Vector to be a `[2]float64`? It's easy to have an `func (v Vector) X() float64` method, and would be more consistent.

**Comment by kortschak** [comment]
I could be convinced.

**Comment by sbinet** [comment]
what's the status of this PR?

(I am asking b/c I'll probably have to add some more R^3 capabilities to one of my packages, soon)
playing a bit with `geo/r3` (and my very limited `Vec3` type), I think I'd be w/ @btracey on making `r3.Vec` a 3-float64 array. (that way, creating a `mat.VecDense` is just sub-slicing the `r3.Vec` 3-array, possibly modifying it in-place)

**Comment by sbinet** [comment]
nevermind, I see the PR associated w/ this issue has been closed :)

I'll open my own.

**Comment by sbinet** [comment]
https://github.com/gonum/gonum/pull/1297

**Comment by rcoreilly** [comment]
for reference and discussion in README: https://github.com/goki/mat32
