### ISSUE TITLE
stat/combin: Cartesian design does not match package

### ISSUE THREAD

**Issue by btracey** [gonum/gonum#1057]
`Combinations` returns a [][]int, while `Cartesian` deals with `*mat.Dense`. There is no good reason for this distinction. In general, `combin` deals with helping indexing (`Combinations`, `SubFor`), so `Cartesian` should change to also deal with [][]int. This is more general, as the current design assumes your sets are type `float64` while if it returns `[][]int`, then they can be interpreted as indexes into sets of arbitrary type.

**Comment by kortschak** [comment]
Yes, we don't need this to be a float matrix. I'm not sure why we went this way.
