### ISSUE TITLE
Continuous Fuzzing Integration

### ISSUE THREAD

**Issue by yevgenypats** [gonum/gonum#1060]
Hi, I'm Yevgeny Founder of [Fuzzit](https://fuzzit.dev) - Continuous fuzzing as a service platform.

I saw that you implemented Fuzz targets but they are currently not running as part of the CI.

We have a free plan for OSS and I would be happy to contribute a PR if that's interesting.
The PR will include the following
- Continuous Fuzzing of master branch which will generate new corpus and look for new crashes
- Regression on every PR that will run the fuzzers through all the generated corpus and fixed crashes from previous step. This will prevent new or old bugs from crippling into master.

You can see our basic example [here](https://github.com/fuzzitdev/example-go) and you can see an example of "in the wild" integration [here](https://github.com/google/syzkaller).

Let me know if this is something worth working on.

Cheers,
Yevgeny

cc @kortschak

**Comment by kortschak** [comment]
Hi Yevgeny. Thanks.

We do run the fuzz corpus on the parts that have been fuzzed (these exist in the commited zip files). I'm curious about which parts of the repo would benefit from additional fuzzed testing.

**Comment by yevgenypats** [comment]
Hi Dan,

So essentially:
* Fuzzit will run the same fuzzers but would do that continuously every time new code is pushed to master (the fuzzers will run indefinitely).
* Fuzzit will take care of hosting and minimising the corpus so you don't need to update the corpus in the git every time you run it.
* As I mentioned it will take advantage of the most recent corpus to run fast regression tests on every PR so travis will fail if new bugs are introduced in the PR.

BTW, forgot to mention we just rolled out a reward program (2 days ago). If you are willing to do the integration to fuzzit I'll be happy to reward you as well as get unbiased feedback regarding how smooth the integration was. If you currently don't have time for this but it still interesting for you I'll be happy to contribute the PR but you won't be eligible for the reward. Let me know what works for you.

**Comment by kortschak** [comment]
Thanks. I could probably find some time to look at that tomorrow. It looks fairly straight forward.

**Comment by kortschak** [comment]
One thing that I'd like clarified is how you can seed the corpus.

**Comment by yevgenypats** [comment]
Cool. you can upload a seed corpus either via the CLI or the UI. once you sign-up at [https://app.fuzzit.dev](https://app.fuzzit.dev) let me know and I'll add you to gonum organisation.

Also you can join our [slack](https://slack.fuzzit.dev) so it will be easier to discuss there any issues/questions you have about the integration.

**Comment by kortschak** [comment]
I am unable to sign in with GitHub at https://app.fuzzit.dev/login using Firefox. Similarly, https://slack.fuzzit.dev/ doesn't accept a sign-on, complaining of a failed Catcha despite not being presented with one. Usually I run Firefox with uMatrix, but even turning this off does not allow either of these to sign me in.

**Comment by yevgenypats** [comment]
That's really strange. I tried to reproduce on firefox. works on my computer:). can you drop me a line at: yp [at] fuzzit.dev so I can invite your email manually to the slack group and try to debug the issue you are experiencing

**Comment by yevgenypats** [comment]
Closing as fuzzit was acquired by GitLab
