### ISSUE TITLE
mat/all: Matrix receiver inputs should respond to IsZero and not nil

### ISSUE THREAD

**Issue by btracey** [gonum/gonum#1081]
stat.Covariance used to check if the input matrix was `nil`, and allocated a new matrix if it was. #705 changed that to instead check if the input matrix is zero and allocate otherwise. This means the usage pattern is 
```
var cov mat.SymDense
stat.CoviarianceMatrix(&cov, data, weights)
```
which is aligned with the similar pattern we've had since the beginning in `mat` for matrix receivers

```
var c mat.Dense
c.Mul(a, b)
```

This issue proposes to change the remaining places we have the `nil` pattern to instead use the `IsZero` pattern. From a quick glance, I think this is mostly in the `FooTo` patterns in `Cholesky`, `SVD`, etc. It is also present in `distmat`, i.e `Wishart.MeanSym`

Note that while this is a change for some of the functions, we do already use the proposed pattern in a number of places, `distmv.Normal.CovarianceMatrix` for example. `Cholesky.SolveVec` is not documented what happens when `dst` is nil, but the current behavior is to resize.

I think implementing this change would make it consistent across the board. #963 can also be implemented to make it easy to help others conform to this style.

**Comment by btracey** [comment]
RFC @kortschak @vladimir-ch

**Comment by kortschak** [comment]
SGTM

Thank you for finding where that was discussed.

**Comment by vladimir-ch** [comment]
SGTM, too.

**Comment by kortschak** [comment]
Yay!
