### ISSUE TITLE
mat: Zero() is does not make IsZero() return true.

### ISSUE THREAD

**Issue by btracey** [gonum/gonum#1083]
Right now we have `IsZero` which checks if the receiver is zero-sized, and `Zero`, which sets the matrix elements to zero. It is confusing that calling `Zero` does not make `IsZero` return true. I suggest we rename `IsZero` to `IsEmpty`. This removes the implicit connection, and `IsReset` seems linguistically awkward.

**Comment by kortschak** [comment]
This is unfortunate, but I think it would probably clear up some documentational issues. I agree that "empty" is probably the best word if "zero" is not available.
