### ISSUE TITLE
proposal: tag a 0.5 release

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#1089]
### Background
We don't have a release. This impacts on distro packagers, so we should have one.

### Proposal
Make a non-stable release. I propose 0.5 since we are probably half way there (in the Zeno sense).

### Potential impact of proposal

I will do this.

**Comment by btracey** [comment]
This is a good idea. I think we should fix #1081 , and then I think we're in a good place for a point release. Thanks for pushing this forward.

**Comment by sbinet** [comment]
I am +1 on this.
`0.5` is as good a number as any.
I'd go with `v0.5.0` for the tag, though.

**Comment by vladimir-ch** [comment]
SGTM

**Comment by btracey** [comment]
Maybe we could make it `0.6` in honor of 6 years since creation?

**Comment by kortschak** [comment]
`vV.Y.M` for less than `v1`?

**Comment by sbinet** [comment]
having a 3-digit version number plays well with the whole semver/go.mod ecosystem.
but I think it would be less confusing to be less cute and just go with `v0.X.0` for versions less than `v1`.

(`v0.6.0` is fine by me.)

**Comment by kortschak** [comment]
I'm looking at how long we are going to be pre-v1. Having `vV.Y.M` for pre-v1 makes it easy to choose reasonably meaningful version numbers.

**Comment by laxatives** [comment]
Please pin this repo. Its already useful but its hard to justify putting this into build pipelines if it is liable to break builds randomly in the future.

**Comment by kortschak** [comment]
If you use go modules this will not break you, but yes, we are working towards this.

**Comment by kortschak** [comment]
Tag v0.6.0 has been pushed.
