### ISSUE TITLE
mat: Cholesky.SetFromU should care about sizes 

### ISSUE THREAD

**Issue by btracey** [gonum/gonum#1097]
Right now, Cholesky.SetFromU does not care about the size of the input triangular matrix, and instead just calls `Copy`. This is ripe for some hidden bugs. It should check that the sizes are either the same or that the destination Cholesky is empty. 

When this is done, the comment for `distmat.Wishart.RandCholTo` should be updated with the behavior

**Comment by btracey** [comment]
I believe this was fixed by https://github.com/gonum/gonum/pull/1098/files

**Comment by kortschak** [comment]
Thanks
