### ISSUE TITLE
blas/gonum/internal/math32: hypot has a flaky test

### ISSUE THREAD

**Issue by btracey** [gonum/gonum#110]
`math32.Hypot` uses `testing/quick`, but the current test as written fails for certain `float32` values. For instance

````
func TestHypot2(t *testing.T) {
	var p float32 = -3.6557444e+37
	var q float32 = 7.9378095e+37
	y := Hypot(p, q)
	if !floats.EqualWithinRel(float64(y), math.Hypot(float64(p), float64(q)), tol) {
		t.Errorf("hypot mismatch")
	}
}
````
fails.

I'm not sure why this hasn't come up before, but it fails under go1.9beta2.  See https://github.com/golang/go/issues/20809

**Comment by kortschak** [comment]
Yeah, I noticed this the other day.
