### ISSUE TITLE
unit: Can not multiply dimensionless units

### ISSUE THREAD

**Issue by abferm** [gonum/gonum#1109]
### What are you trying to do?
Multiply unit.Dimless by a custom unit.

### What did you do?

https://play.golang.org/p/n17wR5TL_hx

### What did you expect to happen?
No panic with viable result, dimensions equal to other unit.

### What actually happened?
panic: assignment to entry in nil map

### What version of Go and Gonum are you using?

`go version go1.12.1 linux/amd64`
```
gonum.org/v1/gonum v0.0.0-20190409070159-6e46824336d2 h1:IZ343hUHFQ/v9IrSpcT1ih//e8VIctin7w2WyVl4kcc=
gonum.org/v1/gonum v0.0.0-20190409070159-6e46824336d2/go.mod h1:2ltnJ7xHfj0zHS40VVPYEAAMTa3ZGguvHGBSJeRWqE0=
```

### Does this issue reproduce with the current master?

Yes

### Proposed fix
https://github.com/gonum/gonum/blob/master/unit/unittype.go#L171
Should be `return Dimensions{}` rather than `return nil`.

**Comment by kortschak** [comment]
Apologies for not responding to this earlier. If the `dimensions` is nil, it can return nil. I have sent a PR fixing this.
