### ISSUE TITLE
gonum: use golang.org/x/xerrors for error reporting

### ISSUE THREAD

**Issue by sbinet** [gonum/gonum#1110]
we should make use of the `%w` wrapping facility of Go >= 1.13 to present nicer errors to our users.
and we should use `golang.org/x/xerrors.Errorf` during the transition period.

**Comment by kortschak** [comment]
While we should use these error handling tools where appropriate, we don't actually wrap errors much and I'd be happy to wait until we are at a minimum version of Go1.13.

**Comment by sbinet** [comment]
now that we only support Go >= 1.13, we can just use `fmt.Errorf` and `errors.{Is,As}`.
