### ISSUE TITLE
graph/path/dynamic: annotate nolint on poisoned key tests

### ISSUE THREAD

**Issue by bvwells** [gonum/gonum#1116]
### What are you trying to do?

Read the D* lite algorithm.

### What did you do?

Looking over the code of the D* lite algorithm I noticed this:

https://github.com/gonum/gonum/blob/5d5638e6749a344a69611ea36989c7dcbdd2dc8d/graph/path/dynamic/dstarlite.go#L416

Unless I'm missing something, this doesn't look quite right :-)

### What did you expect to happen?

I was trying to work out what this failure case was expected to be. Perhaps

```
	if k == badKey || other == badKey {
```

### What actually happened?

N/A

### What version of Go and Gonum are you using?
Master branch of Gonum.

### Does this issue reproduce with the current master?
Yes

**Comment by kortschak** [comment]
This is correct. I should add a `//nolint` line to that and the other place where that exists.

The `dynamic.key` type is `[2]float64` which has NaN inequality behaviour.
