### ISSUE TITLE
mat, lapack64: DSYGST

### ISSUE THREAD

**Issue by Konstantin8105** [gonum/gonum#1159]
### What are you trying to do?

For calculation natural frequencies in finite element analisys, used next:

![Az=lBz](http://www.netlib.org/lapack/lug/img39.gif)

```
A - sparse symmetric matrix
B - sparse symmetric matrix, positive definition
```

In according to LAPACK documentation, we have a fortran implementation for that task - see http://www.netlib.org/lapack/lug/node54.html

### What did you try?

Now, we use `mat.Eigen` , it is more generic.

### How does Gonum not allow you to achieve your goal?

I do not found any comparing of performance  Geev(`mat.Eigen`) and DSYGST(`LAPACK`). I suppose DSYGST is better.

### What version of Go and Gonum are you using?

v1

### Is this feature absent from the current master?

no.

### Are you able to help contribute the feature?

yes, I can contribute and prepare PR.

**Comment by vladimir-ch** [comment]
We don't have `lapack/gonum.Dsygst` but from the Fortran reference it doesn't look like a lot of work to add, especially if you are willing to contribute and submit a PR. Of course, `Dsygst` is only for dense symmetric matrices.

**Comment by Konstantin8105** [comment]
Thank you, @vladimir-ch  for clarification.
I agree - it is more work, then I expect.
