### ISSUE TITLE
HOW TO reshape one  matrix

### ISSUE THREAD

**Issue by mullerhai** [gonum/gonum#1202]
dim :=20
	data := []float64{    3, 4, 5, 5, 2, 4, 7, 8, 11, 8, 12,
		11, 13, 13, 16, 17, 18, 17, 19, 21}
	y_matrix :=mat.NewDense(dim,1 ,data)

	y_matrix.ReuseAs(4,5)
	fmt.Println("matrix" ,y_matrix)

error 
panic: mat: reuse of non-empty matrix

**Comment by btracey** [comment]
Just do 

`y2 = mat.NewDense(4, 5, data)`

**Comment by mullerhai** [comment]
> Just do
> 
> `y2 = mat.NewDense(4, 5, data)`

thx ,but not the same as you ,but you give inspire 
k_matrix := pd.NewDense(4,5,y_matrix.RawMatrix().Data)

**Comment by kortschak** [comment]
>k_matrix := pd.NewDense(4,5,y_matrix.RawMatrix().Data)

This is not safe in the general case.

Please take questions to https://groups.google.com/forum/#!forum/gonum-dev; the issue tracker is not a forum for asking questions.
