### ISSUE TITLE
Error  undefined: reflect.MapIter trying to install gonum

### ISSUE THREAD

**Issue by cleuton** [gonum/gonum#1203]
### What are you trying to do?
I was trying to Install gonum.

### What did you do?
I ran: 
go get -u gonum.org/v1/gonum/...

### What did you expect to happen?
To have the package installed.

### What actually happened?

Got error: 
go/src/gonum.org/v1/gonum/graph/iterator/nodes.go:135:9: undefined: reflect.MapIter
# golang.org/x/exp/rand
go/src/golang.org/x/exp/rand/rng.go:63:19: undefined: bits.Add64
go/src/golang.org/x/exp/rand/rng.go:64:16: undefined: bits.Add64
go/src/golang.org/x/exp/rand/rng.go:68:12: undefined: bits.Mul64

### What version of Go and Gonum are you using?

$ go version
go version go1.10.4 linux/amd64

Version of gonum: latest

### Does this issue reproduce with the current master?

Yes

**Comment by sbinet** [comment]
as noted on the README [here](https://github.com/gonum/gonum#supported-go-versions), _"Gonum supports and tests on the two most recent Go releases on Linux, macOS and Windows"_.

this means, at this time of writing, we only explicitly support Go >= 1.12.
(`reflect.MapIter` was introduced in Go-1.12.)
(ditto for `"math/bits.{Add,Mul}64"`)

please upgrade to Go-1.12.
(any reason why you couldn't do that?)
