### ISSUE TITLE
how to  use eigen solve svd  qr pca  lstsq method ,could you give me some example ?

### ISSUE THREAD

**Issue by mullerhai** [gonum/gonum#1205]
hi ,I want to use these method ,but i find these method is struct ,not like python numpy ,I am  confuse how to use it,would you like give us some detail use toturial for these.thx

**Comment by sbinet** [comment]
Some examples are on the godoc page:

https://godoc.org/gonum.org/v1/gonum/mat#example-Eigen
https://godoc.org/gonum.org/v1/gonum/mat#example-GSVD
https://godoc.org/gonum.org/v1/gonum/mat#example-Cholesky
https://godoc.org/gonum.org/v1/gonum/stat#example-PC
https://godoc.org/gonum.org/v1/gonum/stat#example-LinearRegression

hth.

**Comment by kortschak** [comment]
Please take questions to gonum-dev.

**Comment by mullerhai** [comment]
> https://godoc.org/gonum.org/v1/gonum/mat#example-Eigen

thx ,I check the gonum package find some engen_test.go gsvd_test.go *** file

**Comment by alexandru-balan** [comment]
So there is no way of computing lstsq in go? I tried with the SVD, but the SVD.Values returned are different than what python lstsq is returning. The SVD.Values can be used indeed to construct a solution of a A*x = b system, but unlike the solution returned by lstsq in python, the go solution I calculated is not minimum norm.

Sorry for necrobumping this, but a lstsq would really be nice in GO

**Comment by kortschak** [comment]
Please take a look at https://godoc.org/gonum.org/v1/gonum/mat#VecDense.SolveVec, but also note that questions should be taken to gonum-dev.

**Comment by alexandru-balan** [comment]
Alright, I'll post there, but from the description it seems that SolveVec is not that different from Solve. The matrix in my system is near-singular so both would return garbage data. However the lstsq should be computed using the SVD; I tried to mimick the python implementation of lstsq, but the values returned from SVD.Values are different in GO than what python found for the same data.

**Comment by kortschak** [comment]
If you post there with your Go and python code I can have a look.

**Comment by kortschak** [comment]
Here is an Ax = b implementation (the AX = B implementation that the python also has is left as an exercise for the reader).
```
package main

import (
	"fmt"

	"gonum.org/v1/gonum/mat"
)

// lstsq calculates the least-squares solution to a linear matrix equation, Ax = b.
func lstsq(a *mat.Dense, b *mat.VecDense) (x *mat.VecDense, res float64, s []float64) {
	var svd mat.SVD
	svd.Factorize(a, mat.SVDFull)
	var u, v mat.Dense
	s = svd.Values(nil)
	svd.UTo(&u)
	svd.VTo(&v)

	c := &mat.VecDense{}
	c.MulVec(u.T(), b)

	var y mat.VecDense
	y.DivElemVec(c.SliceVec(0, len(s)), mat.NewVecDense(len(s), s))
	x = &mat.VecDense{}
	x.MulVec(&v, &y)

	if len(s) < c.Len() {
		c = c.SliceVec(len(s), c.Len()).(*mat.VecDense)
		res = mat.Dot(c, c)
	}
	return x, res, s
}

func main() {
	a := mat.NewDense(4, 2, []float64{
		0, 1,
		1, 1,
		2, 1,
		3, 1,
	})
	b := mat.NewVecDense(4, []float64{-1, 0.2, 0.9, 2.1})

	x, res, s := lstsq(a, b)
	fmt.Printf("x=%.4v\nres=%.4v\ns=%.4v\n", mat.Formatted(x, mat.Prefix("  ")), res, s)
}
```
The values here are taken from the python [docs for `lstsq`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.lstsq.html).
```
>>> import numpy as np
>>> x = np.array([0, 1, 2, 3])
>>> y = np.array([-1, 0.2, 0.9, 2.1])
>>> A = np.vstack([x, np.ones(len(x))]).T
>>> np.linalg.lstsq(A, y, rcond=None)
(array([ 1.  , -0.95]), array([0.05]), 2, array([4.10003045, 1.09075677]))
```
This matches the output of the program above.
```
$ go run main.go 
x=⎡    1⎤
  ⎣-0.95⎦
res=0.05
s=[4.1 1.091]
```
The rank of A can be determined by
```
func rank(s []float64, tol float64) int {
	for i, v := range s {
		if v < tol {
			return i
		}
	}
	return len(s)
}
```

**Comment by sbinet** [comment]
couldn't we lift this into a proper `LeastSquares` (or `Lstsq`) function in `stat` or `mat`?

**Comment by kortschak** [comment]
Yes, that could be done. It's just a matter of choosing the right place.

**Comment by kortschak** [comment]
`SolveLeastSquares` and `SolveLeastSquareVec` in mat?

**Comment by sbinet** [comment]
SGTM.

**Comment by btracey** [comment]
Could you post the matrices that you're seeing? It's possible there's a bug, but `Solve` and `SolveVec` should be computing the least-squares solution.

```
func main() {
	a := mat.NewDense(4, 2, []float64{
		0, 1,
		1, 1,
		2, 1,
		3, 1,
	})
	b := mat.NewVecDense(4, []float64{-1, 0.2, 0.9, 2.1})

	c := &mat.VecDense{}
	c.SolveVec(a, b)
	fmt.Printf("x=%.4v\n", mat.Formatted(c, mat.Prefix("  ")))
}
```

**Comment by alexandru-balan** [comment]
Hi @kortschak, I applied form membership at gonum-dev, but in the meantime I wanted to let you know that this solution is what I also implemented and it still is different from python's lstsq. 

Take for example the A matrix as
```
⎡-1.7854591879711257  -0.42687285925779594  -0.12730256811265162⎤
⎢-0.5728984211439724  -0.10093393134001777   -0.1181901192353067⎥
⎢ 1.2484316018707418    0.5646683943038734  -0.48229492403243485⎥
⎢0.10174927665169475   -0.5805410929482445    1.3054473231942054⎥
⎣ -1.134174808195733   -0.4732430202414438    0.3528489486370508⎦

```
and the vector b as
```
⎡ -2.3181340317357653⎤
⎢ -0.7146777651358073⎥
⎢  1.8361340927945298⎥
⎢-0.35699930593018775⎥
⎣ -1.6359508076249094⎦

```
While the python lstsq finds the minimum norm as 4.683861624749758e-31, this GO implementation says it is 5.084455053182303e-31. While the x vectors found by both methods is correct, only the python one finds the minimum norm solution to the problem

**Comment by alexandru-balan** [comment]
Hi @btracey, as advised I made a more detailed post at [gonum-dev](https://groups.google.com/forum/#!topic/gonum-dev/-oFLRyCV120). The problem seems to be that SVD.Factorize finds different singular values to python's lstsq. Or to be more specific, it finds one different singular value.

**Comment by kortschak** [comment]
As posted in gonum-dev, 4.683861624749758e-31 and 5.084455053182303e-31 are under the machine epsilon. I think you are expected more of the machine than is reasonable.
