### ISSUE TITLE
travis: builds on GOARCH=arm64 are broken

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#1218]
Adding the arm64 architecture to the build matrix shows up a number of issues in our testing. These all come down to numerical precision differences between amd64 and arm64 (some show up in arm as well, 386 shows no differences with amd64).

The arm64 arch will be in allowed failures when #1217 is merged which is not ideal, so we need to get the failures resolved so it will show up in the build report on PRs.

This is the list of failure (checked indicates I'm happy with the fix approach - I will add the change sha when #1217 is merged).

- [x] gonum.org/v1/gonum/blas/blas64 `TestDrotmg` "tolerance drotm y_0 mismatch RD1_Med_RD2_Big_Flag_0: expected 0, found 5.1194107541670215e-11" 86e8186781d9a1bb0d5594cda002ef6ba7c5b06e
- [x] gonum.org/v1/gonum/blas/gonum `TestDrotmg` "tolerance drotm y_0 mismatch RD1_Med_RD2_Big_Flag_0: expected 0, found 5.1194107541670215e-11" 86e8186781d9a1bb0d5594cda002ef6ba7c5b06e
- [x] gonum.org/v1/gonum/fourier tolerance `ExampleFFT_Coefficients_tone` 0c0a3fef116df8c4a19bf956d9c1a536b34a08e0
- [x] gonum.org/v1/gonum/graph/layout bug `TestEadesR2` infinite value b5cc9a985978f3b32ea1066f8722cf8a3dc8495e
- [x] gonum.org/v1/gonum/graph/layout tolerance/ED `TestIsomapR2` d8ec179f2bfc07f4e1af26de87896d672c76a332
- [x] gonum.org/v1/gonum/lapack/gonum tolerance `TestDlansb` "got 3.9533942447863906, want 3.9533942447863923" a84dbb2e4f19f947a3a20094acda433ea06ee75a
- [x] gonum.org/v1/gonum/lapack/gonum tolerance `TestDlascl` "unexpected A[0,0]=26.358078839820152, want 26.358078839820152" a84dbb2e4f19f947a3a20094acda433ea06ee75a
- [x] gonum.org/v1/gonum/lapack/gonum tolerance `TestDlaln2` "Want (-0.9316138629711816+0i), got (-0.9316138629728812+0i)" a84dbb2e4f19f947a3a20094acda433ea06ee75a
- [x] gonum.org/v1/gonum/lapack/gonum bug `TestDgeev` "is not right real eigenvector" 4ad776159be98dfcd4c923a85c0d821210cb3dcb
- [x] gonum.org/v1/gonum/internal/asm/f32 tolerance `TestGer` "Test 7 (15x15) align(x:0,y:0,a:0): unexpected value at 77 Got: 1139.92 Expected: 1139.9202" d09a8892ecb325647bbfa9463014fe87b4ab94c9 19131e1d1696cf5862175557dc4aa951a49e864b
- [x] gonum.org/v1/gonum/internal/cmplx64 tolerance `TestSqrt` "Sqrt((2.9263773+5.2290835i)) = (2.111708+1.2381171i), want (2.1117082+1.238117i)" 7c0bd5a0933dd54f8f08bcbcd76d5dc30c45c06b
- [x] gonum.org/v1/gonum/mat tolerance `TestSymRankOne` "got: 0.2824558889951469 want: 0.28245588899514695" 78e1ded4ad704295a1c00a470e1b7d69ad74bb07
- [x] gonum.org/v1/gonum/mathext tolerance `TestMvLgamma` "got=58.89384185123741 want=58.8938418512374" 3e57debe96bfbc7740b66b06894e897889ffd1dd
- [x] gonum.org/v1/gonum/mathext/internal/amos tolerance `TestZacai` "c = 2.4275995843707387e+72, native = 3.269273576136148e+72" 08cd598920a727fc67106acff7e04c1ffde895db
- [x] gonum.org/v1/gonum/mathext/internal/amos ?tolerance `TestZseri` "c = 82.43457817119072, native = 567.4873881105988" 08cd598920a727fc67106acff7e04c1ffde895db
- [x] gonum.org/v1/gonum/optimize ? `TestBFGS` 43ba13d1a9730c8867ecf9d841d9b4aee1fe597b 39972c90c7a54ebe235989958f65ec424f0f7a0b be8b0445de9fddcf006ee2745e6c1cb14857b32b 939a2b38a376db86fad6c239776d83769af46e27
- [x] gonum.org/v1/gonum/optimize ? `TestLBFGS` 43ba13d1a9730c8867ecf9d841d9b4aee1fe597b be8b0445de9fddcf006ee2745e6c1cb14857b32b
- [x] gonum.org/v1/gonum/optimize ? `TestNewton` c3867503e73e5c3fee7ab93e3c2c562eb2be8178
- [x] gonum.org/v1/gonum/stat tolerance `TestROC` "got:[-5.551115123125783e-17 -5.551115123125783e-17 -5.551115123125783e-17 -5.551115123125783e-17 0.6 0.6 1] want:[0 0 0 0 0.6 0.6 1]" 139a027f558418e0ca6402a3b3c9e7bad5e85d9c 4a17ec14901e0097cbdb96135d2dbbfed878f70f
- [x] gonum.org/v1/gonum/stat tolerance `ExampleROC_weighted` 4a17ec14901e0097cbdb96135d2dbbfed878f70f
- [x] gonum.org/v1/gonum/stat tolerance `ExampleROC_unsorted` 4a17ec14901e0097cbdb96135d2dbbfed878f70f
- [x] gonum.org/v1/gonum/stat tolerance `ExampleROC_equallySpacedCutoffs` 4a17ec14901e0097cbdb96135d2dbbfed878f70f
- [x] gonum.org/v1/gonum/stat tolerance `ExampleLinearRegression` 2d18c7e9153eb8803888df69dafd6467fb10ce8e
- [x] gonum.org/v1/gonum/stat/mds tolerance/ED `TestTorgersonScaling` cc09059115b33416663ac7822945c387ca80ac32
- [x] gonum.org/v1/gonum/stat tolerance tolerance `TestCovarianceMatrix` "expected cov &{{2 2 [0.8 3.2 3.2 13.142857142857146] 2} 2 2}, found &{{85 2 [0.8 3.2 0 13.142857142857142] 2} 2}" 86a902cb7f98249e7b486530a4324491000c98a5

@btracey @vladimir-ch @sbinet

**Comment by kortschak** [comment]
I'm not sure what to do about the `ExampleROC_*` examples. The issue is that [this code](https://github.com/gonum/gonum/blob/683ee363d56e77121c6640345bb9d40644f02a1f/stat/roc.go#L107-L114) gives near zero results on arm64 where we get zero on other architectures. If I replace that code with
```
	for i := range tpr {
		tpr[i] /= nPos
		tpr[i] = 1 - tpr[i]
		fpr[i] /= nNeg
		fpr[i] = 1 - fpr[i]
	}
```
the tests pass.

Maybe this should be filed as an issue at golang/go?

**Comment by vladimir-ch** [comment]
What happens if it's written as `tpr[i] = 1 - invPos*tpr[i]`?

> Maybe this should be filed as an issue at golang/go?

I think it's worth it, I'd be curious to see the outcome.

**Comment by kortschak** [comment]
I tried that also, no difference from the case in two parts.

**Comment by kortschak** [comment]
golang/go#36536

**Comment by kortschak** [comment]
I would not be at all surprised if this explained many of the failures we are seeing here.

**Comment by kortschak** [comment]
I've started digging into the optimize failures and they certainly seem to involve this. The rabbit hole is deep though, and I'm not sure that it's the right thing to do, though I suspect that it is what we will have to do.

**Comment by kortschak** [comment]
I don't think this will be ready for February, so when I make the release-v0.7 branch I will rebase out all of these changes.

**Comment by kortschak** [comment]
I have done some work on the changes in testlapack/dgeev-tolerances locally to see if I can get the `Dgeev` test to pass. After initial success, (the smallest failing case - which involved significant spelunking to find the cause of the failure - FMA/FMS in `Dlahqr`, I tried out the rest - they still fail. So I went on to evict all FMA and FMS instructions that I could in the call tree (some cannot be easily removed since the FMA/FMS instructions occur after expanding complex arithmetic). The tests continue to fail.

This is after a diff that is 64 files changed, 707 insertions(+), 715 deletions(-). Without an easy tool to automatically guard against potential FMA/FMS instructions or a compiler option to not emit FMA/FMS automatically (neither of these exits as far as I'm aware), the amount of work for limited gain seem onerous.

I'm wondering if this is a worthwhile thing to continue battling against, and if it's not whether some of the fixes that have been applied should be removed. Or alternatively we don't say that we support arm64, but leave it such that some things work.

**Comment by kortschak** [comment]
So the issue with the `optimize.Newton` test is that it actually succeeds. It doesn't progress, because is finds 1e6, 2e-6 which is the minimum. This is also the case for the BGFS and LBFGS failures that are testing with `BrownBadlyScaled` and return `ErrNoProgress` (the other `BrownBadlyScaled` are close to success). The `PowellBadlyScaled` failure is similarly close, but `ExtendedRosenbrock` looks like a distant failure.

**Comment by kortschak** [comment]
For the `ErrNoProgress` failures, the issue is that on amd64, the `Location.F` field underflows in a way that is helpful and that the optimisation makes use of. On arm64, this doesn't happen, with values <1e-31 appearing where a zero would be on amd64, resulting in a new `MajorIteration` that is ineffectual due to underflows in the next line search iteration. It's not clear to me exactly how to fix this.

For the `ExtendedRosenbrock` failure for BFGS and LBFGS, it gets stuck early on the in the iterations (with BFGS, the amd64 case runs for ~4000 iters and gets a F of 5e-29, while the arm64 case runs for 180 and finishes with F of 1e5. I'm at a loss to understand this.

@btracey Any ideas for either of these?

**Comment by kortschak** [comment]
An additional data point; if the compiler is altered to not emit fused instructions, then the `ErrNoProgress` failures go away and LBFGS and Newton methods pass, but BFGS still fails.

```
$ GOARCH=arm64 go test -v -run '(Newton|BFGS)'
=== RUN   TestBFGS
--- FAIL: TestBFGS (0.99s)
    unconstrained_test.go:1199: Case 51: error finding minimum (linesearch: non-descent search direction) for:
        F: PowellBadlyScaled
        Dim: 2
        Initial X: [0 1]
        GradientThreshold: 1e-12
    unconstrained_test.go:1199: Case 60: error finding minimum (linesearch: failed to converge) for:
        F: BrownAndDennis
        Dim: 4
        Initial X: [25 5 -5 -1]
        GradientThreshold: 1e-05
    unconstrained_test.go:1199: Case 61: error finding minimum (linesearch: failed to converge) for:
        F: ExtendedRosenbrock
        Dim: 2
        Initial X: [100000 100000]
        GradientThreshold: 1e-10
=== RUN   TestLBFGS
--- PASS: TestLBFGS (5.01s)
=== RUN   TestNewton
--- PASS: TestNewton (0.17s)
FAIL
exit status 1
FAIL	gonum.org/v1/gonum/optimize	6.238s
```

**Comment by vladimir-ch** [comment]
I went through the list of all items again and I think the fixes are good enough. I skipped Zseri and Zacai because there already exists a separate ticket for them. I think we can close this.
