### ISSUE TITLE
[Proposal] add functionality for windowing of sequence to be process by Fourier transform

### ISSUE THREAD

**Issue by goofinator** [gonum/gonum#1223]
### Background
If S(f) is Fourier transform (FT) of S(t), then any linear time-invariant operation on function s(t) produces a new spectrum of the form H(f)•S(f), which changes the relative magnitudes and/or phase of the non-zero values of S(f). Any other type of operation creates new frequency components that may be referred to as spectral leakage in the broadest sense. 
One of such operations is a windowing. To perform FT on a finite-time part of infinite-time signal, this signal is multiplied by a window function, which value is 0 outside of finite time interval to process. 
This operation produces a new frequency components that may break the process of frequency recognition for signals with close frequencies or if signal with low amplitude lies near the  frequency of spectral leakage of signal with high amplitude.

Currently, package "fourier"  perform FT on  the input sequence, which is a case of rectangle window function applied to the infinite-time signal. Bat there are many other window functions , with different parameters of spectral leakage (rectangular is, may be, the worst of them).

### Proposal
I want to add a set of functions to perform the transformation of sequence by different window functions:
**Rectangle( []float64 ) []float64,
RectangleCmplx( []complex128 ) []complex128,
Sin( []float64 ) []float64,
SinCmplx( []complex128 ) []complex128,**
...
and so on.
This functions will be a member of **somePackage**

it'll allow to do some thing like this:
**coeff := fft.Coefficients( nil,  somePackage.Sin( data ) )**

### Potential impact of proposal
The current approach , which have been discussed on "https://groups.google.com/forum/#!topic/gonum-dev/DkSuS2NiYo0"   
is to organize a package tree for algorithms of digital signal processing: **dsp**. After that, in this tree, to create a package **windowing** with discussed set of functions.
Looks logical to move **fourier** package and, may be, some other packages to **dsp** later.

Another approach is just to do discussed set of functions a part of **fourier** package, because i don't see other applications for this functions at first glance.

**Comment by kortschak** [comment]
SGTM.

I'd prefer `window` rather than `windowing`.

**Comment by goofinator** [comment]
If there is no other opinion yet,  let's make some decision. I'am currently do it in dsp/window package, according to a original agreement. I can just move it to fourier/window, if there are no other dsp algorithm in mind except fourier.

**Comment by goofinator** [comment]
I have some thoughts. 

May be i should realize each function in form such like it **fourier.FFT.Coefficients** does:
**func funcName( dst []DataType, src []DataType,) (dst []DataType) {}**
where **DataType** is **float64** or **complex128**?

It will be convenient to use it in form of **fft.Coefficients(funcName(nill,src))**.

It will let user to avoid of memory allocation, which may be critical in real time applications.

Because lengths of **dst** and **src** should be equal, user may use some external **dst**, or **src**. First approach will save **src**'s data unchanged, second - will change it inplace.  

like a **fourier.FFT.Coefficients** it will panic if **len(dst)!=len(src)**.

**Comment by kortschak** [comment]
It doesn't need to allocate in the original form, `func(src []T) []T` given that it's allowed to mutate the input. Let's start with the simpler API. To use it as `fft.Coefficients(funcName(nill,src))` the function would need to return two, a dst and a src. since `Coefficients` takes two parameters. This would mean that it would need to provide an allocation to `Coefficients`. The alternative is to require a call like `fft.Coefficients(nil, funcName(nill,src))`. I'd prefer to just mutate in place and tell the user that that is what happens and they can copy the data first.

Please go ahead with your plan to put it in dsp/window and we can discuss further in the PR.

**Comment by goofinator** [comment]
> To use it as fft.Coefficients(funcName(nill,src)) the function would need to return two, a dst and a src.

Sorry - my fault. I mean: 
fft.Coefficients(dst,funcName(nill,src)) 
or
fft.Coefficients(nill,funcName(nill,src))
to allocate buffer in funcName

or
fft.Coefficients(dst,funcName(src,src))
to modify data by funcName in place

or 
fft.Coefficients(dst2,funcName(dst1,src))
to use external buffers.

I just don't like to do some actions with unobvious result silently. It may cause some data change, when user don't expect it, without any report.
Explicitly is better then implicitly.
Another option is a flag:
func function (src []DataType, inPlace bool) dst []DataType {}.

**Comment by kortschak** [comment]
I would greatly prefer to mutate in place and tell the user explicitly that that is what the function does.

**Comment by goofinator** [comment]
OK

**Comment by kortschak** [comment]
Taking a look at the [importers](https://godoc.org/gonum.org/v1/gonum/fourier?importers) of the fourier package, there are 6 non-Gonum authors importing it into 9 non-Gonum packages. If we want to move fourier to dsp/fourier (which I am inclined to think is a good idea) I think we should get broader feedback.

If the packages importing fourier are using modules, this will not immediately break them, but will require a import path rewrite when they bump versions.

Also note that we are in v0, so while this is not without cost, we are allowed.

cc @aouyang1 @but80 @davidkleiven @lsst-lpc (@sbinet) @matrix-profile-foundation (@aouyang1) @sfluor

**Comment by sbinet** [comment]
Fine by me.
(I'll update the packages for lsst-lpc)

**Comment by davidkleiven** [comment]
Fine by me. I'll update the package.

> I can just move it to fourier/window, if there are no other dsp algorithm in mind except fourier.

I think **dsp** is good. Maybe at some point one would like to implement wavelet transforms (e.g. Daubechies-family).

**Comment by aouyang1** [comment]
I’m happy to make the updates to the packages as well.

**Comment by sfluor** [comment]
Fine by me too :+1: , I will update the package (for musig)
