### ISSUE TITLE
Feature Request: Interpolation of missing values

### ISSUE THREAD

**Issue by pjebs** [gonum/gonum#1225]
It would be great if such a feature was provided. not just basic linear interpolation.

eg. https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.interpolate.html

**Comment by jonreiter** [comment]
coincidentally i'm looking at exactly this.  any thoughts please [on this](https://github.com/jonreiter/gonum/tree/interp).

there you'd call Resample on an interpolation Algo instance and pass in a checker function which flags invalid values.  it's a lot more generic than that pandas function.

**Comment by pjebs** [comment]
Is there some sample code how to use your technique?

I was looking at: https://github.com/DzananGanic/numericalgo

**Comment by jonreiter** [comment]
i just pushed an examples.go to my fork.

i am not familiar with that other project at all.

**Comment by mpcsb** [comment]
@jonreiter Have you considered merging your developments to the interp package?
@romanwerpachowski

**Comment by pjebs** [comment]
I ended up implementing it myself in my package: https://github.com/rocketlaunchr/dataframe-go

**Comment by jonreiter** [comment]
@mpcsb i wasn't aware of that package but yes looks interesting.  Have also looked over the data frame approach mentioned here.

The direction is need something that can interpolate/sample from gonum vectors and matrices with v a pluggable interpolation scheme setup.  But I don't care about any of the convenience/usability tagging that comes from a data frame.  I'd like to pass in an interpolated object as a gonum vector or matrix.

Sometimes for a matrix I need something like linear interpolation along the columns but something much heavier along the rows.  I want to hide that inside this sort of approach.

I am not sure the best way to get there.  At first it sounds like image rescaling but it's not- for my problems the interpolation approach depends on which axis you are talking about and should be kept separate.

I don't have a clean full proposal yet...but it is nice to see several reasonably-similar approaches to the problem are around now.
