### ISSUE TITLE
Please use bits.RotateLeft64()

### ISSUE THREAD

**Issue by vigna** [gonum/gonum#1227]
Testing made by Pekka Pulkkinen suggests that the compiler probably uses some intrinsics when compiling bits.RotateLeft64() and that the same does not happen if you use your own rotate function.

https://github.com/gonum/gonum/blob/08917b489e18b1b9c4e53e273d2f1b2bacf6dcdb/mathext/prng/prng_di_unimi.go#L254

**Comment by sbinet** [comment]
according to https://golang.org/pkg/math/bits/#RotateLeft64`, bits.RotateLeft64 was introduced in Go-1.9.
so we theoretically wouldn't even have to introduce a build tag :)

fancy sending a PR ? :)

**Comment by kortschak** [comment]
It would be nice to see whether the asm that gets generated is different.

**Comment by kortschak** [comment]
OK, so here is the difference.

current:
```
0x0035 00053 (/home/daniel/src/gonum.org/v1/gonum/mathext/prng/prng_di_unimi.go:99)	MOVQ	BX, 16(AX)
	0x0039 00057 (<unknown line number>)	NOP
	0x0039 00057 (/home/daniel/src/gonum.org/v1/gonum/mathext/prng/prng_di_unimi.go:255)	ROLQ	$45, DI
	0x003d 00061 (/home/daniel/src/gonum.org/v1/gonum/mathext/prng/prng_di_unimi.go:101)	PCDATA	$0, $0
	0x003d 00061 (/home/daniel/src/gonum.org/v1/gonum/mathext/prng/prng_di_unimi.go:101)	MOVQ	DI, 24(AX)
```

using `bits.RotateLeft64`:
```
0x0035 00053 (/home/daniel/src/gonum.org/v1/gonum/mathext/prng/prng_di_unimi.go:100)	MOVQ	BX, 16(AX)
	0x0039 00057 (/home/daniel/src/gonum.org/v1/gonum/mathext/prng/prng_di_unimi.go:102)	ROLQ	$45, DI
	0x003d 00061 (/home/daniel/src/gonum.org/v1/gonum/mathext/prng/prng_di_unimi.go:102)	PCDATA	$0, $0
	0x003d 00061 (/home/daniel/src/gonum.org/v1/gonum/mathext/prng/prng_di_unimi.go:102)	MOVQ	DI, 24(AX)
```

So it looks like it's worth doing.

**Comment by kortschak** [comment]
Finger fumble.
