### ISSUE TITLE
../../../gonum.org/v1/gonum/lapack/gonum/lapack.go:39:15: syntax error: unexpected p, expecting semicolon or newline or )

### ISSUE THREAD

**Issue by rcoreilly** [gonum/gonum#1283]
from my current travis builds:

../../../gonum.org/v1/gonum/lapack/gonum/lapack.go:39:15: syntax error: unexpected p, expecting semicolon or newline or )

**Comment by kortschak** [comment]
I'm sorry, there is not nearly enough information here to be able to debug this. Please use the bug reporting template. Since it's gone now, you can get it from [here](https://github.com/gonum/gonum/blob/master/.github/ISSUE_TEMPLATE/bug_report.md). A link to your travis failure would also be helpful.

**Comment by kortschak** [comment]
However, I suspect that this is because you are not running Go version 1.13 or 1.14.

**Comment by rcoreilly** [comment]
Yep, now that I look more carefully, I see that the 1.13 build is working and 1.11 and 1.12 are not.  I guess I missed that key point in all the discussion a while back, that only 1.13 and up are supported.  Might be good to add that to the main README page.  I'll add that to mine now and fix the travis things.

**Comment by kortschak** [comment]
I think it's pretty explicit in the [README](https://github.com/gonum/gonum#supported-go-versions).

**Comment by rcoreilly** [comment]
I would expect something more like "as of 3/2020, Go versions earlier than 1.13 are no longer supported" and perhaps an brief email to the email list -- this seems to have occurred very recently and again caught me by surprise.

Not everyone is so fastidious about updating things :)

**Comment by kortschak** [comment]
Yeah. Having text that needs to be changed in parallel with the code is asking for failures which even greater levels of confusion resulting; the link in the README points to the lines of the travis configuration that specify the tested versions and so is always correct (by definition).

We have no planned changes that will break people using 1.13 when its support is dropped (although this may change if there are new features that we need); the changes from 1.10 through to 1.13 had a lot of things that we wanted to use, so there was some damage to client code using older versions of Go.

**Comment by kortschak** [comment]
I agree, we could send an email to gonum-dev. I'll try to remember to do this in August.

**Comment by kortschak** [comment]
Out of curiosity, are you using modules? You should not notice changes to support if you are since your Gonum version will be pinned.

**Comment by rcoreilly** [comment]
no not using modules: https://github.com/golang/go/issues/37755

**Comment by SpartakRu88** [comment]
Hello, Guys. I still have such problem with version go version go1.14.2 linux/amd64,
How can I fix that?
![image](https://user-images.githubusercontent.com/63638372/79203946-73914e80-7e44-11ea-80eb-d92d330f15d7.png)

**Comment by sbinet** [comment]
are you sure `Bazel` is calling that `go` binary?

**Comment by kortschak** [comment]
Yeah, I don't think this is us. I suspect that you have bazel configured to use an older version of Go that is lying around somewhere. Without a reproducer, I don't think there is anything we can do to help here.

**Comment by SpartakRu88** [comment]
In WORKSPACE i have next:
go_repository(
    name = "com_github_milosgajdos_go_estimate",
    importpath = "github.com/milosgajdos/go-estimate",
    sum = "h1:r9sO0xYriwc/geKOOe+uKKtP31JjYgxsZldrZO0gaXQ=",
    version = "v0.0.0-20200225195609-9b3ac7df4a55",
)
So I think i'm calling right binary.

**Comment by egonelbre** [comment]
@SpartakRu88 based on the error message I'm guessing that Bazel is using an older version of Go to compile.

**Comment by SpartakRu88** [comment]
How to check it? I install bazel-3.0.0. So I'm a little wondering why it is not using the latest version of Go. Any ideas how to fix it?

**Comment by sbinet** [comment]
with no idea on how to debug Bazel, a possible strategy would be to create a test package `"example.com/my/pkg"`, compile it with your machinery and add Go build tags to one file with a compile error to detect when it's being considered by the Go compiler that Bazel uses.

_e.g.:_
```go
// +build go1.14

package foo

XXX
```

**Comment by SpartakRu88** [comment]
Anyway. Thank you guys for help. Just update bazel rules and seems start working. At least I have another error.

**Comment by sbinet** [comment]
in Gonum?
