### ISSUE TITLE
graph: Inconsistent ID when using two distinct graphs

### ISSUE THREAD

**Issue by amitlevy21** [gonum/gonum#1308]
### What are you trying to do?
I have the following functions:
<details>

<summary>Code:</summary>

```go
// Equal check if g and o are equal, meaning, they have the same nodes and edges.
// See EqualNodes and EqualEdges for more info.
func (g *Graph) Equal(o *Graph) bool {
	if g == o {
		return true
	}
	if !g.EqualNodes(o) {
		return false
	}
	if !g.EqualEdges(o) {
		return false
	}
	return true
}

// EqualEdges checks if g and o have the same pointing edges with same weights.
func (g *Graph) EqualEdges(o *Graph) bool {
	ge := g.WeightedEdges()
	oe := o.WeightedEdges()
	for ge.Next() {
		e1 := ge.WeightedEdge()
		if !oe.Next() {
			return false
		}
		e2 := oe.WeightedEdge()
		fmt.Printf("e1.From().ID(): %d\n", e1.From().ID())
		fmt.Printf("e2.From().ID(): %d\n", e2.From().ID())
		if e1.From().ID() != e2.From().ID() {
			return false
		}
		fmt.Printf("e1.To().ID(): %d\n", e1.To().ID())
		fmt.Printf("e2.To().ID(): %d\n", e2.To().ID())
		if e1.To().ID() != e2.To().ID() {
			return false
		}
		if e1.Weight() != e2.Weight() {
			return false
		}
	}
	if oe.Next() {
		return false
	}
	return true
}
```
</details>

And I'm trying to fully cover those with the following tests:
<details>

<summary>Tests:</summary>

```go
func TestEqualSelf(t *testing.T) {
	g1 := NewGraph()
	if !g1.Equal(g1) {
		t.Errorf("empty graphs should equal")
	}
}

func TestEqualEmpty(t *testing.T) {
	g1 := NewGraph()
	g2 := NewGraph()
	if !g1.Equal(g2) || !g2.Equal(g1) {
		t.Errorf("empty graphs should equal")
	}
}

func TestNotEqualNodes(t *testing.T) {
	g1 := NewGraph()
	g2 := NewGraph()
	g1.AddNode(g1.NewNode())
	if g1.Equal(g2) || g2.Equal(g1) {
		t.Errorf("graphs should not equal")
	}
}

func TestEqualNodes(t *testing.T) {
	g1 := NewGraph()
	g2 := NewGraph()
	g1.AddNode(g1.NewNode())
	g2.AddNode(g2.NewNode())
	if !g1.Equal(g2) || !g2.Equal(g1) {
		t.Errorf("graphs should equal")
	}
}

func TestNotEqualEdges(t *testing.T) {
	g1 := NewGraph()
	g2 := NewGraph()
	n1 := g1.NewNode()
	g1.AddNode(n1)
	n2 := g1.NewNode()
	g1.AddNode(n2)
	n1 = g2.NewNode()
	g2.AddNode(n1)
	n2 = g2.NewNode()
	g2.AddNode(n2)
	g1.SetWeightedEdge(g1.NewWeightedEdge(n1, n2, 0))
	if g1.Equal(g2) || g2.Equal(g1) {
		t.Errorf("g1 should not equal g2")
	}
}

func TestEqualEdgesToDiffNodes(t *testing.T) {
	g1 := NewGraph()
	g2 := NewGraph()
	n1 := g1.NewNode()
	g1.AddNode(n1)
	n2 := g1.NewNode()
	g1.AddNode(n2)
	g1.SetWeightedEdge(g1.NewWeightedEdge(n1, n2, 0))
	n1 = g2.NewNode()
	g2.AddNode(n1)
	n2 = g2.NewNode()
	g2.AddNode(n2)
	g2.SetWeightedEdge(g2.NewWeightedEdge(n2, n1, 0))
	if g1.Equal(g2) || g2.Equal(g1) {
		t.Errorf("graphs should not equal")
	}
}

func TestEqualEdgesDiffWeight(t *testing.T) {
	g1 := NewGraph()
	g2 := NewGraph()
	n1 := g1.NewNode()
	g1.AddNode(n1)
	n2 := g1.NewNode()
	g1.AddNode(n2)
	g1.SetWeightedEdge(g1.NewWeightedEdge(n1, n2, 0))
	n1 = g2.NewNode()
	g2.AddNode(n1)
	n2 = g2.NewNode()
	g2.AddNode(n2)
	g2.SetWeightedEdge(g2.NewWeightedEdge(n1, n2, 1))
	if g1.Equal(g2) || g2.Equal(g1) {
		t.Errorf("graphs should not equal")
	}
}
```
</details>

But the coverage reports different percentage every time I run:  `go test -coverprofile=coverage1.out -covermode atomic`  because the nodes ID's of graphs g and o does not match.

### What did you do?

I ran with no code changes between runs:
`go test -coverprofile=coverage1.out -covermode atomic`
`go test -coverprofile=coverage2.out -covermode atomic`
`go test -coverprofile=coverage3.out -covermode atomic`

### What did you expect to happen?
Coverage tool should tell 100% coverage or at least be consistent.
When I do:
```go
	g1 := NewGraph()
	g2 := NewGraph()
	n1 := g1.NewNode()
	g1.AddNode(n1)
	n2 := g1.NewNode()
	g1.AddNode(n2)
	g1.SetWeightedEdge(g1.NewWeightedEdge(n1, n2, 0))
	n1 = g2.NewNode()
	g2.AddNode(n1)
	n2 = g2.NewNode()
	g2.AddNode(n2)
	g2.SetWeightedEdge(g2.NewWeightedEdge(n1, n2, 0))
```
I expect g1 and g2 to have nodes with ids 0 and 1 and a weighted edge of 0 cost between them.

### What actually happened?
Sometimes g2 gets a different id as shown below:
Inconsitent coverage:
<details>

```
$ go test -coverprofile=coverage1.out -covermode atomic
e1.From().ID(): 1
e2.From().ID(): 0
e1.From().ID(): 0
e2.From().ID(): 0
e1.To().ID(): 1
e2.To().ID(): 1
e1.From().ID(): 0
e2.From().ID(): 0
e1.To().ID(): 1
e2.To().ID(): 1
PASS
coverage: 99.2% of statements
ok      github.com/amitlevy21/transportation    0.406s

$ go test -coverprofile=coverage2.out -covermode atomic
e1.From().ID(): 0
e2.From().ID(): 1
e1.From().ID(): 0
e2.From().ID(): 0
e1.To().ID(): 1  
e2.To().ID(): 1  
e1.From().ID(): 0
e2.From().ID(): 0
e1.To().ID(): 1  
e2.To().ID(): 1  
PASS
coverage: 97.5% of statements
ok      github.com/amitlevy21/transportation    0.368s

$ go test -coverprofile=coverage3.out -covermode atomic
e1.From().ID(): 0
e2.From().ID(): 1
e1.From().ID(): 0
e2.From().ID(): 0
e1.To().ID(): 1
e2.To().ID(): 1
e1.From().ID(): 0
e2.From().ID(): 0
e1.To().ID(): 1
e2.To().ID(): 1
PASS
coverage: 98.3% of statements
ok      github.com/amitlevy21/transportation    0.411s
```
</details>
I'm attaching the coverage files, as I ran `go tool cover -html=coverageX.out` and you can see there different coverage for graph.go:

(I had to add .txt at end of file so these would be uploaded to github)

[coverage1.out.txt](https://github.com/gonum/gonum/files/4452016/coverage1.out.txt)
[coverage2.out.txt](https://github.com/gonum/gonum/files/4452017/coverage2.out.txt)
[coverage3.out.txt](https://github.com/gonum/gonum/files/4452018/coverage3.out.txt)

### What version of Go and Gonum are you using?

Go version:
1.14.1
`grep gonum.org/v1/gonum go.sum`:

```
gonum.org/v1/gonum v0.0.0-20180816165407-929014505bf4/go.mod h1:Y+Yx5eoAFn32cQvJDxZx5Dpnq+c3wtXuadVZAcxbbBo=
gonum.org/v1/gonum v0.7.0 h1:Hdks0L0hgznZLG9nzXb8vZ0rRvqNvAcgAp84y7Mwkgw=       
gonum.org/v1/gonum v0.7.0/go.mod h1:L02bwd0sqlsvRv41G7wGWFCsVNZFv/k1xzGIxeANHGM=
```

### Does this issue reproduce with the current master?
I am running latest release

Sorry for the over detailed issue, I have tried to make a playgroud example but It does not reproduce [link](https://play.golang.org/p/E1PayXbtE-d)

**Comment by amitlevy21** [comment]
Closing since graph package is behaving as expected. No idea why coverage diverges between runs though.

**Comment by kortschak** [comment]
I don't know what your `NewGraph` or our `*Graph` do, but it is likely that it is using underlying Gonum code to iterate through edges. Edge iteration is non-deterministic by design. This would give you the behaviour you see.

**Comment by amitlevy21** [comment]
@kortschak thanks for your response, I though the iterator itself might be it. However I am using a weighted directed graph which it Edges() method always returns an iterator of ordered edges. Isn't [iterator.NewOrderedEdges(edges)](https://github.com/gonum/gonum/blob/master/graph/simple/weighted_directed.go#L80) always deterministic? If not, is there anything else I can use? or should I write something of my own?

Here are the missing methods:
```go
// Graph is always a weighted directed graph
type Graph struct {
	*simple.WeightedDirectedGraph
}

// NewGraph must be used to initialize a graph.
// self pointing edges (loops) are not allowed and considered with infinite
// weight. The weight of a non existent edge is infinite.
func NewGraph() *Graph {
	loopWeight := math.Inf(1)
	absentWeight := math.Inf(1)
	return &Graph{simple.NewWeightedDirectedGraph(loopWeight, absentWeight)}
}
```

The implementation of Edge iteration by WeightedDirectedGraph is expected to be

**Comment by kortschak** [comment]
It's deterministic in its iteration order given a determined input. If the input's ordering is not deterministic, then the ordering of iteration will not be determined between runs (it will be for each loop/reset case). You can see that [here](https://github.com/gonum/gonum/blob/448e2b6d0e3ffaded00aac84f34d17df7fac4d25/graph/simple/weighted_undirected.go#L261-L280); `for _, u := range g.edges` is a map range iteration.
