### ISSUE TITLE
Matrix interface docs not clear

### ISSUE THREAD

**Issue by pjebs** [gonum/gonum#1309]
For `At` and `Set` functions in docs, it's not clear if `row i, column j` are zero indexed or 1-indexed? In maths, the convention is 1-indexed. In Go, the convention is 0-index.

```go
type Matrix interface {
    // Dims returns the dimensions of a Matrix.
    Dims() (r, c int)

    // At returns the value of a matrix element at row i, column j.
    // It will panic if i or j are out of bounds for the matrix.
    At(i, j int) float64

    // T returns the transpose of the Matrix. Whether T returns a copy of the
    // underlying data is implementation dependent.
    // This method may be implemented using the Transpose type, which
    // provides an implicit matrix transpose.
    T() Matrix
}

type Mutable interface {
    // Set alters the matrix element at row i, column j to v.
    // It will panic if i or j are out of bounds for the matrix.
    Set(i, j int, v float64)

    Matrix
}
```

**Comment by kortschak** [comment]
Everything else in Go is zero indexed. The principle of least surprise says that you would expect that this is the case in Gonum as well.

Taking a quick look at the NumPy docs for [basic indexing](https://docs.scipy.org/doc/numpy/user/basics.indexing.html) they don't say that indexing np arrays are zero based either. I don't think this needs to be documented and more than it already is.
