### ISSUE TITLE
doc: add documentation for build tags used in gonum packages

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#131]
We use them, but we don't explain them anywhere.

**Comment by rpinheiroalmeida** [comment]
I'd like to be a contributor and also I want to help building some documentation. This is the kind of documentation that I can do.
So, what kind of build tags are you using? Or when I can find this build tags?
I guess with this information I write a documentation.

**Comment by kortschak** [comment]
This gives the complete list of out build tags.

```
$ grep -hIR +build | sort | uniq
//+build !amd64 noasm appengine
//+build appengine
//+build !appengine
//+build bounds
//+build !bounds
//+build cblas
// +build fortran
// +build !go1.7
// +build go1.7
// +build ignore
// +build !noasm,!appengine
// +build noasm appengine
//+build !noasm,!appengine
//+build tomita
//+build !tomita
```

The important ones are `noasm`, `appengine`, `cblas`, and `bounds`.

The `go1.7` and `fortran` are for testing, and `tomita` is a build option for `topo.VertexOrdering` (the details are in gonum/graph/topo/bron_kerbosch.go `(*bronKerbosch).choosePivotFrom`).
