### ISSUE TITLE
floats: adding a Filter() function?

### ISSUE THREAD

**Issue by rmadar** [gonum/gonum#1310]
Getting a sub-slice with elements passing a given condition is currently possible using the `floats.Find()` function, followed by a loop over returned indices.

I was thinking that it might be useful to have a `floats.Filter()` function, like:
```go
func Filter(dst []float64, src []float64, f func(float64) bool) []float64 {
	if dst == nil {
		dst = []float64{}
	}
	for _, x := range src {
		if f(x) {
			dst = append(dst, x)
		}
	}
	return dst
}
```
This would, I think, ease slice filtering and would read nicely:
```go
slice := []float64{1, 2, -99, 4, 5, -99, 7}
condition := func(x float64) bool { return x > 0 }
fmt.Println(Filter(nil, slice, condition))

// Output:
// [1 2 4 5 7]
```

go version: `1.14`
gonum version: `v0.7.1-0.20200330111830-e98ce15ff236`

**Comment by kortschak** [comment]
The floats package explicitly says that it does not allocate. Adding this would break that. An alternative that would fit the requirements of the package would be

```
// Filter copies elements from src to dst that satisfy cond and returns the number of elements copied.
func Filter(dst []float64, src []float64, cond func(float64) bool) int {
	t := dst[:0]
	for _, x := range src {
		if len(t) == len(dst) {
			break
		}
		if cond(x) {
			t = append(t, x)
		}
	}
	return len(t)
}
```

I think though, just rolling the loop is easier.

**Comment by rmadar** [comment]
Thanks for the reply, sorry I missed the "doesn't allocate" requirement. In that case, I agree with you: the explicit loop is easier. I'll close the issue.
