### ISSUE TITLE
Please reduce dependencies by not depending on netlib module anymore

### ISSUE THREAD

**Issue by stapelberg** [gonum/gonum#1313]
I’m updating an older project of mine to a newer version of gonum and noticed that it now pulls in a lot more dependencies:

```
% go list -m all | wc -l         
46
% go get -u gonum.org/v1/netlib
go: gonum.org/v1/netlib upgrade => v0.0.0-20200317120129-c5a04cffd98a
% go list -m all | wc -l
61
```

Since my code doesn’t pull in the netlib module, I checked where that dependency comes from, and it looks like mat/cblas_test.go verifies the netlib implementation works:
https://github.com/gonum/gonum/blob/015024673d2bbd05971e5baac93843f2c180e792/mat/cblas_test.go#L11

I understand that cblas_test.go isn’t compiled thanks to the `// +build cblas` line, but on the Go module level, that doesn’t matter: the netlib module is still pulled in when using gonum.

Could cblas_test.go be moved to the netlib repository instead, to make gonum a less heavyweight module to pull into projects please?

**Comment by kortschak** [comment]
I'm afraid cblas_test.go cannot be moved to another location and retain the behaviour that it has; it is there to allow testing and benchmarking of the mat package when the backing implementation is the Cgo wrapper. The only way to do this is to have it in the mat package. The question is really whether this can be deleted. This needs discussion.

**Comment by vladimir-ch** [comment]
Arguments for removing cblas_test.go:
* It's not used by our CI pipeline and I don't think it should be.
* It's easy to add locally if someone wants to test this combination manually.
* We don't do the same thing for lapack/netlib which has a much higher chance of deviation between implementations.
* Testing mat with blas/netlib should only catch what tests for blas/netlib missed. But thas is quite unlikely and in that case we should rather change those tests.

Arguments for keeping:
* Testing mat with blas/netlib could catch what tests for blas/netlib missed.

I'd be fine with removing.

**Comment by kortschak** [comment]
> I'd be fine with removing.

SGTM
