### ISSUE TITLE
Latest version from go get -u does not match github master

### ISSUE THREAD

**Issue by han-so1omon** [gonum/gonum#1332]
### What are you trying to do?
I am debugging an issue with the gonum.org/mat:FormatPython() function. It does not exist in the current version that I can pull, which is gonum-v0.7.0

### What did you do?
I am getting `timeout running go build` on play.golang.org. Below is the relevant code from my project.

```
package main

import (
	"fmt"
	"gonum.org/v1/gonum/mat"
)

func pyFormattedMat(m mat.Matrix) fmt.Formatter {
	return mat.Formatted(m, mat.Prefix("    "), mat.FormatPython())
}
```

### What did you expect to happen?
I expect this to work as noted in the docs.

### What actually happened?
I receive this error on build: `undefined: mat.FormatPython`

### What version of Go and Gonum are you using?
go version go1.14.2 linux/amd64
gonum.org/v1/gonum v0.0.0-20180816165407-929014505bf4/go.mod h1:Y+Yx5eoAFn32cQvJDxZx5Dpnq+c3wtXuadVZAcxbbBo=
gonum.org/v1/gonum v0.7.0 h1:Hdks0L0hgznZLG9nzXb8vZ0rRvqNvAcgAp84y7Mwkgw=
gonum.org/v1/gonum v0.7.0/go.mod h1:L02bwd0sqlsvRv41G7wGWFCsVNZFv/k1xzGIxeANHGM=

### Does this issue reproduce with the current master?
I think this is the problem. The current master has the function gonum.org/mat:FormatPython(), but the version pulled by go tools (v0.7.0) does not have this function.

**Comment by kortschak** [comment]
The new matrix formatting options are not available until the next release unless you use a non-semver pseudoversion in your go.mod file. You can do this by running `go get gonum.org/v1/gonum/mat@9c4b7c` (that's the current master).

Note that the godoc.org docs are not versioned, and will not be. If you want to see versioned docs, use pkg.go.dev.

**Comment by han-so1omon** [comment]
Thanks @kortschak . I'm going to close this issue. I think that the documentation for the current release version should be presented to the end-user on Github and the gonum.org website. It is confusing as is.

**Comment by kortschak** [comment]
Conventionally projects generally leave publishing of documentation up to godoc.org or pkg.go.dev. We could add a link to the go.pkg.dev page for gonum (this is gonum/website#24 and gonum/website#23).

Note that we still have other problems with the website which unfortunately sit fairly low on the priority list due to time constraints (gonum/website#10 gonum/website#11). Help with any of these is greatly appreciated.
