### ISSUE TITLE
graph/simple: add node indegree outdegree functions for graph implementations

### ISSUE THREAD

**Issue by awsl-dbq** [gonum/gonum#1346]
### What are you trying to do?

using `indegree := g.Indegree(id)` instand of `g.To(id).Len()`
using `outdegree := g.Outdegree(id)` instand of `g.From(id).Len()`
for `g.To` or `g.From` copy node data, it's slow . 

### What did you try?

g.To(id).Len()
or 
g.From(id).Len()

### How does Gonum not allow you to achieve your goal?
It's slow for big data. 
g.To or g.From copy node data,but I don't use this data.

### What version of Go and Gonum are you using?

go version go1.14.1 linux/amd64
gonum.org/v1/gonum v0.7.0
### Is this feature absent from the current master?
no

### Are you able to help contribute the feature?

yes
```
func (g *DirectedGraph) Indegree(id int64) int {
	return len(g.to[id])
}

func (g *DirectedGraph) Outdegree(id int64) int {
	return len(g.from[id])
}
```

**Comment by kortschak** [comment]
I don't think we will add this. The implementation of `g.From().Len()` and `g.To().Len()` is not fixed, and while it's true that currently these operations allocate for each no in the set, this is not necessarily true (an implementation change that is planned is to optimise this).

The graph implementations are starting points that satisfy the graph interfaces. You are welcome to copy the code and add this method, but making use of the method it not likely to be something that the gonum graph routines will do.

Can you give an example where this impacts on your work?

**Comment by kortschak** [comment]
Please see #1347.

**Comment by awsl-dbq** [comment]
> I don't think we will add this. The implementation of `g.From().Len()` and `g.To().Len()` is not fixed, and while it's true that currently these operations allocate for each no in the set, this is not necessarily true (an implementation change that is planned is to optimise this).
> 
> The graph implementations are starting points that satisfy the graph interfaces. You are welcome to copy the code and add this method, but making use of the method it not likely to be something that the gonum graph routines will do.
> 
> Can you give an example where this impacts on your work?

Hi ,
  Thank you very much.
  I'm trying to rewrite the stanford'snap code to go. It's in c++ and python except go.
  I'm trying to follow this example  https://github.com/snap-stanford/snap/tree/master/examples/cascadegen
  when debuging my code, I find it's more slow than the c++'s snap cascadegen.
  I 'm trying to find out the reason.
  In this line,
  https://github.com/snap-stanford/snap/blob/master/snap-core/casc.cpp#L155
  My go version code using gonum's graph , is slower than snap's version.
  so, I'm here to request a faster Indegree function.

**Comment by kortschak** [comment]
OK. So in the first instance, I would jut copy the code we have and use that with your modifications. This is a perfectly reasonable approach and part of the design intention with the simple/multi graph implementations. In the longer term, I'll get to issue I just filed (and later the unsafe version that will be a little faster).

**Comment by awsl-dbq** [comment]
> OK. So in the first instance, I would jut copy the code we have and use that with your modifications. This is a perfectly reasonable approach and part of the design intention with the simple/multi graph implementations. In the longer term, I'll get to issue I just filed (and later the unsafe version that will be a little faster).

OK, Thank you very much.

**Comment by kortschak** [comment]
I have implemented the lazy iterators. This is in https://github.com/gonum/gonum/tree/graph/lazy-nodes if you want to try it.

**Comment by awsl-dbq** [comment]
@kortschak  I will try it now. Thank you,Sir.

**Comment by awsl-dbq** [comment]
Thanks
