### ISSUE TITLE
Error with running go get -u gonum.org/v1/gonum/...

### ISSUE THREAD

**Issue by zwilson999** [gonum/gonum#1362]
### What are you trying to do?
Install Gonum

### What did you do?
simply used ```go get -u gonum.org/v1/gonum/...```

### What did you expect to happen?
install gonum

### What actually happened?
```package gonum.org/v1/gonum/...: unrecognized import path "gonum.org/v1/gonum": reading https://gonum.org/v1/gonum?go-get=1: 404 Not Found```

### What version of Go and Gonum are you using?
go version go1.14.4 windows/amd64

**Comment by zwilson999** [comment]
Actually. Had a silly download issue with Go and I think I figured out my issue. This can be marked as solved. Thanks.

**Comment by kortschak** [comment]
Dup of gonum/website#9.
