### ISSUE TITLE
parameters / setParameters or MarshalParameters / UnmarshalParameters in stat/distuv?

### ISSUE THREAD

**Issue by romanwerpachowski** [gonum/gonum#1365]
Some distributions in `stat/distuv` implement functions `parameters` and `setParameters` to return and set distribution parameters from a `[]Parameter` slice, while others implement `MarshalParameters` and `UnmarshalParameters` to do exactly the same thing (the comments for the latter mention a `ParameterMarshaler` interface, which AFAIK doesn't exist). That seems a bit messy. Can we settle on one set of methods, and which one should it be?

**Comment by kortschak** [comment]
The background for this is https://github.com/gonum/stat/pull/31 and the changes in https://github.com/gonum/stat/pull/32. It looks like the `MarshalParameters` and `UnmarshalParameters` that still exist were missed. They should be removed.

**Comment by romanwerpachowski** [comment]
OK, will do.
