### ISSUE TITLE
stat/distuv.Beta: Beta{Alpha: 1, Beta: 1}.Prob(0) == NaN

### ISSUE THREAD

**Issue by goccmack** [gonum/gonum#1377]
### What are you trying to do?
Computing the probability function of Beta(1,1) at various x,  0 <= x <= 1.

### What did you do?
distuv.Beta{Alpha: 1, Beta: 1}.Prob(0)

### What did you expect to happen?
I expected distuv.Beta{Alpha: 1, Beta: 1}.Prob(0) == 1

### What actually happened?
The result is NaN.

### What version of Go and Gonum are you using?
> go version
go version go1.14.2 darwin/amd64

> grep gonum.org/v1/gonum go.sum
gonum.org/v1/gonum v0.0.0-20180816165407-929014505bf4/go.mod h1:Y+Yx5eoAFn32cQvJDxZx5Dpnq+c3wtXuadVZAcxbbBo=
gonum.org/v1/gonum v0.7.0 h1:Hdks0L0hgznZLG9nzXb8vZ0rRvqNvAcgAp84y7Mwkgw=
gonum.org/v1/gonum v0.7.0/go.mod h1:L02bwd0sqlsvRv41G7wGWFCsVNZFv/k1xzGIxeANHGM=
R

### Does this issue reproduce with the current master?
I haven't tried it.

**Comment by romanwerpachowski** [comment]
It's in current master. Looking at it.

**Comment by goccmack** [comment]
Thanks Roman. That works.
