### ISSUE TITLE
all: fix package doc and canonical imports for some packages

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#14]
See https://github.com/gonum/gonum/pull/13#issuecomment-304000258

- [x] ~~gonum.org/v1/gonum~~ later
- [ ] gonum.org/v1/gonum/graph/ex/fdpclust
- [x] gonum.org/v1/gonum/lapack
- [x] gonum.org/v1/gonum/lapack/testlapack
- [x] gonum.org/v1/gonum/mathext
- [x] gonum.org/v1/gonum/optimize/convex/lp
- [x] ~~gonum.org/v1/gonum/unit/autogen~~ This has been removed.

Some of these e.g. unit/autogen should probably just be made a `// +build ignore` file in their package.

**Comment by Kunde21** [comment]
Ping @kortschak @btracey 

Are there packages that haven't been fixed to address this issue?

**Comment by kortschak** [comment]
Some internal graph packages probably want this.

https://godoc.org/gonum.org/v1/gonum

**Comment by vladimir-ch** [comment]
Can this be closed? At https://godoc.org/gonum.org/v1/gonum it seems that all packages have a doc comment except for `unit/internal` which can be removed altogether and `unit/internal/autogen.go` can be moved to `unit/generate_unit.go`.

**Comment by kortschak** [comment]
SGTM
