### ISSUE TITLE
 mat.Formatted(x, mat.Prefix("-"), mat.Squeeze()) doesn't format first elem from vector

### ISSUE THREAD

**Issue by jcbritobr** [gonum/gonum#1404]
Windows 10 amd64, go version 1.14

### What are you trying to do?
I'm trying to format a vec using mat.Formatted() and mat. Prefix()

### What did you do?
the first elment printed doesn't receive the prefix
```go
func matPrint(x mat.Matrix) {
	fa := mat.Formatted(x, mat.Prefix("-"), mat.Squeeze())
	fmt.Printf("%v\n", fa)
}
```

### What did you expect to happen?
print 
```
-⎡  5⎤
-⎢8.3⎥
-⎣  9⎦
```
### What actually happened?
```
⎡  5⎤
-⎢8.3⎥
-⎣  9⎦
```

### What version of Go and Gonum are you using?
I'm using go modules, go version 1.14
	golang.org/x/exp v0.0.0-20200513190911-00229845015e // indirect
	golang.org/x/tools v0.0.0-20200714190737-9048b464a08d // indirect
	gonum.org/v1/gonum v0.7.0

### Does this issue reproduce with the current master?
Not tested. I don't know if I'm in master branch

**Comment by kortschak** [comment]
This is working as intended. The documentation should be clarified though. The point of the prefix is to allow alignment of the matrix properly when there is text preceding the first line.
