### ISSUE TITLE
"All rights reserved." in LICENSE

### ISSUE THREAD

**Issue by qlcom** [gonum/gonum#1427]
Do gonum Authors really want that?

**Comment by sbinet** [comment]
Gonum's License is the same one than Go's (_ie:_ BSD-3):

- https://github.com/golang/go/blob/master/LICENSE#L1

if it's good for Go, why wouldn't it be for Gonum?
(it's an honest question.)

what issue or problem do you think that could cause?

**Comment by qlcom** [comment]
I hope Go Authors will remove this sentence for their License.

**Comment by qlcom** [comment]
The License template for new code in OpenBSD doesn't have this sentence.

**Comment by qlcom** [comment]
https://cvsweb.openbsd.org/src/share/misc/license.template?rev=HEAD

**Comment by qlcom** [comment]
I opened an on golang/go https://github.com/golang/go/issues/40709

**Comment by qlcom** [comment]
I need other peoples help.

**Comment by kortschak** [comment]
If this is actually an issue, the appropriate format would be a submission of a [proposal format](https://github.com/gonum/gonum/issues/new?template=proposal.md) issue. There is not enough information here to explain why this is something that we should worry about. My understanding (as a non-lawyer who is interested in aspects of intellectual property) is that the phrase makes little difference, though with the inherent conservatism of law leaving it in is likely to be safer, and taking it out will take a non-zero amount of work.

**Comment by kortschak** [comment]
Closing at the (off-line) request of the author.
