### ISSUE TITLE
lapack: remove Dlansb and Dlantb from Float64 interface

### ISSUE THREAD

**Issue by vladimir-ch** [gonum/gonum#1428]
I'd like to remove Dlansb and Dlantb from the lapack.Float64 interface. The reason is that LAPACKE doesn't provide wrappers for these two functions but by having them in lapack.Floa64 our lapack/netlib implementation must somehow provide them. I thought that a good solution would be to work around/hide this by having a copy of our Go implementation of them in the lapack/netlib package. However, now I think it's not great because:
* it gives the wrong impression that netlib.Dlansb and netlib.Dlantb call into the underlying (non-Go, optimized) implementation,
* it creates a maintenance burden on us by having the same code in two repositories that should be kept identical,
* these two functions depend on other lapack functions that have to be brought along and maintained as per previous point.
Therefore I'd like to revert this decision and remove them from lapack.Float64.

My original intention of having them in lapack.Float64 (and in lapack64) in the first place was to make these functions available to the clients of this interface, the main one being our mat package. Now I think that the client code should rather call into lapack/gonum explicitly for functions that lapacke doesn't provide but it also has a couple of downsides:
* it creates a hard dependency of the client code (mat package) on lapack/gonum, possibly leading to increased build time and binary size,
* we typically document functions in lapack/gonum as internal and exported only for testing purposes (although I see that I forgot to add this notice to Dlansb and Dlantb). This would break this convention.

Of course, there are many LAPACK routines that LAPACKE doesn't provide and we don't mind but these norm-computing routines are slightly different. The mat package provides corresponding matrix types (band symmetric, band triangular) and we need to be able to compute their norm somehow. Using Dlansb and Dlantb for that would be the most natural choice.

Any other opinions or ideas?

**Comment by kortschak** [comment]
I think it's OK to move directly to v0.8.1 and remove these (see https://groups.google.com/g/gonum-dev/c/qgqbkNPLTNU/m/WhyB0TWMCAAJ).
