### ISSUE TITLE
gonum/floats/scalar/scalar.go:20:29: syntax error: unexpected p after top level declaration

### ISSUE THREAD

**Issue by kurianCoding** [gonum/gonum#1433]
### What are you trying to do?
install gonum package

### What did you do?

go get -u gonum.org/v1/gonum/...

### What did you expect to happen?
fetch gonum and and install without errors

### What actually happened?
error in title

### What version of Go and Gonum are you using?

go version go1.12 darwin/amd64

### Does this issue reproduce with the current master?

yes

**Comment by kortschak** [comment]
Gonum does not support go1.12 and uses feature that were added to the language after that version. This is one of those features (https://golang.org/ref/spec#Floating-point_literals) which was added in [Go 1.13](https://golang.org/doc/go1.13#language) (see Hexadecimal floating point literals).
