### ISSUE TITLE
Is there any possibility of GF(2) matrix support?

### ISSUE THREAD

**Issue by nathanhack** [gonum/gonum#1439]
Has there been any thoughts/requests for supporting GF(2) matrices?

**Comment by vladimir-ch** [comment]
I think that such discrete-mathematical structures are out of scope of Gonum, we already have more than enough with linear algebra over real and complex numbers. If you want to elaborate on your needs for this, then I suggest you take the discussion to [gonum-dev](https://groups.google.com/g/gonum-dev).
