### ISSUE TITLE
dsp/window: window widths of Tukey v other functions do not match

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#1442]
It's been gently pointed out to me that #1242 was the wrong thing to do; the way we decided to make the windows in #1240 was to only keep the non-zero weights based on the fact that the region outside the window would be zeroed.

This is not the behaviour of the new Tukey implementation (which can be seen by removing the Hann call optimisation). If the windows' behaviours are known to only contain the non-zero weights then the user can zero the preceding and following values. However, this is less ergnomic than it could be, and the behaviour differs from the Rectangular window where this should not be done, leaving it not possibly to have drop-in replacement between these different classes of window.

On this basis, I'm going to revert #1242. The alternative is to bring Tukey into the same scheme.

**Comment by vladimir-ch** [comment]
I'm not sure it was the wrong thing to do, maybe unconventional, so I'd like to read some literature first before reviewing #1443 .

My current, preliminary view is as follows: in the continuous case, you have a signal and the window function with a compact support, you multiply them and integrate. In the discrete case you integrate numerically, only that you have no control or knowledge over how the signal has been sampled, the samples are given. You do have a freedom in placing and sampling of the window function. Current dsp package takes point samples of the window function, assumes that signal has been sampled at the same points and multiplies them pairwise. Before #1242 we did what could be called "node-centered" sampling, after #1242 we shift the window function by half sample and do "cell-centered" sampling. In my opinion both approaches are valid but the "node-centered" sampling brings two difficulties:

1. (minor point) With most windows the first and last sample are always zero and so more information than necessary is lost.
2. With Rectangular window both end nodes fall at the point of a jump discontinuity and we have to decide which side limit we take. At both ends we take the value of 1 but that's arbitrary and even inconsistent if we interpret samples as "values to the right". 

As I wrote, shifting the window function by half sample spacing might go against established conventions or even be incorrect, so I'd like to study more about it.

> However, this is less ergnomic than it could be,

Could you elaborate? What do you mean by 'less ergonomic'?

**Comment by kortschak** [comment]
> Could you elaborate? What do you mean by 'less ergonomic'?

So, say we have a sequence that we want to window to pass to an FFT. The reason we're using a window is to ensure that we don't have a discontinuity, so we want the first and last elements of the sequence to be zero. This can be achieved either by using the window functions as they were prior to #1242 without any additional work, or with the change in #1242 in place the first and last elements of the sequence can be explicitly zeroed and the window then applied to all the remaining elements. The effect is identical. However there is more work in the second case, and some users may not be aware of this requirement notwithstanding the note in the package documentation. In addition to this, the rectangular window would not have the first and last elements zeroed since it is defined as not altering the sequence. Further some of the non-rectangular windows have non-zero weights at the first and last positions which we currently incorrectly discard (Gaussian for example) (this is not an ergonomics issue but a correctness one).

**Comment by vladimir-ch** [comment]
> The reason we're using a window is to ensure that we don't have a discontinuity, so we want the first and last elements of the sequence to be zero.

I still don't understand. What is the difference between explicit zeros in the first and last element, and implicit zeros just outside the slice?

> Further some of the non-rectangular windows have non-zero weights at the first and last positions which we currently incorrectly discard (Gaussian for example)

Gaussian is a slightly different case because it must be truncated, it doesn't have compact support and is positive everywhere.

**Comment by kortschak** [comment]
This [Siemens article](https://community.sw.siemens.com/s/article/windows-and-spectral-leakage) explains it quite nicely.

What we want to achieve is this.

![continuous sequence by weighting end points to zero](https://community.sw.siemens.com/servlet/rtaImage?eid=ka54O000000PJM0&feoid=00N4O000006LZn5&refid=0EM4O000001130u)

If we have non-zero weights at the end, we get something like this (though less severe because it is weighted to near zero - it will still have a potential discontinuity).

![discontinuous](https://community.sw.siemens.com/servlet/rtaImage?eid=ka54O000000PJM0&feoid=00N4O000006LZn5&refid=0EM4O000001130r)

With the code as it stands we can get zero at the windowed end points, but it's not done by the window function, it must be done by the user. With the proposed reversion, it just happens.

The difference between the windows that have a zero in the window function's end points and those that don't (BlackmanHarris, BlackmanNuttall, FlatTop, Gaussian, Hamming, Rectangular and Tukey) means that users need to know when to zero the end points and when not to. This is obviously prone to failure.

**Comment by kortschak** [comment]
I found this helpful, https://www.dsprelated.com/showarticle/1211.php. Note the comments in "Spectrum of the Hanning Window" about losing the first and last values.

**Comment by vladimir-ch** [comment]
Thanks for the links, they helped me think about the issue more. I understand that the explicit zeros are actually important to have and so reverting to before #1242 it the right thing to do.

I also see the difference between before and after #1242: they don't apply the same window. Windows after #1242 are one sample wider and shifted by half sample. If before #1242 a window's support begins at index 0 and ends at index n (that is, dst[0]=dst[n]=0), then after #1242 the supports begins at (non-existent) index -1/2 and ends at index n+1/2.
