### ISSUE TITLE
mat: missing return for VecDense.MulVec in TriDenseCase

### ISSUE THREAD

**Issue by argusdusty** [gonum/gonum#1448]
The [VecDense.MulVec](https://github.com/gonum/gonum/blob/f883758f082bd1f138ab0155a5c2677edd09b320/mat/vector.go#L556) function has the [TriDense case](https://github.com/gonum/gonum/blob/f883758f082bd1f138ab0155a5c2677edd09b320/mat/vector.go#L631):
```go
switch aU := aU.(type) {
...
case *TriDense:
	v.CopyVec(b)
	aU.checkOverlap(v.asGeneral())
	ta := blas.NoTrans
	if trans {
		ta = blas.Trans
	}
	blas64.Trmv(ta, aU.mat, v.mat)
...
}
```
that lacks a return value, meaning that the code then proceeds on to the inefficient backup code at the bottom of the function. This causes slowdown in cases where MulVec is called with a TriDense matrix (for example, distmv.StudentsT.Rand).

**Comment by kortschak** [comment]
Thanks, I have sent a fix.
