### ISSUE TITLE
stat/distuv: Improve performance of Gamma.Rand in Alpha > 1 case

### ISSUE THREAD

**Issue by argusdusty** [gonum/gonum#1453]
In the current Gamma.Rand code, when Alpha > 1, it uses [the following loop](https://github.com/gonum/gonum/blob/1839007961357eb896846276604907b28f214187/stat/distuv/gamma.go#L222):

```go
u := -exprnd()
x := normrnd()
v := 1 + x*c
v = v * v * v
if u < 0.5*x*x+d*(1-v+math.Log(v)) {
	return d * v / b
}
```

Replacing the above with code based on [numpy's logic](https://github.com/numpy/numpy/blob/9ee262b5bf89e8c866a507e4d62b78532361adc2/numpy/random/src/legacy/legacy-distributions.c#L67):
```go
x := normrnd()
v := 1 + x*c
if v <= 0.0 {
	continue
}
v = v * v * v
u := unifrnd()
if u < 1.0-0.0331*(x*x)*(x*x) {
	return d * v / b
}
if math.Log(u) < 0.5*x*x+d*(1-v+math.Log(v)) {
	return d * v / b
}
```

Runs much faster - as the new initial check (`if u < ...`) catches most (specifically, ~92% of) cases and avoids an expensive call to `math.Log`. For a simple benchmark:
```go
package main

import (
	"testing"

	"gonum.org/v1/gonum/stat/distuv"
)

func BenchmarkGamma(b *testing.B) {
	dist := distuv.Gamma{Alpha: 2.0, Beta: 1.0}
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		dist.Rand()
	}
}
```

`go test -bench=. -benchtime=10s -cpu=1`
Old code: `BenchmarkGamma  207709526               57.0 ns/op`
New code: `BenchmarkGamma  345146806               34.6 ns/op`
Gives a 40% performance boost (windows/amd64). This should also improve performance for some other distributions (Beta/Dirichlet, StudentsT, etc).

A few existing statistical tests (specifically, InverseGamma - ExKurtosis, Beta - Entroy, and StudentsT - Variance) fail with the new code until you sufficiently increase the `n` sample sizes, indicating it's just sampling error.

**Comment by kortschak** [comment]
@romanwerpachowski Do you want to take/shepherd this?

**Comment by romanwerpachowski** [comment]
Yup.

**Comment by romanwerpachowski** [comment]
The condition `u < 1.0-0.0331*(x*x)*(x*x)` doesn't depend on `d`. Is that correct?

**Comment by argusdusty** [comment]
Yes, that's correct. Since `d > 2/3`, and `x > -1/c` (as `v > 0`), it can be shown that 0.0331 holds.

Setting the condition `1-a*x^4 > exp(x^2/2+d*(1-v+log(v)))` at `d=2/3` and solving for a yields:
https://www.wolframalpha.com/input/?i=maximize+%281-exp%280.5*x*x%2B2%2F3*%281-%281%2Bx%2F%283*sqrt%282%2F3%29%29%29%5E3%2Blog%28%281%2Bx%2F%283*sqrt%282%2F3%29%29%29%5E3%29%29%29%29%2Fx%5E4+for+x+%3E+-sqrt%286%29

Finds `a > ~0.033073` (round up to 0.0331) at `x~=-2.15621`

Larger `d` results in smaller `a`, but there's no easy way to compute it, so we can just use 0.0331 for all d.

**Comment by romanwerpachowski** [comment]
Thanks. Is there a derivation of this approximation which could be referenced in a comment?

Would you like to submit a PR with this change, also showing how much the sample sizes need to be increased to make other tests pass?

**Comment by argusdusty** [comment]
There's no simpler derivation that I'm aware of, but reading the paper that is already cited in a comment: https://dl.acm.org/doi/pdf/10.1145/358407.358414, they propose this approach as a squeeze function and provide a 3-step proof for it.

I'm sending out a PR with the change.

**Comment by romanwerpachowski** [comment]
Thanks a lot, I'll have a look at it.
