### ISSUE TITLE
About Interpolate package

### ISSUE THREAD

**Issue by lkeix** [gonum/gonum#1469]
### Background
When I handle time series data as Approximated function by collecting time series data using Go, Gonum provide plotting the time series data, we can see the time series data outline, but Gonum doesn't provide returning function's coefficient based on the time series data.
we have to use other language (e.g. Python) to calculate function's coefficient based on time series data. 

### Proposal
I want to calculate function's coefficient not using other language. So, I want to add interpolate package for Gonum.

### Potential impact of proposal
* Extent of change
  * add directory interpolate.
  * add cubic.go on interpolate dir.
  * add lagrange.go on interpolate dir.

* implementation detail
  * Cubic Interpolate.
  * Lagrange interpolation.

* who
  * me.

**Comment by kortschak** [comment]
Have you looked at the interp package? https://pkg.go.dev/gonum.org/v1/gonum/interp

If there are things that you need that are not there, suggesting addtions to that package would be the best way forward.

**Comment by lkeix** [comment]
I overlooked. Sorry.
I didn't know AkimaSpline. AkimaSpline seems better than Cubic Spline on not happening over shoot.

Thank you for your response.

**Comment by romanwerpachowski** [comment]
Hi Kei,

I'm the main author of the interp/ package. I was planning on adding natural cubic splines and some other methods to it. If you want to contribute to this package, I'll be happy to help.

Best,
Roman

**Comment by lkeix** [comment]
Hi Roman!

Thank you for replay.
I want to contribute this package.
If you have plan to implement other methods now, I'll help you!

**Comment by romanwerpachowski** [comment]
Great :) Do you want to take a stab at natural cubic splines? We don't have any C2 interpolator in the package now.

**Comment by lkeix** [comment]
OK!
I'll try to implement other spline methods (e.g. cubic spline, cubic B spline, Bezier spline). I'll mention you again, when I implemented it!

**Comment by romanwerpachowski** [comment]
Great :) Let me know if you need any help.

Thanks and best regards,
Roman

**Comment by romanwerpachowski** [comment]
Natural cubic spline was added in #1657.
