### ISSUE TITLE
mat: Inverse return error even though condition number is within range

### ISSUE THREAD

**Issue by melaurent** [gonum/gonum#1499]
### What are you trying to do?
Inverse a random matrix

### What did you do?

```
func TestSingular(t *testing.T) {
	for size := 10; size < 500; size += 10 {
		data := make([]float64, size * size)
		for i := range data {
			data[i] = rand.NormFloat64()
		}
		M := mat.NewDense(size, size, data)
		cond := mat.Cond(M, math.Inf(1))
		fmt.Println(fmt.Sprintf("Size: %d, Cond: %f", size, cond))
		res := &mat.Dense{}
		if err := res.Inverse(M); err != nil {
			t.Fatal(err)
		}
	}
}
```

```
Size: 10, Cond: 36.192444
Size: 20, Cond: 78.512922
Size: 30, Cond: 403.110746
Size: 40, Cond: 602.725103
Size: 50, Cond: 970.609080
Size: 60, Cond: 850.203528
--- FAIL: TestSingular (0.00s)
    line_lin_test.go:22: matrix singular or near-singular with condition number 1.5566e+18
FAIL
```

### What did you expect to happen?

A successful inversion of the non-singular matrix

### What actually happened?
An error saying that the matrix is singular even though the condition number with inf norm is bellow the threshold

### What version of Go and Gonum are you using?

go 1.13
gonum.org/v1/gonum v0.8.1 h1:wGtP3yGpc5mCLOLeTeBdjeui9oZSz5De0eOjMLC/QuQ=
gonum.org/v1/gonum v0.8.1/go.mod h1:oe/vMfY3deqTw+1EZJhuvEW2iwGF1bW9wwu7XCu0+v0=

### Does this issue reproduce with the current master?

Yes

**Comment by vladimir-ch** [comment]
Thanks for the report. I can reproduce the issue and it's a bug in `mat.Inverse`.

The condition number is computed by `Gecon` which expects the input matrix to contain the LU factorization. However, when `Gecon` is called the input contains the inverse matrix from the previous call to `Getri`. Our test unfortunately uses only tiny matrices where the incorrect condition number happens to be below the tolerance.

I'll fix it, hopefully soon.
