### ISSUE TITLE
spatial/{r2,r3}: provide a way to rotate a vector

### ISSUE THREAD

**Issue by sbinet** [gonum/gonum#1513]
### What are you trying to do?

it should be possible to rotate a, say, `r3.Vec` by some angle around a given axis (x,y,z) or around a user provided `r3.Vec`.

a possible API (for `r3`, `r2` is expected to be rather similar):
```go
package r3

func (p Vec) Rotate(angle float64, q Vec) Vec { ... }
```

we could also imagine providing a way to rotate a vector via rotation matrix:
```go
package r3

func Rotate(m *mat.Dense, p Vec) Vec { ... }
```

API to be discussed.

**Comment by kortschak** [comment]
Rotating around a 3 vector as shown in the first case is best done with a quaternion (lightly tested):
```
func (p Vec) Rotate(alpha float64, axis Vec) Vec {
	alpha /= 2
	q := raise(axis)
	q = quat.Scale(math.Sin(alpha)/quat.Abs(q), q)
	q.Real += math.Cos(alpha)
	if len := quat.Abs(q); len != 1 {
		q = quat.Scale(1/len, q)
	}
	pp := quat.Mul(quat.Mul(q, raise(p)), quat.Conj(q))
	return Vec{X: pp.Imag, Y: pp.Jmag, Z: pp.Kmag}
}

func raise(p Vec) quat.Number {
	return quat.Number{Imag: p.X, Jmag: p.Y, Kmag: p.Z}
}
```

R2 is trivial.

The API presented matches what we have (I recall an issue to discuss this, but I can't find it now).

**Comment by sbinet** [comment]
one could also expose a new type `Rotation`:
```go
type Rotation struct {
    q quat.Number
}

func NewRotation(alpha float64, axis Vec) Rotation {
 // lift from Vec.Rotate
}

func (rot Rotation) Rotate(p Vec) Vec {
    pp := quat.Mul(quat.Mul(rot.q, raise(p)), quat.Conj(rot.q))
    return Vec{X: pp.Imag, Y: pp.Jmag, Z: pp.Kmag}
}
```

to be able to repeatedly apply a 3d rotation, w/o incurring the cost of re-computing the same sin/cos values.

**Comment by kortschak** [comment]
That's probably a reasonably middle ground between a pure function and being able to do all the things that you can with quaternions in their pure form.
