### ISSUE TITLE
proposal: mat: provide non-conjugate transpose for CMatrix

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#1539]
### Background

I have had a query about non-conjugate transpose for complex matrices [on the gopher slack data-science channel](https://gophers.slack.com/archives/C0UKS8V9S/p1609624024198600). While my initial suggestion of implementing a local transpose type works (below), it prevents that transpose information being available to a BLAS or LAPACK back-end, both of which accept (variously) T and H (by various names) as trans parameters.

```
type Transpose struct {
	CMatrix mat.CMatrix
}

func (t Transpose) At(i, j int) complex128 {
	return t.CMatrix.At(j, i)
}

func (t Transpose) Dims() (r, c int) {
	c, r = t.CMatrix.Dims()
	return r, c
}

func (t Transpose) H() mat.CMatrix {
	return mat.Conjugate{t}
}
```

The inclusion of T in addition to H was briefly considered in gonum/matrix#283. Note the [comment](https://github.com/gonum/matrix/issues/283#issuecomment-173796281) which points to use of T/H confusion in the [LAPACK errata](https://www.netlib.org/lapack/Errata/errata-lapack-3.3.0.html#_strong_span_class_green_bug0024_span_strong_the_notation_a_is_confusing_for_complex_matrices_does_a_stand_for_a_transpose_of_a_hermitian_transpose). It's worth noting that while the documentation [linked in the comment](https://www.netlib.org/lapack/complex/) always refers to conjugate transpose, that it is in the context of describing `X**H`; the BLAS and LAPACK code *does* differentiate between T and H.

### Proposal

I propose adding a `T() CMatrix` method to `CMatrix`, the backing `CDense` implementation, and `CTranspose` and support types (`CUntransposer`?).

Adding the mechanisms for implicit transpose allows the transpose state to be given to backing routines in an efficient manner in the same way as is currently done for the real matrix types (when those API additions are made in mat).

### Potential impact of proposal

The addition of a new method to `CMatrix` is a breaking API change. However the number of users of complex matrices is likely to be low at the moment since very little API is provided (just enough to support `Eigen`). So if it should be added at some time it should be earlier than later.

There is some subtlety in how to deal with the case of `m.H().T()`/`m.T().H()` as inputs to back-end routines; this doesn't need to be dealt with immediately though probably just conjugating the elements of `m` into a workspace and working on that with `NoTrans` would be the best. I think to support this we should add a `Conj(CMatrix)` method that performs an element-wise conjugation on the argument, placing the result in the receiver.

It's worth noting that NumPy uses the matrix conjugate to [refer to element-wise conjugation](https://numpy.org/doc/stable/reference/generated/numpy.matrix.conjugate.html), not the conjugate transpose (which it uses [H as a method for](https://numpy.org/doc/stable/reference/generated/numpy.matrix.H.html) matching our approach). It may be worth considering renaming the `Conjugate` type (`ConjTranspose`?) and the associated interfaces. Again, there are few users of `CMatrix` now meaning that if the change should be made, it should be made earlier than later.

The implementation cost is minimal and I'm happy to do it.

/cc @notmgsk @btracey @vladimir-ch

**Comment by vladimir-ch** [comment]
> I propose adding a T() CMatrix method

This SGTM. Mathematically `T` isn't very useful but it may be when the matrix is treated as a 2d array to store complex numbers.

> I think to support this we should add a Conj(CMatrix)

Agreed. Maybe the method could be called `ConjElem` to avoid confusion with `H`?

**Comment by kortschak** [comment]
In looking into this, I saw that `T` is needed for complex-differentiability.

The request came from @notmgsk, so the use cases that he has would provide backing for the proposal.

**Comment by vladimir-ch** [comment]
Sure, I support the proposal.
