### ISSUE TITLE
PROPOSAL To add new functionality to Gonum's linear algebra packages, probably in or parallel to GONUM/mat

### ISSUE THREAD

**Issue by rejones7go** [gonum/gonum#1546]
### Background
LAPACK is of course the definitive package for linear equation solutions,
and is well integrated into Gonum (thanks to whoever did that!)
But lapack is quite old, and was defined before usable auto-regularizing methods were available. The package I am proposing provides a significant new capability for Go which would impact absolutely nothing else in the Go libraries. Logically it would just sit above gonum's svd decomposition.

I have supported a similar state-of-the-art C++ package for a decade.
Recently I have converted the primary functions from that package to Go (and Python).
Along the way I have had the opportunity to further "tune" the heuristic parameters in the package, based on further test  problems, to the benefit of all three version: C++, Python, and Go.
 
Please see the attached README file for some details.

[README.txt](https://github.com/gonum/gonum/files/5785158/README.txt)

Since you probably have not heard of this auto-regularizing package please see my website:
    http://www.rejtrix.net/
to see my currently released versions for C++, Python, and Go.
(The Python and C++ versions are more extensive, but those extensions may be too esoteric for most users.) There is also some tutorial material that will clarify what this package, called "Arls" there, can do. If you are not familiar with solving problematic linear systems, there is a brief tutorial there to introduce you to the issue.

### Proposal
I propose to add to Gonum my "larls" package of  automatically regularizing solvers for linear systems of equations. (It will be a little different than the code offered by my website because the license will have to change.) This code is completely done, very well tested, and edited based on Go's golint and other code sifters. I also have a larls-test package, with excellent code coverage, ready to deliver, modelled after existing similar gonum packages.

### Potential impact of proposal
This package is built on Gonum's mat package, including gonum's svd algorithm, which I believe just calls lapack. This is strictly an ADDITION to current gonum capabilities, so it should present no difficulties.

Exactly WHERE to put it is not my call... but I would suggest it  NOT be put it in LAPACK directly. It could go in gonum/mat, but I would suggest it would be much cleaner and less maintenance burden to go in a separate package in the gonum area, probably called "larls", to suggest its relation/reliance on lapack.

The main question for you might be whether you want any such current linear algebra capabilities, or whether you are happy with the current package, though there is no capability there for auto-regularization. Arls/larls/whatever also includes a solver than forces non-negativity, whether the system is in fact well-conditioned or ill-conditioned. This routine is a (much more reliable) update to the classic Lawson/Hanson NNLS.   

Interested?
Ron Jones rejones7@gmail.com

**Comment by kortschak** [comment]
Thanks, this does look like something that could fit into mat. I agree that it is not appropriate to go in the lapack implementation. I'll defer though to @vladimir-ch.

/cc @vladimir-ch

**Comment by rejones7go** [comment]
So what is my next step?
Ron Jones

**Comment by kortschak** [comment]
Sorry @rejones7go, waiting for @vladimir-ch. Germany is in lockdown, so time is not highly available.

**Comment by rejones7go** [comment]
HI... since I am still not busy due to Covid, I have now expanded this package to include all the features in my C++ and Python libraries. So now the user can combine the auto-regularization solver with both equality constraints, presented as arguments E (matrix) and f (RHS values), and inequality constraints (i.e., greater than constraints), presented as arguments G (matrix) and h (RHS values). One version accepts Ex==h in addition to.
 Ax=b;  another accepts Gx>=h in addition to Ax=b, and a final one accepts all three: x = Arlsall(A,b,E,f,G,h). 
(These solvers build nicely on each other, with no duplicated functionality in the code.)
These solvers handle redundant or conflicting constraints, and ill-conditioning among constraints (which should be very rare).  
I have placed all this code and the associated test routines (for "Go test") in this portion of my web site for your review http://www.rejones7.net/ArlsGo/index.htm 
(This has not been advertised to the public and Google hasn't scanned it.)
If you want me to place this code somewhere in Github, please tell me exactly where, as I only understand Github minimally. 
Thank you for considering this package.
I think you will find it to be a unique and powerful resource. 
(I have also submitted it to Python's SciPy, but the SciPy developers seem to be very busy with their own issues right now. They have promised to get to it.  The C++ version has been available for 10 years and used significantly.)

**Comment by rejones7go** [comment]
HI... since I am still not busy due to Covid, I have now expanded this package to include all the features in my C++ and Python libraries. So now the user can combine the auto-regularization solver with both equality constraints, presented as arguments E (matrix) and f (RHS values), and inequality constraints (i.e., greater than constraints), presented as arguments G (matrix) and h (RHS values). One version accepts Ex==h in addition to.
 Ax=b;  another accepts Gx>=h in addition to Ax=b, and a final one accepts all three: x = Arlsall(A,b,E,f,G,h). 
(These solvers build nicely on each other, with no duplicated functionality in the code.)
These solvers handle redundant or conflicting constraints, and ill-conditioning among constraints (which should be very rare).  
I have placed all this code and the associated test routines (for "Go test") in this portion of my web site for your review http://www.rejones7.net/ArlsGo/index.htm 
(This has not been advertised to the public and Google hasn't scanned it.)
If you want me to place this code somewhere in Github, please tell me exactly where, as I only understand Github minimally. 
Thank you for considering this package.
I think you will find it to be a unique and powerful resource. 
(I have also submitted it to Python's SciPy, but the SciPy developers seem to be very busy with their own issues right now. They have promised to get to it.  The C++ version has been available for 10 years and used significantly.)

**Comment by kortschak** [comment]
Thank you @rejones7go. Sorry it's taking a long time to get to this; contributor time has been fairly significantly impacted by work at home arrangements due to COVID.

We could move forward with this by incorporating it into the gonum/exp repository. That repo holds things that are being worked on but have not been fully integrated into Gonum proper, with a more fluid development model. If you would like to send a PR adding ARLS there maybe that would work out. In the meantime, I think it's worth keeping this issue open.

**Comment by vladimir-ch** [comment]
Hi, sorry I haven't been able to take a look yet. @kortschak is right but in addition to work at home arrangements it's the work load itself. I haven't had free time for Gonum in months and I'm not sure when it will end. I _will_ take a look but can't guarantee when.

@rejones7go , if you're new to Github and don't feel like discovering how to push your code to our https://github.com/gonum/exp, then don't worry, I'll get it from your website. Thanks for your patience.

**Comment by rejones7go** [comment]
Thank you for the response!
I have just placed the "Arls" code and test files in
github.com/gonum/exp/rejonesgo.
I hope I did it right. If not, please move things wherever they should be,
Thanks for your helpful offer to upload it for me.

I fully understand your being very busy. (Been there/ Done that! :-) )
I am happy to wait until whenever you have time to look at this,
as it is worth the wait to reach my goal of having Arls be "official".
(My Python version is also delayed for similar reasons, plus Python SCIPY
is in flux right now anyway.)

I did all this work recently because (being retired) COVID left me looking
for something to do..

Ron Jones

**Comment by kortschak** [comment]
@rejones7go Would you be able to redo the PR so that it's against gonum/exp rather than rejones7go/exp? Also, after that would you send a PR adding yourself to the AUTHORS and CONTRIBUTORS files in gonum/gonum.

**Comment by rejones7go** [comment]
Yes, I will do that.

**Comment by rejones7go** [comment]
OK, I think I did a correct pull of ARLS to gonum/exp instead of
rejones7go/exp.  Let me know.

As I mentioned my previous experience with Github was minimal, and with
Python, not Go, but I want to learn to do things right.
I am sure you could do the changes to AUTHORS and CONTRIBUTORS, but I want
to understand how to do it.
Do I fork a branch of gonum/gonum to my area, edit the files there, then do
a pull request based on the fork compare?
Or am I misunderstanding the process entirely?
Sorry to be such a pain.
Thanks for your managing all this.
Ron Jones

**Comment by kortschak** [comment]
Thanks for that. The ARLS PR at gonum/exp is there and I'll take a look when I get back to a keyboard later today.

As far as the PR for adding yourself to A+C, yes you need to make a GitHub fork of the gonum/gonum repo and make the change adding yourself and then send a PR by pushing your changed branch back to GitHub and then using the same PR UI you used to send the ARLS PR. If you have any issues I'll try to explain more clearly (if you are using git on the command line, then it should give you a success output on pushing the branch that links to a PR set-up page).

**Comment by rejones7go** [comment]
Thanks for your guidance and patience.
I believe I just correctly modified AUTHORS and CONTRIBUTORS.
Ron

**Comment by kortschak** [comment]
Thanks. If you're happy to fix up the license header in the gonum/exp PR, I'll approve and merge both of them.
