### ISSUE TITLE
graph/layout: TestEadesR2 and TestIsomapR2 fail: image mismatch / image bounds error

### ISSUE THREAD

**Issue by eclipseo** [gonum/gonum#1551]
### What did you do?

Run test with qo 1.16 beta1, in my case:

`go test -buildmode pie -compiler gc -ldflags " -X gonum.org/v1/gonum/version=0.8.2 -extldflags '-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld  '"
`

### What did you expect to happen?
No error.

### What actually happened?
```
--- FAIL: TestEadesR2 (0.64s)
    layout_test.go:81: image mismatch for testdata/line.png
    layout_test.go:95: image bounds union:(0,0)-(378,378) diff bounds intersection:(0,0)-(378,378)

etc for other images…
```
Full log: https://koji.fedoraproject.org/koji/taskinfo?taskID=60406612

```
--- FAIL: TestIsomapR2 (1.29s)
    layout_test.go:81: image mismatch for testdata/line_isomap.png
    layout_test.go:95: image bounds union:(0,0)-(378,378) diff bounds intersection:(0,0)-(378,378)

etc for other images…
```
Full log: https://koji.fedoraproject.org/koji/taskinfo?taskID=60406644

### What version of Go and Gonum are you using?

Go 1.16 beta 1
Gonum 0.8.2

### Does this issue reproduce with the current master?
Yes.

**Comment by kortschak** [comment]
Thanks for filing this issue. For context, can you explain the external ldflags you are using (I'm also curious about `-X gonum.org/v1/gonum/version=0.8.2` which doesn't match the syntax for that ldflag, though won't be causing this problem).

I had thought that the likely cause for this in Isomap is that it depends on Eigen decomposition which can be numerically unstable. This is not likely to be the case for Eades. Looking at the the graphical output though (the image diffs are base64 encoded png in test log lines prefixed with `IMAGE:`) I have doubts. The diffs all show only changes in label positions, not nodes nor edges.

Can you paste the complete go.mod that you are using and whether there are any local changes to the tree?

**Comment by eclipseo** [comment]
I've checked a new build with Go 1.15 and it's also affected. So I will be correcting the bug title.

> Thanks for filing this issue. For context, can you explain the external ldflags you are using (I'm also curious about `-X gonum.org/v1/gonum/version=0.8.2` which doesn't match the syntax for that ldflag, though won't be causing this problem).
> 
Default Fedora hardening build flags, + default versioning ldflags for Go packaging.

> I had thought that the likely cause for this in Isomap is that it depends on Eigen decomposition which can be numerically unstable. This is not likely to be the case for Eades. Looking at the the graphical output though (the image diffs are base64 encoded png in test log lines prefixed with `IMAGE:`) I have doubts. The diffs all show only changes in label positions, not nodes nor edges.
> 
> Can you paste the complete go.mod that you are using and whether there are any local changes to the tree?

We don't use Go modules yet in Fedora (it is planned at some point), the actual dependencies may not be in Sync with go.mod.

You can infer the dependency from the logs:

```
DEBUG util.py:446:    golang-gioui-devel-0-0.1.20201225git18d4dbf.fc34.noarch                       
DEBUG util.py:446:    golang-github-ajstarks-svgo-devel-0-0.11.20210108git7a3c8b5.fc34.noarch       
DEBUG util.py:446:    golang-github-boombuler-barcode-devel-1.0.0-7.fc33.noarch                     
DEBUG util.py:446:    golang-github-burntsushi-toml-devel-0.3.1-8.fc33.noarch                       
DEBUG util.py:446:    golang-github-burntsushi-xgb-devel-0-0.11.20210108git5f9e7b3.fc34.noarch      
DEBUG util.py:446:    golang-github-fogleman-gg-devel-1.3.0-7.20200726gitad4d1ea.fc33.noarch        
DEBUG util.py:446:    golang-github-freetype-devel-0-0.12.20190701gite2365df.fc33.noarch            
DEBUG util.py:446:    golang-github-google-cmp-devel-0.5.4-1.fc34.noarch                            
DEBUG util.py:446:    golang-github-kisielk-gotool-devel-1.0.0-8.fc33.noarch                        
DEBUG util.py:446:    golang-github-latex-devel-0-0.1.20201224git94de131.fc34.noarch                
DEBUG util.py:446:    golang-github-phpdave11-gofpdf-devel-1.4.2-1.fc34.noarch                      
DEBUG util.py:446:    golang-github-phpdave11-gofpdi-devel-1.0.13-1.fc34.noarch                     
DEBUG util.py:446:    golang-github-pkg-errors-devel-0.9.1-2.fc33.noarch                            
DEBUG util.py:446:    golang-github-ruudk-pdf417-devel-0-0.1.20201224git1af4ab5.fc34.noarch         
DEBUG util.py:446:    golang-github-sanity-io-litter-devel-1.3.0-1.fc33.noarch                      
DEBUG util.py:446:    golang-github-sergi-diff-devel-1.1.0-3.fc34.noarch                            
DEBUG util.py:446:    golang-github-yuin-goldmark-devel-1.3.1-1.fc34.noarch                         
DEBUG util.py:446:    golang-gonum-1-plot-devel-0.8.1-1.20201222gitf888cdb.fc34.noarch              
DEBUG util.py:446:    golang-honnef-tools-devel-2020.2.1-1.fc34.noarch                              
DEBUG util.py:446:    golang-mvdan-gofumpt-devel-0.1.0-1.fc34.noarch                                
DEBUG util.py:446:    golang-mvdan-xurls-devel-2.2.0-2.fc33.noarch                                  
DEBUG util.py:446:    golang-src-1.16-0.beta1.1.fc34.noarch                                         
DEBUG util.py:446:    golang-x-crypto-devel-0-0.38.20210123giteec23a3.fc34.noarch                   
DEBUG util.py:446:    golang-x-exp-devel-0-0.26.20210123giteab1b5e.fc34.noarch                      
DEBUG util.py:446:    golang-x-image-devel-0-0.22.20201223git35266b9.fc34.noarch                    
DEBUG util.py:446:    golang-x-mobile-devel-0-0.7.20210123gite6ae53a.fc34.noarch                    
DEBUG util.py:446:    golang-x-mod-devel-0.4.0-1.fc34.noarch                                        
DEBUG util.py:446:    golang-x-net-devel-0-0.60.20210123git5f4716e.fc34.noarch                      
DEBUG util.py:446:    golang-x-net-http-devel-0-0.60.20210123git5f4716e.fc34.noarch                 
DEBUG util.py:446:    golang-x-sync-devel-0-0.13.20210123git09787c9.fc34.noarch                     
DEBUG util.py:446:    golang-x-sys-devel-0-0.38.20210123git9b0068b.fc34.noarch                      
DEBUG util.py:446:    golang-x-term-devel-0-0.1.20210107git2321bbc.fc34.noarch                      
DEBUG util.py:446:    golang-x-text-devel-0.3.5-1.fc34.noarch                                       
DEBUG util.py:446:    golang-x-tools-devel-0-37.20210123git2972602.fc34.noarch                      
DEBUG util.py:446:    golang-x-xerrors-devel-0-0.6.20200807git5ec99f8.fc33.noarch     
```

According to our dependency tracker, the only change which triggered the bug is going from  golang-github-yuin-goldmark-devel  1.3.0 to 1.3.1 (https://koschei.fedoraproject.org/build/9576330). Can it explain the issue?

**Comment by kortschak** [comment]
It's not at all clear to me why that would impact on this since I don't see it in our deps for this particular test.

Not using modules makes this very much harder to resolve, but as a workaround you can regenerate the test cases that are failing and commit those to your tree. This is done by running those failing tests with an additional `-regen` flag. This will need to be done for all the architectures that you are targeting that fail.

**Comment by eclipseo** [comment]
I've checked and it's not due to golang-github-yuin-goldmark-devel. Not sure why this is happening. Iwill try the regen thing.

**Comment by kortschak** [comment]
We changed font handling in gonum/plot recently, but I looked at the dates for when that happened and it was after the date you have on golang-gonum-1-plot-devel-0.8.1-1.20201222gitf888cdb.fc34.noarch. Maybe check that first though.

**Comment by eclipseo** [comment]
The issue is indeed with gonum/plot. Version 0.8.1 works. I think I packaged a git tip to get rid of rsc/pdf.

**Comment by kortschak** [comment]
Glad we could sort it out.
