### ISSUE TITLE
spatial/{r2,r3}: add rotation matrix converters to/from mat.Matrix

### ISSUE THREAD

**Issue by sbinet** [gonum/gonum#1552]
as alluded to in https://github.com/gonum/gonum/pull/1516, we should (probably) provide `r3.Rotation` matrices converters to/from their `mat.Matrix` equivalent. (or to/from `mat.Dense` ?)

proposed API:
```go
package r3

func NewRotationFrom(m mat.Matrix) Rotation { ... }

func (r Rotation) ToMatrix(m mat.Matrix) { ... }
```

or just use `[]float64` everywhere ?
(that would have the advantage of not coupling `r3,r2` to `mat`, at the cost of introducing possible row/col-major mistakes)

**Comment by kortschak** [comment]
I'm still ambivalent about this for the reasons that I wrote [previously](https://github.com/gonum/gonum/pull/1516#discussion_r532911007).

**Comment by sbinet** [comment]
I am fine w/ not providing conversions to/from Euler angles.

I am just talking about rotation matrices here.
ie: https://en.wikipedia.org/wiki/Rotation_matrix#Quaternion

**Comment by kortschak** [comment]
Where is it expected to be used? Given that it's a 3×3 maybe `[3][3]float64`? Alternatively make a type here that satisfies `mat.Matrix` built around a `[9]float64` that can then also satisfy `mat.RawMatrixer`. Having a defined type means that the conversion would be `m := r.Matrix()` and `r := m.Rotation()`.

**Comment by sbinet** [comment]
in some code I am working on:
- https://github.com/sbinet-staging/go-topquark-reco/blob/33455d75bd8318cd360d97495c100d670cdbedb1/tbuilder/neutrino_ellipse_calc.go#L210
- https://github.com/sbinet-staging/go-topquark-reco/blob/33455d75bd8318cd360d97495c100d670cdbedb1/tbuilder/neutrino_ellipse_calc.go#L163
- https://github.com/sbinet-staging/go-topquark-reco/blob/33455d75bd8318cd360d97495c100d670cdbedb1/tbuilder/neutrino_ellipse_calc.go#L244
(don't mind the C++-isms, I am still in the process of transliterating that code from C++ into _"proper"_ Go)

it'd be great to indeed be able to mesh `r3.Rotation` and `r3.Vec` together with other `mat.Xyz` operations and types.

**Comment by kortschak** [comment]
It seems to me that you you'd do better using quaternions for these rotations; they'll be simpler and quicker. Then for the subsequent parts that involve the matrix arithmetic, either wrap an `r3.Vec` so that it satisfies `mat.Vector`, or probably better (for speed), make a 3×3 mul that doesn't use loops.

**Comment by sbinet** [comment]
would providing a PR that make `r3.Vec` implement `mat.Vector` be ok? (that would make `spatial/r3` import `mat`, obviously)

**Comment by kortschak** [comment]
There are a number of ways to implement that and leaving that up to the user allows that better. I'm inclined to not want it.

**Comment by sbinet** [comment]
ok.
