### ISSUE TITLE
stat:ROC has a wrong result when  the span in y is not consistent with that in cutoffs

### ISSUE THREAD

**Issue by zhongsigang** [gonum/gonum#1559]
### What are you trying to do?

package main

import (
	"fmt"
	"gonum.org/v1/gonum/stat"
	"math"
)

func main() {

	y := []float64{0.1, 0.35, 0.4, 0.8}
	c := []bool{true, false, true, false}
	cutoffs := []float64{math.Inf(-1), 0.1, 0.36, 0.8}

	tpr, fpr, thresh := stat.ROC(cutoffs, y, c, nil)
	fmt.Printf("true  positive rate: %v\n", tpr)
	fmt.Printf("false positive rate: %v\n", fpr)
	fmt.Printf("thresh: %v\n", thresh)
}

### What did you expect to happen?
true  positive rate: [0 0 0.5 1]
false positive rate: [0 0.5 0.5 1]
thresh: [+Inf 0.8 0.36 0.1]

### What actually happened?
true  positive rate: [0 0.5 0.5 1]
false positive rate: [0 0.5 1 1]
thresh: [+Inf 0.8 0.36 0.1]

### What version of Go and Gonum are you using?

go version
go version go1.15.6 windows/amd64

rg gonum.org/v1/gonum go.sum
18:gonum.org/v1/gonum v0.0.0-20180816165407-929014505bf4/go.mod h1:Y+Yx5eoAFn32cQvJDxZx5Dpnq+c3wtXuadVZAcxbbBo=

### Does this issue reproduce with the current master?
require gonum.org/v1/gonum v0.8.2

**Comment by zhongsigang** [comment]
I suggest that we do not use the inverse of cutoffs, but use the meaning of **<=** directly.

**Comment by zhongsigang** [comment]
Or cancel the parameter cutoff, that is, it always equals nil.

**Comment by kortschak** [comment]
Please explain with more detail why you think this is wrong and why your suggestion is appropriate; this bug is very terse.

**Comment by Armadilloa16** [comment]
I can confirm I've reproduced this bug, and that it is a bug --- output is incorrect. 

I had a look through the src and I'm not sure what's causing it. The codes been re-written a few times as well, I'd suggest it could be re-written to be more readable which might make debugging easier. I can have a go at this if that's desirable.

**Comment by Armadilloa16** [comment]
But basically what I'm saying is I agree --- we should not use the inverse of cutoffs, and should calculate the output directly rather than transforming afterwards.

**Comment by kortschak** [comment]
If you have time to do that, that would be good. Also note #1558.

**Comment by zhongsigang** [comment]
According to the src of ROC, the reverse of `a<b<c<d`  is` a>d>c>b`, the first part replaced by +inf. The value P of count(y<=c) is corresponding to len(y)-P of count(y>c). In some case, count(y>c) is equals to count(y>=d), but not always. Notice that len(y)-P goes from penultimate to second.

**Comment by kortschak** [comment]
Closed by #1561.
