### ISSUE TITLE
stat: ROC revise desired behaviour when cutoffs is not nil

### ISSUE THREAD

**Issue by Armadilloa16** [gonum/gonum#1560]
Looking over the code for ROC, I notice it's diverged a little from original intended functionality, particularly when cutoffs is not nil. Specifically, it says in the documentation that fpr and tpr will be returned with the same length as cutoffs, this is the case, but the intention was (I believe) that in this case (when cutoffs is not nil), that the returned thresh should be exactly equal to cutoffs (or a reversed version). If this is correct, I can submit a PR bringing the tests back in line with this, but if it is not (I believe some changes were made to bring behaviour more in line with sklearn at some point?) then could someone clarify for me the intended behaviour in this case?

I'd also like to improve the readability of the code for ROC, and I'll include those changes (which shouldn't affect functionality, but might resolve #1557 and/or #1558), but I wanted to be clear on what the intended behaviour was before I made any changes.

**Comment by Armadilloa16** [comment]
@kortschak

**Comment by Armadilloa16** [comment]
For example, in roc_test.go, should test 2 not instead be: 

			y:          []float64{0, 3, 5, 6, 7.5, 8},
			c:          []bool{false, true, false, true, true, true},
			cutoffs:    []float64{-1, 2, 4, 6, 8},
			wantTPR:    []float64{0.25, 0.75, 0.75, 1,    1},
			wantFPR:    []float64{0,    0,    0.5,  0.5,  1},
			wantThresh: []float64{8,    6,    4,    2,   -1},

**Comment by kortschak** [comment]
That was changed in #959. I defer to your opinion.

**Comment by kortschak** [comment]
The decision was made in #316.

**Comment by Armadilloa16** [comment]
Yep I'm ok with the decision made in #316, I'll keep that change, but I'm just not sure about the final approach we ended up taking to close #708... I realise that's partly my fault for not being very available. I'll work up a suggestion for how to change this and then we can review if it works for everyone or not.

**Comment by kortschak** [comment]
SGTM

**Comment by Armadilloa16** [comment]
Done, see #1561. :)
