### ISSUE TITLE
mat: VecDense equivalent for f32 (or non-internal asm/f32 access)

### ISSUE THREAD

**Issue by y0ast** [gonum/gonum#1583]
### What are you trying to do?
I would like to perform some vector operations in float32.

### What did you try?
Directly use `blas32.Vector`.

### How does Gonum not allow you to achieve your goal?
Some operations (such as `SubVec`) are not implemented for `blas32.Vector`. This is solved for `mat.VecDense` by using hand-coded assembly in `internal/asm/f64`.

I attempted to port SubVec to float32, which is fairly straightforward by changing `f64.AxpyUnitaryTo` -> `f32.AxpyUnitaryTo` (and a few very similar steps).

However `f32` is an internal module which I am not allowed to import. This was previously discussed in #559, where the issue creator was pointed to `mat`. However `mat` is strictly float64 which does not help me.

### What version of Go and Gonum are you using?
1.16.2, 0.9.0

### Is this feature absent from the current master?
Yes

### Are you able to help contribute the feature?
Sure, I would be happy to do `VecDense32`, but it would add a lot of code (and for consistency probably needs to be done for all in `mat`, which I am not sure is practical).

Alternatively, `f32` could be made *non-internal*. There is hardly any gonum usage of it (the only place where it's currently used is: https://github.com/gonum/gonum/blob/master/blas/gonum/gemv.go#L9 ) so this would actually enable a sensible interface to it.

**Comment by chewxy** [comment]
You can use `tensor.Dense` , which supports a majority of functions for `float32`

**Comment by y0ast** [comment]
@chewxy Thanks, I'll try that out :)

I previously tried https://github.com/gorgonia/vecf32 but found it significantly slower than the float64 ops in `gonum`. Perhaps it's outdated compared to `gorgonia/tensor`?

I'm happy to close this issue if `float32` isn't on the books for gonum.

**Comment by kortschak** [comment]
Adding `float32` to mat is non-trivial, so its addition is not likely to happen soon.
