### ISSUE TITLE
interp: PiecewiseLinear now wrongly panics when given 2 values for xs/ys

### ISSUE THREAD

**Issue by petecorreia** [gonum/gonum#1585]
### What are you trying to do?

Simply using the PiecewiseLinear interpolation with slices of length 2 causes a panic.

```go
xs := []float64{10, 20}
ys := []float64{50, 100}

pl := interp.PiecewiseLinear{}

pl.Fit(xs, ys)

prediction := pl.Predict(15)

fmt.Println(prediction)
```

### What did you expect to happen?

I expected no panics and the prediction to result in 75.

### What actually happened?

Results in a panic in `calculateSlopes`:  `panic: interp: too few points for interpolation`.

This is due to the addition of `calculateSlopes` to the `Fit` method in `v0.9.0` which has a check for slice length that is **less than or equal** instead of **less than**.

https://github.com/gonum/gonum/commit/c4c4cbff9cc750e157ae773e934a2981da2533ce#diff-823b529e07487add8285aa46d3e37d7c7ffea005c59fd148f550c8c455212196R463-R465

The `Fit` method already has a check for length of the float64 slices: https://github.com/gonum/gonum/blob/master/interp/interp.go#L81

### What version of Go and Gonum are you using?

```bash
$ go version
go version go1.16 darwin/amd64

$ grep gonum.org/v1/gonum go.sum
gonum.org/v1/gonum v0.0.0-20180816165407-929014505bf4/go.mod h1:Y+Yx5eoAFn32cQvJDxZx5Dpnq+c3wtXuadVZAcxbbBo=
gonum.org/v1/gonum v0.8.1-0.20200930085651-eea0b5cb5cc9/go.mod h1:oe/vMfY3deqTw+1EZJhuvEW2iwGF1bW9wwu7XCu0+v0=
gonum.org/v1/gonum v0.8.2 h1:CCXrcPKiGGotvnN6jfUsKk4rRqm7q09/YbKb5xCEvtM=
gonum.org/v1/gonum v0.8.2/go.mod h1:oe/vMfY3deqTw+1EZJhuvEW2iwGF1bW9wwu7XCu0+v0=
gonum.org/v1/gonum v0.9.0 h1:KSrriwTGNTqNqyR6ZWWvwtInD/kl89sTrKsDfmbk2HU=
gonum.org/v1/gonum v0.9.0/go.mod h1:TZumC3NeyVQskjXqmyWt4S3bINhy7B4eYwW69EbyX+0=
```

### Does this issue reproduce with the current master?

Yes in the recent `v0.9.0` release.

**Comment by romanwerpachowski** [comment]
Indeed, it's a bug.
