### ISSUE TITLE
floats: Add ArgsortStable function

### ISSUE THREAD

**Issue by virtuald** [gonum/gonum#1598]
### What are you trying to do?

I'm working on porting some MATLAB/NumPy code to golang. The existing code appears to depend on a stable sort output from argsort/sort, and `floats.Argsort` uses sort.Sort which is not stable.

### Is this feature absent from the current master?

Yes

### Are you able to help contribute the feature?

If you're open to it, sure.

**Comment by kortschak** [comment]
This seems reasonable, but can you link to the relevant NumPy and MATLAB documentation.

**Comment by virtuald** [comment]
NumPy's argsort documentation, they added 'stable' in 1.15.0: https://numpy.org/doc/stable/reference/generated/numpy.argsort.html

> kind{‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}, optional
Sorting algorithm. The default is ‘quicksort’. Note that both ‘stable’ and ‘mergesort’ use timsort under the covers and, in general, the actual implementation will vary with data type. The ‘mergesort’ option is retained for backwards compatibility.

According to [MATLAB's sort documentation](https://www.mathworks.com/help/matlab/ref/sort.html), one of the output arguments can be a sort index similar to Argsort. (caveat: not a MATLAB person). The sort documentation itself doesn't specifically seem to say that it is a stable sort, but in `sort.m` this appears:

```
%   The sort ordering is stable. Namely, when more than one element has the
%   same value, the order of the equal elements is preserved in the sorted
%   output B and the indices I relating to equal elements are ascending.
```

**Comment by kortschak** [comment]
No worries. Thanks. The implementation is trivial (just copy paste from the `Argsort` implementation). Here is a test that exercises the stability. https://play.golang.org/p/Az1kyLX3-OQ. If you want to send a PR, please go ahead.
