### ISSUE TITLE
graph/graphs/gen: reconsider signatures for deterministic graph generation routines

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#1614]
The routines that were added in #1590 all return errors. It is possible to know ahead of time whether their will be multiple instances of the same node in the iterators or whether central nodes are also present in leaves or cycles. For this reason, and to be consistent with other areas of the suite, I think the error return should be elevated to panics.

/cc @vladimir-ch @mattConn

**Comment by mattConn** [comment]
That sounds fair. This behavior looks to be consistent like you said with the other graph functions, or at least the ones I looked over in `simple` that pertained to adding components to a graph.

It would also mean that when a graph-making function panics, something really went wrong, despite preflight checks.

**Comment by kortschak** [comment]
> It would also mean that when a graph-making function panics, something really went wrong, despite preflight checks.

Yes. That's the intention. There's an argument that could be made for the random graph generators in this direction too, but it seems less firm (for no really clear reason — which troubles me).
