### ISSUE TITLE
mat: unused BandWidther interface

### ISSUE THREAD

**Issue by vladimir-ch** [gonum/gonum#1626]
The `mat.BandWidther` interface is unused and no matrix type in `mat` fulfills it:
```
type BandWidther interface {
	BandWidth() (k1, k2 int)
}
```
Since there is the `Banded` interface:
```
type Banded interface {
	Matrix
	Bandwidth() (kl, ku int)
	TBand() Banded
}
```
I think that `BandWidther` should be removed.

**Comment by kortschak** [comment]
SGTM
