### ISSUE TITLE
mat: Export Cond() methods for factorized types, and possibly rectify Cond() function implementation

### ISSUE THREAD

**Issue by btracey** [gonum/gonum#165]
`SVD` has a Cond method for returning the condition number. `LU`, `LQ`, and `QR` should also have the same.

There is also a lot of repeated code between the `mat.Cond` function and the factorized types. The reason for this repeat is allowing the norm of the condition number to adjust. I think we can have an unexported `factorize` function that inputs both the matrix and the condition norm. Then we can delete most of the code in `Cond`, and instead have

```
if m == n {
    var lu LU
    lu.factorize(m, lnorm)
    return lu.Cond()
}
```

and similar substitutions for the other cases.

**Comment by kortschak** [comment]
SGTM
