### ISSUE TITLE
all: generalise vector functions

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#167]
Candidate functions and methods at this stage are (only exported functions are listed):

- [x] `stat/statmat.go:func Mahalanobis(x, y *mat.VecDense, chol *mat.Cholesky) float64`
- [x] `mat/cholesky.go:func (c *Cholesky) SolveVec(v, b *VecDense) error`
- [x] `mat/cholesky.go:func (c *Cholesky) SymRankOne(orig *Cholesky, alpha float64, x *VecDense)`ok bool) {
- [x] `mat/symmetric.go:func (s *SymDense) SymRankOne(a Symmetric, alpha float64, x *VecDense)`
- [x] `mat/symmetric.go:func (s *SymDense) RankTwo(a Symmetric, alpha float64, x, y *VecDense)`
- [x] `mat/inner.go:func Inner(x *VecDense, A Matrix, y *VecDense) float64`
- [x] `mat/solve.go:func (v *VecDense) SolveVec(a Matrix, b *VecDense) error`
- [x] `mat/matrix.go:func Dot(a, b *VecDense) float64`
- [x] `mat/vector.go:func (v *VecDense) SliceVec(i, k int) *VecDense`
- [x] `mat/vector.go:func (v *VecDense) CloneVec(a *VecDense)`
- [x] `mat/vector.go:func (v *VecDense) CopyVec(a *VecDense) int`
- [x] `mat/vector.go:func (v *VecDense) ScaleVec(alpha float64, a *VecDense)`
- [x] `mat/vector.go:func (v *VecDense) AddScaledVec(a *VecDense, alpha float64, b *VecDense)`
- [x] `mat/vector.go:func (v *VecDense) AddVec(a, b *VecDense)`
- [x] `mat/vector.go:func (v *VecDense) SubVec(a, b *VecDense)`
- [x] `mat/vector.go:func (v *VecDense) MulElemVec(a, b *VecDense)`
- [x] `mat/vector.go:func (v *VecDense) DivElemVec(a, b *VecDense)`
- [x] `mat/vector.go:func (v *VecDense) MulVec(a Matrix, b *VecDense)`
- [x] `mat/qr.go:func (qr *QR) SolveVec(v *VecDense, trans bool, b *VecDense) error`
- [x] `mat/dense_arithmetic.go:func (m *Dense) RankOne(a Matrix, alpha float64, x, y *VecDense)`
- [x] `mat/dense_arithmetic.go:func (m *Dense) Outer(alpha float64, x, y *VecDense)`
- [x] `mat/dense.go:func (m *Dense) ColView(j int) *VecDense`
- [x] `mat/dense.go:func (m *Dense) RowView(i int) *VecDense`
- [x] `mat/lq.go:func (lq *LQ) SolveVec(v *VecDense, trans bool, b *VecDense) error`
- [x] `mat/lu.go:func (lu *LU) RankOne(orig *LU, alpha float64, x, y *VecDense)`
- [x] `mat/lu.go:func (lu *LU) SolveVec(v *VecDense, trans bool, b *VecDense) error`

Not all are necessarily worth doing or useful (e.g. `ColView`, `RowView`).

**Comment by kortschak** [comment]
Note that with this change, the vector solves can be simplified to lose the `trans` parameter.

**Comment by james-bowman** [comment]
Generalising `ColView` and `RowView` to use the `Vector` interface rather than `VecDense` would be really useful.  It would allow other matrix types e.g. Sparse matrices to have a standardised way of slicing col/row vectors.  At the moment, to be consistent with the existing API, other matrix types would need to implement ColView/RowView and return VecDense types rather than being able to return other types of Vector to match the sliced matrix potentially allowing sharing of underlying storage too.

**Comment by kortschak** [comment]
PRs are welcome.

**Comment by james-bowman** [comment]
Cool, I have updated `ColView` and `RowView` methods to return `Vector` types and updated the `Dot` function to accept `Vector` types. PR #199

**Comment by kortschak** [comment]
Accidental assignment.
