### ISSUE TITLE
Kronecker product

### ISSUE THREAD

**Issue by gcwenes** [gonum/gonum#1690]
### Background
1/ The Kronecker product of two arbitrarily-sized matrices A(n,m) , B(p,q) is a block matrix  of size (np, mq) that is useful in solving for the matrix X in matrix equations such as AXB = C. 2/ In addition, in random matrix theory, it is becoming increasingly important to learn from a partially-observed random matrix and predict its missing elements. The study of such matrix-variate distributions leverages the Kronecker product (and the helper "vec" vectorization function) to move back and forth between matrix-variate and multi-variate distribution and by doing so greatly simplifies matrix variate statistics. 

### Proposal
A native implementation of the Kronecker product and helper function vec in mat64. (And possibly extensions to the multivariate package mvt.)

### Potential impact of proposal
Considerably reduced effort for the  statistician and algebraist to write, test, and publish robust Golang applications.

**Comment by kortschak** [comment]
I was actually thinking about this a month ago when I wrote an [answer in slack](https://gophers.slack.com/archives/C0UKS8V9S/p1622241474021600). The implementation is trivial and I'm happy to take this on, possibly over the weekend.

**Comment by kortschak** [comment]
Well that's embarrassing; I just wrote one and then saw that a Kronecker was already declared. Time travelling me has already written [this](https://pkg.go.dev/gonum.org/v1/gonum/mat#Dense.Kronecker) (two years ago). Reassuringly, I wrote it the same way both times, though there is an optimisation that I included this time that may be worth considering.

```diff
index d0c66509..c7a0597a 100644
--- a/mat/dense_arithmetic.go
+++ b/mat/dense_arithmetic.go
@@ -686,6 +686,12 @@ func (m *Dense) Kronecker(a, b Matrix) {
        ra, ca := a.Dims()
        rb, cb := b.Dims()
 
+       // Minimise the number of Scale calls.
+       if rb*cb < ra*ca {
+               a, b = b, a
+               ra, rb = rb, ra
+               ca, cb = cb, ca
+       }
        m.reuseAsNonZeroed(ra*rb, ca*cb)
        for i := 0; i < ra; i++ {
                for j := 0; j < ca; j++ {
```

**Comment by kortschak** [comment]
@gcwenes Are you happy to close this?

**Comment by gcwenes** [comment]
yes - closed

Geert C. Wenes
+1 (206) 383-1891
