### ISSUE TITLE
mat: add informative panics for factorising types that do not hold a factorisation

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#171]
`SVD` states that it will panic if it does not hold a successful factorisation. `LU`, `LQ` and `QR` will also, but this will happen due to a nil pointer dereference or other cause. We should make a check and explicitly panic, with documentation.

**Comment by btracey** [comment]
This was updated with #872 . I haven't checked if that `LU`, `LQ` and `QR` are consistent.
