### ISSUE TITLE
mat: SliceSquare not as useful as it could be

### ISSUE THREAD

**Issue by btracey** [gonum/gonum#174]
The current signature is `func (s *SymDense) SliceSquare(i, k int) Matrix`. The difficulty with this function is that it doesn't return a Symmetric matrix, so it's less useful. I'm not sure if we should add `SliceSquareSym`, or just rename.

**Comment by kortschak** [comment]
Can we not make these `func (s *SymDense) SliceSquare(i, k int) Symmetric` (and `func (s *TriDense) SliceSquare(i, k int) Triangular` when it is added).

**Comment by btracey** [comment]
We can, though we generally avoid having the same method names with different signatures.

**Comment by kortschak** [comment]
Yeah. Normally that's because we want to be able to ensure interfaces can be satisfied, but here we would absolutely not want a `Triangular` to be able to satisfy `Symmetric` and vice versa.

**Comment by btracey** [comment]
I don't know how much need there is, but one advantage of the special names is cases for `Banded`, which could be useful. It seems plausible the general case could be useful (schur complement?). I'm not sure if I'm over thinking / over engineering
