### ISSUE TITLE
Add Logistic distribution

### ISSUE THREAD

**Issue by gudvinr** [gonum/gonum#1744]
### What are you trying to do?

I am trying to use [Logistic](https://en.wikipedia.org/wiki/Logistic_distribution) CDF.

### How does Gonum not allow you to achieve your goal?

Gonum does have a number of distributions but Logistic distribution is not one of them.  
It is used in logistic regression and also particularly useful for rating calculations (e.g. Elo rating).

### What version of Go and Gonum are you using?

go version go1.17.2 linux/amd64
gonum v0.9.3

### Is this feature absent from the current master?
Yes

### Are you able to help contribute the feature?

I suppose I can write an implementation but I am not familiar with gonum internals to do so efficiently.

**Comment by romanwerpachowski** [comment]
Hi Maxim, thanks for your interest in Gonum. If you submit a PR with the initial implementation, I can help you to get it merged.

**Comment by gudvinr** [comment]
What are hard and soft requirements for implementation? I suppose it should be in `distuv` but is there something other than that?

**Comment by gudvinr** [comment]
@romanwerpachowski can you take a look at #1745?

**Comment by kortschak** [comment]
Closed by #1745.
