### ISSUE TITLE
tests fail on ppc64el with amos_test.go:354: Case zseri yi_idx_5: Float64 mismatch. c = 2.845067377894076e+68, native = 2.8761262203281526e+68 cb: 5630936712465022803, nb: 5631001566354080705

### ISSUE THREAD

**Issue by pravi** [gonum/gonum#1751]
### What are you trying to do?

Run tests on ppc64el machine (same tests pass on amd64 and arm)

### What did you do?

Run testsuite normally (the same commands pass on other archs)

### What did you expect to happen?

Tests should pass on ppc64el as well

### What actually happened?
```
    amos_test.go:354: Case zseri yi_idx_5: Float64 mismatch. c = 2.845067377894076e+68, native = 2.8761262203281526e+68
         cb: 5630936712465022803, nb: 5631001566354080705
--- FAIL: TestZseri (19.62s)
```

Full log https://ci.debian.net/data/autopkgtest/testing/ppc64el/g/golang-gonum-v1-gonum/14820455/log.gz

### What version of Go and Gonum are you using?

gonum 0.9.0 and golang go 1.15.15

### Does this issue reproduce with the current master?

not tested with master

**Comment by kortschak** [comment]
Unfortunately this is not a supported architecture and amos is a particularly finicky package. I'm not sure that we will be able to help with this.

**Comment by gibmat** [comment]
Still an issue with gonum 0.13.0 and golang go 1.20.5. Additionally, another test is now failing (shown below). Any further thoughts on fixes? I'd like to be able to run the tests on the ppc64el builders when the package is updated in Debian.

```
[snip a ton of reported failures]
    amos_test.go:354: Case zseri yi_idx_3: Float64 mismatch. c = 1.7225404522972317e+69, native = 1.7210280917217914e+69
         cb: 5642995214568237156, nb: 5642987319677661040
    amos_test.go:354: Case zseri yi_idx_4: Float64 mismatch. c = -8.848345645672536e+68, native = -8.796985853913224e+68
         cb: 14861994222645354487, nb: 14861967411583063086
    amos_test.go:354: Case zseri yi_idx_5: Float64 mismatch. c = 2.845067377894076e+68, native = 2.8761262203281526e+68
         cb: 5630936712465022803, nb: 5631001566354080705
--- FAIL: TestZseri (9.46s)
```

and

```
    unconstrained_test.go:1221: Case 61: error finding minimum (linesearch: failed to converge) for:
        F: ExtendedRosenbrock
        Dim: 2
        Initial X: [100000 100000]
        GradientThreshold: 1e-10
--- FAIL: TestBFGS (0.38s)
```

**Comment by kortschak** [comment]
Still not a supported architecture.
