### ISSUE TITLE
spatial/r3: Adding a `r3.Mat` type

### ISSUE THREAD

**Issue by soypat** [gonum/gonum#1754]
I work with rotation tensors and vectors of dimension 3. I found myself writing a package for matrix and r3.Vec interoperability.

### Background
I work with rotation tensors and vectors of dimension 3. I found myself writing a package for matrix and r3.Vec interoperability.
These tensors are used for attitude representation of a launch vehicle and are the industry standard way of representing this concept. One can use euler angles or quaternions to construct/decompose these matrices. See _Modeling and simulation of aerospace vehicle dynamics_ by P. Zipfel.

### Proposal
I propose the following addition to `spatial/r3`

<details>

```go
import (
	"fmt"
	"math"

	"gonum.org/v1/gonum/mat"
	"gonum.org/v1/gonum/spatial/r3"
)

const (
	badDim = "bad matrix dimensions"
	badIdx = "bad matrix index"
)

type Mat3 [3 * 3]float64

func NewMat3(val []float64) *Mat3 {
	if len(val) != 9 {
		if val == nil {
			return &Mat3{}
		}
		panic(badDim)
	}
	M := Mat3{}
	copy(M[:], val)
	return &M
}

// IdentityMat3 returns the Identity 3x3 matrix
func IdentityMat3() *Mat3 { return &Mat3{1, 0, 0, 0, 1, 0, 0, 0, 1} }

func (m Mat3) String() string {
	for i := range m {
		if math.Abs(m[i]) < 1e-6 {
			m[i] = 0
		}
	}
	return fmt.Sprintf("[%0.6g\t%0.6g\t%0.6g]\n[%0.6g\t%0.6g\t%0.6g]\n[%0.6g\t%0.6g\t%0.6g]",
		m[0], m[1], m[2], m[3], m[4], m[5], m[6], m[7], m[8])
}

func (m Mat3) CloneDense() *mat.Dense {
	M := mat.NewDense(3, 3, m[:])
	return M
	// for i := 0; i < 3; i++ {
	// 	for j := 0; j < 3; j++ {
	// 		M.Set(i, j, m.at(i, j))
	// 	}
	// }
	// return M
}

// CopyToMat3 copies elements from src Matrix to
// dst Mat3.
func CopyToMat3(dst *Mat3, src mat.Matrix) {
	r, c := src.Dims()
	if r != 3 || c != 3 {
		panic(badDim)
	}
	for i := 0; i < 3; i++ {
		for j := 0; j < 3; j++ {
			dst.set(i, j, src.At(i, j))
		}
	}
}

func (m *Mat3) Dims() (r, c int) { return 3, 3 }

func (m *Mat3) At(i, j int) float64 {
	if uint(i) > 2 || uint(j) > 2 {
		panic(badIdx)
	}
	return m.at(i, j)
}

func (m *Mat3) at(i, j int) float64 {
	return m[i*3+j]
}

func (m *Mat3) T() mat.Matrix { return mat.Transpose{Matrix: m} }
func (m *Mat3) Set(i, j int, v float64) {
	if uint(i) > 2 || uint(j) > 2 {
		panic(badIdx)
	}
	m.set(i, j, v)
}

// set sets element at position i,j without bounds checking
func (m *Mat3) set(i, j int, v float64) {
	m[i*3+j] = v
}

// Scale multiplies the elements of a by f, placing the result in the receiver.
//
// See the Scaler interface for more information.
func (m *Mat3) Scale(f float64, a mat.Matrix) {
	r, c := a.Dims()
	if r != 3 || c != 3 {
		panic(badDim)
	}
	for i := 0; i < 3; i++ {
		for j := 0; j < 3; j++ {
			m.set(i, j, f*a.At(i, j))
		}
	}
}

// Performs matrix multiplication on v:
//  result = M * v
func (m *Mat3) MulVec(v r3.Vec) (result r3.Vec) {
	result.X = v.X*m[0] + v.Y*m[1] + v.Z*m[2]
	result.Y = v.X*m[3] + v.Y*m[4] + v.Z*m[5]
	result.Z = v.X*m[6] + v.Y*m[7] + v.Z*m[8]
	return result
}

// Performs transposed matrix multiplication on v:
//  result = Mᵀ * v
func (m *Mat3) MulVecTrans(v r3.Vec) (result r3.Vec) {
	result.X = v.X*m[0] + v.Y*m[3] + v.Z*m[6]
	result.Y = v.X*m[1] + v.Y*m[4] + v.Z*m[7]
	result.Z = v.X*m[2] + v.Y*m[5] + v.Z*m[8]
	return result
}

// Skew returns the skew symmetric matrix (right hand system) of v.
//                  [0  -z  y]
//  Skew({x,y,z}) = [z   0 -x]
//                  [-y  x  0]
func Skew(v r3.Vec) (M *Mat3) {
	return &Mat3{
		0, -v.Z, v.Y,
		v.Z, 0, -v.X,
		-v.Y, v.X, 0,
	}
}

// Mul takes the matrix product of a and b, placing the result in the receiver.
// If the number of columns in a does not equal 3, Mul will panic.
func (m *Mat3) Mul(a, b mat.Matrix) {
	// TODO: add optimized operations for Mat3*Mat3
	// A, oka := a.(*Mat3)
	// B, okb := b.(*Mat3)
	// if oka && okb {
	// 	m.mul(A, B)
	// 	return
	// }
	mat.NewDense(3, 3, m[:]).Mul(a, b)
}

// Subtracts b from a and stores result in receiver. Sub will panic if the two matrices do not have the same shape.
func (m *Mat3) Sub(a, b mat.Matrix) {
	mat.NewDense(3, 3, m[:]).Sub(a, b)
}

// Add adds a and b element-wise, placing the result in the receiver. Add will panic if the two matrices do not have the same shape.
func (m *Mat3) Add(a, b mat.Matrix) {
	mat.NewDense(3, 3, m[:]).Add(a, b)
}

func (m *Mat3) VecRow(i int) r3.Vec {
	if uint(i) > 2 {
		panic(badIdx)
	}
	return r3.Vec{X: m.at(i, 0), Y: m.at(i, 1), Z: m.at(i, 2)}
}

func (m *Mat3) VecCol(j int) r3.Vec {
	if uint(j) > 2 {
		panic(badIdx)
	}
	return r3.Vec{X: m.at(0, j), Y: m.at(1, j), Z: m.at(2, j)}
}
```

</details>

### Potential impact of proposal

Above is a working example of a 3x3 matrix. Of course with time the routines could be optimized for the special case of 3x3 arguments to Add, Mul, etc. Let me know what you think!

`Mat` implements the `mat.Matrix` interface. Maybe it is worth having `r3.Vec` implement the `Vector` interface so that there is better gonum package interoperability.

**Comment by sbinet** [comment]
I am in favor of this proposal (I vaguely remember making the point for such a thing (well, `Vec` actually) last year).

a couple of "drive-by" comments:
- it would be great to be able to implement `mat.Matrix` w/o importing `mat` (but that's not possible)
- I would implement `Mat3` as a `struct{ x00, x01, ... x22 float64}` as it's more amenable to SSA optimizations
- I would `s/Mat3/Mat3x3/g`
- I would `s/IdentityMat3/Id3x3/` or `Identity3x3` or `Eye3x3`
- I would drop `CloneDense` (that can be done with `mat.DenseCopyFrom`)
- I would drop `CopyToMat3` and instead implement the `mat.ClonerFrom` interface

@kortschak WDYT?

**Comment by kortschak** [comment]
I think we can probably simplify the name to `Mat` since r3 is already in the package name. With that in mind, `IdentityMat` and I agree with the drops.

I am not convinced by the use of a struct with named fields for elements, I was thinking `struct { data [3][3]float64 }` all on pointers. There is no need for `String`

**Comment by sbinet** [comment]
I think changing `type Mat [3*3]float64` for `type Mat struct {data [3][3]float64}` doesn't buy you anything, performance-wise.
at least that's what I understood from this discussion:
https://github.com/gonum/gonum/pull/1297#issuecomment-603466614

**Comment by kortschak** [comment]
Yeah, I wasn't thinking about performance. It is clearer though. Thanks for linking that, I thought I remembered a conversation about this kind of thing. If it is hidden behind a struct wall, it can be changed.

**Comment by soypat** [comment]
@sbinet @kortschak  I agree with all your comments. I can make a PR for the agreed upon drops.
