### ISSUE TITLE
spatial/r3: Adding more functionality to Mat type

### ISSUE THREAD

**Issue by soypat** [gonum/gonum#1757]
### What are you trying to do?
**Vector Product** method

Adding `Mat.VecProd(v1,v2t)` or similar for multiplying two `r3.Vec` to obtain a matrix as in `Mat = Vec1 * Vec2ᵀ`. Seems to appear often in the literature I'm using.

<details><summary>VecProd()</summary>

```go
// Prod performs vector multiplication as if they were matrices
//  m = v1 * v2ᵀ
func (m *Mat) VecProd(v1, v2t r3.Vec) {
	m.Set(0, 0, v1.X*v2t.X)
	m.Set(0, 1, v1.X*v2t.Y)
	m.Set(0, 2, v1.X*v2t.Z)

	m.Set(1, 0, v1.Y*v2t.X)
	m.Set(1, 1, v1.Y*v2t.Y)
	m.Set(1, 2, v1.Y*v2t.Z)

	m.Set(2, 0, v1.Z*v2t.X)
	m.Set(2, 1, v1.Z*v2t.Y)
	m.Set(2, 2, v1.Z*v2t.Z)
}
```

</details>

**Rotation tensor from quaternion** method

Having a rotation tensor from a quaternion would be incredibly useful to have natively as a method:
`[R] = q.Real*q.Real * [E] - dot([q],[q])*[E] + 2*[q]*[q]ᵀ + 2*q.Real * skew([q])`, where `[q] = {q.Imag, q.Jmag, q.Kmag}` and `[E]=Eye()`

<details><summary>FromQuat()</summary> 

```go
// Not tested
func (m *Mat) RotationFromQuat(q quat.Number) {
	qv := r3.Vec{X: q.Imag, Y: q.Jmag, Z: q.Kmag}
	qs := Skew(qv)
	q01 := Identity()
	q01.Scale(q.Real*q.Real, q01)

	qd := Identity()
	qd.Scale(r3.Dot(qv, qv), qd)

	qs.Scale(2*q.Real, qs)

	qv = r3.Scale(2, qv)
	m.Prod(qv, qv) // m = 2*[q]*[q]ᵀ
	m.Add(m, q01)  // m += q.Real*q.Real * [E]
	m.Add(m, qd)   // m += dot([q],[q])*[E]
	m.Add(m, qs)   // m += 2*q.Real * skew([q])
}
```

</details>

I can also add the following:
* Determinant: Should be package level function? Or method? I feel it to be more of a function kind.
* Inverse: Probably a method which receives a 3x3 `mat.Matrix` and stores the result in the receiver?

### Is this feature absent from the current master?
Yes

### Are you able to help contribute the feature?
Yes

**Comment by kortschak** [comment]
> Adding `Mat.VecProd(v1,v2t)` or similar for multiplying two `r3.Vec` to obtain a matrix as in `Mat = Vec1 * Vec2ᵀ`. Seems to appear often in the literature I'm using.

See https://pkg.go.dev/gonum.org/v1/gonum/mat#Dense.Outer

To make this work well would require that `Vec` here satisfy `mat.Vector` though this is a heavy change.

> Determinant: Should be package level function? Or method? I feel it to be more of a function kind.

We have package level `Det` and `LogDet` in mat. These don't currently specialise for types that have their own `Det` or `LogDet` method, but they could. This should be a method here.

> Inverse: Probably a method which receives a 3x3 mat.Matrix and stores the result in the receiver?

Yes, see https://pkg.go.dev/gonum.org/v1/gonum/mat#Dense.Inverse.

**Comment by soypat** [comment]
Alright, sounds good. I'll wait for #1756 to come through before starting a branch.

Any thoughts on `func (m *Mat) RotationFromQuat(q quat.Number)`?

**Comment by kortschak** [comment]
There's not much to think about really. The only concern I have is adding quat as a dep for r3, but I guess that doesn't matter.

**Comment by soypat** [comment]
What method would we use to solve for the inverse of r3.Mat?
