### ISSUE TITLE
num/quat: Adding Norm, Norm2, and Normalize functions

### ISSUE THREAD

**Issue by soypat** [gonum/gonum#1758]
### What are you trying to do?

Trying to use quaternions for building rotation matrices. These need to be normalized `Sqrt(q.Real^2+q.Imag^2+q.Jmag^2+q.Kmag^2)=1`.

### How does Gonum not allow you to achieve your goal?
Missing a `Normalize` Method which is numerically stable. The literature I follow also uses the Norm and Norm2 (`r3` package equivalent) often, maybe they could be included.

### Is this feature absent from the current master?
Yes

### Are you able to help contribute the feature?
Yes. I'd need to investigate on state of the art methods of normalizing quaternions because the literature I'm using may be a bit old.

**Comment by kortschak** [comment]
These exist as [`Abs`](https://pkg.go.dev/gonum.org/v1/gonum/num/quat#Abs).

**Comment by soypat** [comment]
Thanks for the clarification. What about having Norm and Norm2 equivalents?

**Comment by kortschak** [comment]
`Norm2` is `x := quat.Abs(q); x*x` and `Normalize` is `quat.Scale(1/quat.Abs(q), q)`. Is there a reason that these are not good enough?

**Comment by soypat** [comment]
A quick google search shows that this method of normalizing a quaternion is standard. The literature I was reading made it seem as if there was more to it. Nevermind!
