### ISSUE TITLE
[gonum@v0.9.3/graph/path/dijkstra] Function path.DijkstraFrom crashes on go1.18 reporting segfault

### ISSUE THREAD

**Issue by betterchen** [gonum/gonum#1788]
Function path.DijkstraFrom brokes after upgraded go env to v1.18-ARM64 on a M1 chip Mac.

When called it crashes and reports segfault:
```
unexpected fault address 0x7000105
fatal error: fault
unexpected fault address 0x8000101
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7000105 pc=0x100df1608]
```

After that I tried the tests under gonum.org/v1/gonum@v0.9.3/graph/path. 

On Go1.17.7 the tests passed:
<img width="335" alt="Screenshot 2022-03-16 at 10 43 16 AM" src="https://user-images.githubusercontent.com/12558511/158506224-ca867489-91ba-4352-9dc6-0f7997387dc6.png">

On Go1.18 the tests failed as segmentation violated:
<img width="564" alt="Screenshot 2022-03-16 at 10 44 48 AM" src="https://user-images.githubusercontent.com/12558511/158506339-f0cc41c0-0c68-4390-8591-f59f5c0c3e58.png">

**Comment by kortschak** [comment]
Gonum 9.3 does not support 1.18. This is #1775.
