### ISSUE TITLE
proposal: spatial package: add Box, Triangle types and Elem functions

### ISSUE THREAD

**Issue by soypat** [gonum/gonum#1791]
### Background
I am developing a [replacement](https://github.com/soypat/sdf) for a [Signed Distance Function](https://en.wikipedia.org/wiki/Signed_distance_function) (SDF) library for generating 2D and 3D shapes. This module I am writing makes as heavy use of spatial types and algorithms, notably
* Vectors (Already implemented as `rn.Vec` types)
* Bounding Boxes (Implemented only as `r2.Box`)
* Triangles (Not implemented by gonum)
* [Elem functions](https://github.com/soypat/sdf/blob/main/internal/d3/vector.go#L37) such as the [Hadamard product](https://en.wikipedia.org/wiki/Hadamard_product_(matrices)). These functions operate on individual elements of vectors.

I am keen on using gonum as the defacto package for all this logic, but it requires the types be added. I am available to contribute this feature.

### Proposal
I've been working with these types for the past two weeks, so keep in mind my experience is far from thorough.

#### Adding Box types and utility methods
The Box type is already present in `r2`, this proposal would seek to add it to `r3` as well.

This proposal would also seek to add utility **methods** to the Box type. I have the library I wrote to measure how often [I've used these methods](https://github.com/soypat/sdf/blob/main/internal/d3/box.go#L11):
* `Size`.  Size returns the size of a 3d box. Very commonly used in bounding box operations.
* `Center`.  Center returns the center of a 3d box. Very commonly used in bounding box operations.
* `Vertices`.  Vertices returns a slice of 3d box corner vertices. Very commonly used in bounding box operations.
* 9 uses of `Extend`. Extend returns a box enclosing two 3d boxes.
* 8 uses of `Translate`. Translate translates a 3d box with a Vec
* 2 uses of `Enlarge` . Enlarge returns a new 3d box enlarged by a size vector
* 1 use of `func (a Box) MinMaxDist2(p r3.Vec) (min, max float64)` returns the minimum and maximum dist * dist from a point to a box. Is quite complex for such a simple objective.

I think gonum is a well suited place for these kind of functions. That said I'd like to open the floor for discussion on how best to combine the functions (or even add others not mentioned here) so that more can be done with less.

#### Add Triangle types
Adding triangle types for `r2` and `r3` packages.

Renderers require using triangles for representing 3D and 2D models. Below is the type declaration of Triangle from the [sdf package](https://github.com/soypat/sdf/blob/main/render/render.go).
```go
type Triangle3 struct {
	// Triangle vertices. Ordering of these vertices decides Normal vector direction. Inverting ordering of two vertices inverts the resulting direction.
	V [3]r3.Vec
}
```
As of today there are only two methods on the Triangle type which are commonly used. I'd like for these to be added to gonum as well!
* `func (t Triangle3) Normal() r3.Vec` Normal returns the normal vector to the plane defined by the 3D triangle given the numbering scheme of the vertices
* `func (t Triangle3) Degenerate(tolerance float64) bool` Degenerate returns true if the triangle is degenerate. Implementation is incorrect in sdf library.

This functionality and types should also be added to `r2` package.

#### Elem functions
Add all or a subset of proposed Elem functions to `r2` and `r3` packages.

Now this is where it gets opinionated. I am unsure if the `Elem` functions are a good fit for gonum mainly because I have yet to have needed them outside of the sdf package (with some exceptions), something which is not true for the previous types and functions. Here are some numbers to illustrate why I have included them in this proposal:

* The `Elem` function has been used a total of 91 times, only in the sdf module. I have also made use of it outside of sdf on several occasions.
```go
// Elem returns a vector with all components set to `f`
func Elem(f float64) r3.Vec {
	return r3.Vec{
		X: f,
		Y: f,
		Z: f,
	}
}
```
Find these function implementations [here at vector.go](https://github.com/soypat/sdf/blob/main/internal/d3/vector.go#L37)
* 30 combined uses of `MinElem` and `MaxElem`. MinElem return a vector with the minimum element-wise components of two vectors.
* 13 uses. `func EqualWithin(a, b r3.Vec, tol float64) bool` returns true if vectors are within `tol` of eachother, element wise. Could be renamed to `EqualElem`
* 8 uses of `AbsElem`. returns vector with components set to their absolute value.
* 9 uses of `MulElem`. Performs Hadamard product between two vectors
* 6 uses of `DivElem`. Performs Hadamard product between a vector a and the inverse components of a vector b.

### Potential impact of proposal
This proposal seeks to only add functionality. No breaking changes intended.

#### Pros:
* This package would bring gonum into the forefront as a viable module to be used with 3D libraries.
* Minimal API footprint added for `Box` and `Triangle` types

#### Cons
* Requires adding a significant API footprint for `Elem` functions.

**Comment by kortschak** [comment]
This sounds OK to me at least to start a PR to discuss, though I think the elems part should wait as it looks like a significant additions.

Also, I would suggest `Extend` => `Union`, `Translate` => `Add`, `Enlarge` => `Scale`.

**Comment by soypat** [comment]
Triangle and Box types have been added. Elem functions can wait, as they can easily be implemented as external functions without breaking interface APIs, which was my primary concern in adding Box and Triangle types.
