### ISSUE TITLE
spatial/rn: Remove deprecated Vec methods

### ISSUE THREAD

**Issue by soypat** [gonum/gonum#1796]
Files marked for removal in v0.10.0 still remain in v0.11.0:

https://github.com/gonum/gonum/blob/master/spatial/r3/deprecated.go#L7

https://github.com/gonum/gonum/blob/master/spatial/r2/deprecated.go#L7

**Comment by kortschak** [comment]
This can be done now, but will be in the v0.12.0 milestone.

**Comment by soypat** [comment]
Seems to be done, shall we close?
