### ISSUE TITLE
Add quaternion spherical interpolation function

### ISSUE THREAD

**Issue by soypat** [gonum/gonum#1803]
This is a common function used for computer graphics.

https://en.wikipedia.org/wiki/Slerp

A tried and tested implementation can be found at [three.js](https://github.com/mrdoob/three.js/blob/14030014c00a5a0f0e2b052d9b6773a6c49055f2/src/math/Quaternion.js#L535). I can help contribute the feature.

**Comment by kortschak** [comment]
With quats, slerp is not that hard; all you need to do is take the n-th root of a transform for an n-step slerp from the start to the end of the transform. The same for the dual quat and dual complex. I don't think this is needed. You can demonstrate this with minor changes to https://pkg.go.dev/gonum.org/v1/gonum/num/quat#example-package-Rotate.

**Comment by soypat** [comment]
So like `nthRoot:= quat.Number{Real:math.Pow(q.Real, 1/n), Imag: math.Pow(q.Imag, 1/n), Kmag:math.Pow(q.Kmag, 1/n),Jmag:math.Pow(q.Jmag, 1/n)}` ? I can't find anything on this algorithm with a cursory google search.

**Comment by kortschak** [comment]
No, `quat.Pow(q, quat.Inv(quat.Number{Real: n}))`. I'll find some papers.
