### ISSUE TITLE
[matrix/mat64]: Dense.Mul(A, B.T()) result has a slight innacuracy

### ISSUE THREAD

**Issue by Pro7ech** [gonum/gonum#1815]
### What are you trying to do?
Multiply the dense matrix A with the dense matrix B transposed: `C.Mul(A, B.T())`

### What did you do?

`C.Mul(A, B.T())`

with

Flattened A (4x4): `[0.8903922985882329, -0.5100698294124405, 0.31191253039081035, -0.8913123208005992, -0.26482558673508294, -0.42103913368681445, -0.6151227806501357, 0.31066430162966485, 0.794339426299602, -0.6652911148818833, -0.4228286963890898, 0.8052096925410095, 0.6995605635257469, -0.45390639057303417, 0.21816038398071225, -0.49268798711432626]`
Flattened B (4x4):` [0.20932057595923914, 0.8810181760900249, 0.32912010643698086, -0.12457162562603963, -0.15072500585746862, 0.37364614573421884, -0.8687259615650476, -0.6869614905344175, -0.8060609621710308, -0.39817627882942586, 0.03042525700413079, 0.6272799219801937, -0.5714722548352502, -0.238685621400628, -0.3638836513393403, -0.062220310195153616]`

### What did you expect to happen?
I expected each coefficient of the result matrix to match the "by hand" inner product between the row vectors of the input matrices.

### What actually happened?
An error proportional to the matrix dimension times the float64 precision is introduced into the result matrix.

Expected result vs. actual result:
```
    matrix_plain_test.go:172: 0 -0.04931445207343839 -0.049314452073438375
    matrix_plain_test.go:172: 1 0.01654071730550144 0.016540717305501385
    matrix_plain_test.go:172: 2 -1.0642250704429372 -1.0642250704429372
    matrix_plain_test.go:172: 3 -0.44513030174726353 -0.44513030174726365
    matrix_plain_test.go:172: 4 -0.6675258060847824 -0.6675258060847824
    matrix_plain_test.go:172: 5 0.2035549060040068 0.20355490600400683
    matrix_plain_test.go:172: 6 0.5572715729420813 0.5572715729420812
    matrix_plain_test.go:172: 7 0.4563399566786064 0.45633995667860633
    matrix_plain_test.go:172: 8 -0.659329684311836 -0.659329684311836
    matrix_plain_test.go:172: 9 -0.5541360602814871 -0.5541360602814872
    matrix_plain_test.go:172: 10 0.1168443395669671 0.11684433956696716
    matrix_plain_test.go:172: 11 -0.19138746679300422 -0.19138746679300422
    matrix_plain_test.go:172: 12 -0.12029144798536429 -0.12029144798536426
    matrix_plain_test.go:172: 13 -0.12610555874940232 -0.12610555874940224
    matrix_plain_test.go:172: 14 -0.6855693997641257 -0.6855693997641257
    matrix_plain_test.go:172: 15 -0.34016832145305087 -0.34016832145305087
```

### What version of Go and Gonum are you using?
v0.11.0

### Others:

This behavior does not happen with `C.Mul(A, B)` and `C.Mul(A.T(), B)`.

**Comment by kortschak** [comment]
Can you please provide a self-contained reproducer.

**Comment by Pro7ech** [comment]
There you go
```
package main

import(
	"testing"
	"math/rand"
	"github.com/gonum/matrix/mat64"
	"github.com/stretchr/testify/assert"
)

func main(){}

func TestMat64(t *testing.T){

	r := rand.New(rand.NewSource(0))

	dim := 4

	a := make([]float64, dim * dim)
	b := make([]float64, dim * dim)


	for i := 0; i < dim*dim; i++{
		a[i] = (r.Float64()-0.5)*2
		b[i] = (r.Float64()-0.5)*2
	}

	A := NewFloatMatrix(dim, dim, a)
	B := NewFloatMatrix(dim, dim, b)
	C := NewFloatMatrix(dim, dim, nil)

	Am64 := mat64.NewDense(dim, dim, a)
	Bm64 := mat64.NewDense(dim, dim, b)
	Cm64 := mat64.NewDense(dim, dim, nil)

	t.Run("AxB", func(t *testing.T){
		Cm64.Mul(Am64, Bm64)
		C.Mul(A, B)
		assert.Equal(t, Cm64.RawMatrix().Data, C.Data)
	})
	
	t.Run("A^TxB", func(t *testing.T){
		Cm64.Mul(Am64.T(), Bm64)
		C.MulTransposeLeft(A, B)
		assert.Equal(t, Cm64.RawMatrix().Data, C.Data)
	})

	t.Run("AxB^T", func(t *testing.T){
		Cm64.Mul(Am64, Bm64.T())
		C.MulTransposeRight(A, B)
		assert.Equal(t, Cm64.RawMatrix().Data, C.Data)
	})
}

type FloatMatrix struct{
	Rows, Cols int
	Data []float64
}

func NewFloatMatrix(rows, cols int, data []float64) (m *FloatMatrix){
	m = new(FloatMatrix)
	m.Rows = rows
	m.Cols = cols

	if data == nil{
		m.Data = make([]float64, rows * cols)
	}else{

		if len(data) != rows * cols{
			panic("invalid data size: len(data) != rows * cols")
		}

		m.Data = data
	}

	return
}

func (m *FloatMatrix) Mul(A, B *FloatMatrix) {

	rowsA := A.Rows
	colsA := A.Cols
	colsB := B.Cols
	a, b, c := A.Data, B.Data, m.Data

	for x := 0; x < rowsA*colsB; x++ {
		i := x / colsB
		j := x - i*colsB
		r := 0.0
		tmp := a[i*colsA:]
		for k0, k1 := 0, j; k0 < colsA; k0, k1 = k0+1, k1+colsB {
			r += tmp[k0] * b[k1]
		}
		c[x] = r
	}
}

func (m *FloatMatrix) MulTransposeLeft(A, B *FloatMatrix) {
	rowsA := A.Rows
	colsA := A.Cols
	colsB := B.Cols

	a, b, c := A.Data, B.Data, m.Data

	for x := 0; x < colsA*colsB; x++ {
		i := x / colsB
		j := x - i*colsB
		r := 0.0
		for k, k0, k1 := 0, i, j; k < rowsA; k, k0, k1 = k+1, k0+colsA, k1+colsB {
			r += a[k0] * b[k1]
		}

		c[x] = r
	}
}

func (m *FloatMatrix) MulTransposeRight(A, B *FloatMatrix) {

	rowsA := A.Rows
	colsA := A.Cols
	colsB := B.Cols
	rowsB := B.Rows

	a, b, c := A.Data, B.Data, m.Data

	for x := 0; x < rowsA*rowsB; x++ {
		i := x / rowsB
		j := x - i*rowsB
		r := 0.0
		for k, k0, k1 := 0, i*colsA, j*colsB; k < colsA; k, k0, k1 = k+1, k0+1, k1+1 {
			r += a[k0] * b[k1]
		}
		c[x] = r
	}
}
```

**Comment by kortschak** [comment]
Note that you are importing an ancient version of the matrix package. Notwithstanding that, the issue is due to the fact that floating point arithmetic is a model of real number arithmetic. The order of operations makes a (exceedingly slight — on the order of 1e-16 as you note) difference and the operation order in the naive code here and the `gonum.Dgemm` multiply routine will be different.

This is not a problem. Please see https://floating-point-gui.de/ and the references it links to, particularly https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html.

**Comment by Pro7ech** [comment]
Thank you. I was aware of the behavior of floating point arithmetic, however what wasn't expected was that this behavior would only occur with one of the operations. Although the difference is small, it can actually become quite a problem in the context of deep learning since the error is proportional to the matrix dimension and gets amplified with the non-linear layer. Two models can quickly diverge due to this behavior, making debugging small tuning and reproducibility difficult to evaluate unless one make sure to use the exact same operations order everytime.

**Comment by kortschak** [comment]
Two things that you could try, use the cgo BLAS implementation (a call to `blas64.Use(cgo.Implementation{})` in your code will do this) which may have different behaviour (at the cost of requiring the use of Cgo) or make an explicit transpose copy of `b` when you want to do an AB^T (at the performance cost of a copy).

**Comment by vladimir-ch** [comment]
If your algorithm amplifies rounding errors, then it is not stable and you should think of a better approach. Otherwise you will get divergent results not only between models (which AFAIU you'd expect to give identical results in exact arithmetic) but also between runs (because of non-determinism from goroutines) or every time there is the tiniest change in input data.
