### ISSUE TITLE
Wrong certificate x509: “badiaenergies.3cx.eu” for www.gonum.org

### ISSUE THREAD

**Issue by awsom82** [gonum/gonum#1831]
### What are you trying to do?
update dependecy in go.mod and download deps to vendor folder

### What did you do?

`go mod tidy`

### What did you expect to happen?
updated go.sum. updated modules in vendor directory

### What actually happened?
```
gonum.org/v1/gonum/stat/distuv: unrecognized import path "gonum.org/v1/gonum": https fetch: Get "https://gonum.org/v1/gonum?go-get=1": x509: “badiaenergies.3cx.eu” certificate name does not match input
```

### What version of Go and Gonum are you using?

go1.19

### Does this issue reproduce with the current master?
yes

**Comment by kortschak** [comment]
I suspect this was transient; I cannot reproduce the failure.

**Comment by awsom82** [comment]
Hard to reproduce, this happened on `go1.14` under some third-party unmaintained modules
