### ISSUE TITLE
blas/gonum: add complex BLAS Level 2 functions

### ISSUE THREAD

**Issue by vladimir-ch** [gonum/gonum#184]
- [x] ZGEMV - matrix vector multiply
- [x] ZGBMV - banded matrix vector multiply
- [x] ZHEMV - hermitian matrix vector multiply
- [x] ZHPMV - hermitian packed matrix vector multiply
- [x] ZHBMV - hermitian banded matrix vector multiply
- [x] ZTRMV - triangular matrix vector multiply
- [x] ZTPMV - triangular packed matrix vector multiply
- [x] ZTBMV - triangular banded matrix vector multiply
- [x] ZTRSV - solving triangular matrix problems
- [x] ZTPSV - solving triangular packed matrix problems
- [ ] ZTBSV - solving triangular banded matrix problems
- [x] ZGERU - performs the rank 1 operation `A := alpha*x*y' + A`
- [x] ZGERC - performs the rank 1 operation `A := alpha*x*conjg( y' ) + A`
- [x] ZHER - hermitian rank 1 operation `A := alpha*x*conjg(x') + A`
- [x] ZHPR - hermitian packed rank 1 operation `A := alpha*x*conjg( x' ) + A`
- [x] ZHER2 - hermitian rank 2 operation
- [x] ZHPR2 - hermitian packed rank 2 operation

**Comment by btracey** [comment]
Almost there!
