### ISSUE TITLE
Renovate Bot can not lookup new versions for gonum

### ISSUE THREAD

**Issue by thielepaul** [gonum/gonum#1844]
### What are you trying to do?
When running renovate bot on my project, it fails to resolve the gonum dependency:

![image](https://user-images.githubusercontent.com/2041078/208883280-0cd966f0-07f4-4d58-a68d-18fadf121f8a.png)

Does anyone have any suggestions, why this is the case? I do not have this problem for any other dependency.

**Comment by kortschak** [comment]
This sounds like an issue with the bot. I'd suggest you ask there.

**Comment by thielepaul** [comment]
Sorry for replying, so late.

I looked in the log from the bot and found the following error: 
`GET https://gonum.org/v1/gonum?go-get=1 = (code=ERR_NON_2XX_3XX_RESPONSE, statusCode=404 retryCount=0, duration=228)`

I can reproduce this behavior with curl:
```
$ curl -I https://www.gonum.org/v1/gonum?go-get=1 
HTTP/2 404 
age: 98108
cache-control: public, max-age=0, must-revalidate
content-type: text/html; charset=utf-8
date: Tue, 03 Jan 2023 06:16:36 GMT
etag: 1505632130-ssl
server: Netlify
strict-transport-security: max-age=31536000
x-nf-request-id: 01GNY1YKCY900KVHM6X0R6FBX3
content-length: 14277
```

This does look like a problem with the gonum server to me. If you are sure it isn't, feel free to close this issue

**Comment by kortschak** [comment]
The bot should ignore the status code and should not restrict the request to the \<head\>.

**Comment by thielepaul** [comment]
thanks for your I help, but shouldn't the status code be `3XX` if it is a redirect?

**Comment by kortschak** [comment]
The `https://gonum.org/v1/gonum?go-get=1` redirects to `https://www.gonum.org/v1/gonum?go-get=1`. The latter is a 404.

**Comment by thielepaul** [comment]
It still feels a bit weird to me that a 404 is returned, and not a `2XX OK`, but if you say this is how it should work, feel free to close this issue

**Comment by kortschak** [comment]
Yeah, it is a bit weird, but it's how we sneak the meta tags out. It's not unique to Gonum.
