### ISSUE TITLE
Performance of /graph/path/shortest.go/allBetween is not great

### ISSUE THREAD

**Issue by netixx** [gonum/gonum#1848]
### What are you trying to do?
My app does network simulations. Doing so, I call the `AllBetween` method of `AllShortest` a lot.

### What did you do?

Doing some profiling, I observed that it was one of the main reason the code was slow.

### What did you expect to happen?
Gonum to be blazing fast :)

### What actually happened?
![image](https://user-images.githubusercontent.com/1488603/213174104-c6599370-fed0-4932-acfd-4d3411d49cab.png)
The calculation for this was taken from around 4h of simulations. As you can see, the allBetween accounts for almost 3h of execution, most of it due to the `growslice` runtime.

I seems that all the `append()` (or slicing ?) calls make this slow.
Maybe it could be rewritten using a generator pattern (channel, or func ?).

### What version of Go and Gonum are you using?

```
> go version
go version go1.19.4 darwin/amd64

> grep gonum.org/v1/gonum go.sum
gonum.org/v1/gonum v0.12.0 h1:xKuo6hzt+gMav00meVPUlXwSdoEJP46BR+wdxQEFK2o=
gonum.org/v1/gonum v0.12.0/go.mod h1:73TDxJfAAHeA8Mk9mf8NlIppyhQNo5GLTcYeqgo2lvY=
```

### Does this issue reproduce with the current master?
Code is the same, so I don't think it would change anything.

**Comment by kortschak** [comment]
Please try using a local version of gonum with the following changes. Removing all the allocations is not at all trivial, but this will reduce some of them — reducing the allocations of the path tree recursion is non-trivial without making assumptions that would require a heap of code duplication, but this at least stops `paths` and `seen` reallocs.
```diff
diff --git a/graph/path/shortest.go b/graph/path/shortest.go
index db6bb03f..625a912b 100644
--- a/graph/path/shortest.go
+++ b/graph/path/shortest.go
@@ -681,16 +681,50 @@ func (p AllShortest) AllBetween(uid, vid int64) (paths [][]graph.Node, weight fl
                n = p.nodes[to]
        }
        seen := make([]bool, len(p.nodes))
-       paths = p.allBetween(from, to, seen, []graph.Node{n}, nil)
+       p.allBetween(from, to, seen, []graph.Node{n}, func(path []graph.Node) {
+               paths = append(paths, path)
+       })
 
        return paths, weight
 }
 
-// allBetween recursively constructs a slice of paths extending from the node
+// AllBetweenFunc calls fn on all shortest paths from u to v. Paths containing
+// zero-weight cycles are not considered. If a negative cycle exists between u
+// and v, no path is considered.
+func (p AllShortest) AllBetweenFunc(uid, vid int64, fn func([]graph.Node)) {
+       from, fromOK := p.indexOf[uid]
+       to, toOK := p.indexOf[vid]
+       if !fromOK || !toOK || len(p.at(from, to)) == 0 {
+               if uid == vid {
+                       if !fromOK {
+                               fn([]graph.Node{node(uid)})
+                               return
+                       }
+                       fn([]graph.Node{p.nodes[from]})
+                       return
+               }
+               return
+       }
+
+       if math.Float64bits(p.dist.At(from, to)) == defacedBits {
+               return
+       }
+
+       var n graph.Node
+       if p.forward {
+               n = p.nodes[from]
+       } else {
+               n = p.nodes[to]
+       }
+       seen := make([]bool, len(p.nodes))
+       p.allBetween(from, to, seen, []graph.Node{n}, fn)
+}
+
+// allBetween recursively constructs a set of paths extending from the node
 // indexed into p.nodes by from to the node indexed by to. len(seen) must match
 // the number of nodes held by the receiver. The path parameter is the current
-// working path and the results are written into paths.
-func (p AllShortest) allBetween(from, to int, seen []bool, path []graph.Node, paths [][]graph.Node) [][]graph.Node {
+// working path and the results passed to fn.
+func (p AllShortest) allBetween(from, to int, seen []bool, path []graph.Node, fn func([]graph.Node)) {
        if p.forward {
                seen[from] = true
        } else {
@@ -698,14 +732,16 @@ func (p AllShortest) allBetween(from, to int, seen []bool, path []graph.Node, pa
        }
        if from == to {
                if path == nil {
-                       return paths
+                       return
                }
                if !p.forward {
                        ordered.Reverse(path)
                }
-               return append(paths, path)
+               fn(path)
+               return
        }
        first := true
+       seenWork := make([]bool, len(seen))
        for _, n := range p.at(from, to) {
                if seen[n] {
                        continue
@@ -720,9 +756,9 @@ func (p AllShortest) allBetween(from, to int, seen []bool, path []graph.Node, pa
                        to = n
                }
                path = path[:len(path):len(path)]
-               paths = p.allBetween(from, to, append([]bool(nil), seen...), append(path, p.nodes[n]), paths)
+               copy(seenWork, seen)
+               p.allBetween(from, to, seenWork, append(path, p.nodes[n]), fn)
        }
-       return paths
 }
 
 type node int64
```

**Comment by kortschak** [comment]
I have made some additional improvements to the code above that should further reduce allocations. Please provide a routine that I can use to build a benchmark from so that this can be included in the changes.

**Comment by kortschak** [comment]
I have a full set of changes that you can try in your code with a replace like in go.mod
```
replace gonum.org/v1/gonum => gonum.org/v1/gonum v0.12.1-0.20230121234131-25a80d6e6709
```
I will not merge this until it has been rigorously tested and can be justified with benchmarks; this is because the code is now more subtle. I'll wait for your test case code.

**Comment by netixx** [comment]
Thank you for the quick answer.

I didn't change my code, and I can definitely see some improvement!
![image](https://user-images.githubusercontent.com/1488603/213800965-71122682-8eae-4873-ab85-4d74c596d9d4.png)
(If I read the graph correctly, I would say around 5% for my workload).

We are now spending roughly 50% doing `makeslice` and 50% doing `growslice`.

Would it be better if I changed my code to use `AllBetweenFunc` ?

**Comment by kortschak** [comment]
You should see improvements if you use `AllBetweenFunc`. What is there looks promising. Are you able to provide code to base a benchmark on?

**Comment by netixx** [comment]
Tested the new code (*not* using AllBetweenFunc yet), with the following results (improved again!):
![image](https://user-images.githubusercontent.com/1488603/214029727-545d8743-7d05-498b-ae3b-48a94b182117.png)


I am working on a graph of this map: http://weathermap.ovh.net/
I think it resembles a smallworld graph: https://pkg.go.dev/gonum.org/v1/gonum/graph/graphs/gen#SmallWorldsBB

**Comment by kortschak** [comment]
See #1850.

**Comment by netixx** [comment]
Great thanks!
