### ISSUE TITLE
hang for large numbers of ids using graph/set/uid.go NewID() function 

### ISSUE THREAD

**Issue by globalflea** [gonum/gonum#1853]
### What are you trying to do?
Testing out the performance of the `graph/set/uid.go` `NewID()` function

i noticed there's a rather in-efficient piece of code in `graph/set/uid.go`, the performance will get worse if i keep adding nodes without removing any.

### What did you do?
I tried timing the creation of 1B nodes with the following code:
```go
        max := 1_000_000_000 
	for i := int64(0); i < max; i++ {
		id := s.NewID()
		s.Use(id)
	}
```

### What did you expect to happen?
i expect it to complete within a few seconds max

### What actually happened?
when max is: 
1_000_000, it took a total 167ms (150ns per op)
1_000_000_0, it took a total 1.87s (192ns per op)
1_000_000_00, it took a total 22s (215ns per op)
1_000_000_000, ... i gave up waiting after a few minutes

Essentially, my intel mac book pro just hang there ... for a very long time (over several minutes)

### What version of Go and Gonum are you using?
go ver 19.6
gonum - main branch

### Does this issue reproduce with the current master?
yes

**Comment by kortschak** [comment]
Is this a problem in a real world use? If you have a graph with 1e9 nodes, I don't think ID allocation is going to be the limiting factor in any functions that deal with graphs.

It is worth noting that if you have a known set of IDs to use, you can just use `simple.Node(id)` to construct the node given the `id`, this is constant time ~ns. Alternatively, you can wrap the graph type we provide and replace the `NewID` method with your own. The graph types in simple and  multi are primarily present to ensure that we have robust graphs to test the algorithms that are in the graph packages, this may mean they are slower in the general case; specialise what you need.

**Comment by globalflea** [comment]
thanks
