### ISSUE TITLE
Several test failures on s390x

### ISSUE THREAD

**Issue by gibmat** [gonum/gonum#1873]
### What are you trying to do?

Several tests fail when run on the s390x architecture. This has been seen for a while in the Debian packaging (for instance, https://ci.debian.net/data/autopkgtest/unstable/s390x/g/golang-gonum-v1-gonum/33999494/log.gz), and has been blocking the ability of gonum to properly migrate into Debian.

### What did you do?

Run the tests as part of the build with `go test`.

### What did you expect to happen?

Tests pass as they do on other architectures (amd64, i386, arm64, etc).

### What actually happened?

Failing tests:

```
--- FAIL: ExampleDerivative (0.00s)
got:
f′(0) ≈ 1
f′(0) ≈ 0.9999998333333416
f′′(0) ≈ -2.999999970665357
want:
f′(0) ≈ 1
f′(0) ≈ 0.9999998333333416
f′′(0) ≈ -2.999999981767587
```

```
[snip a ton of reported failures]
    amos_test.go:354: Case zseri yi_idx_1: Float64 mismatch. c = -45.45886137570029, native = 147.8222449816137
         cb: 13854966620137784289, nb: 4639405049434679959
    amos_test.go:354: Case zseri yi_idx_2: Float64 mismatch. c = -100.90526160601746, native = 8.51342233431811
         cb: 13860173030331779800, nb: 4620982248761318737
--- FAIL: TestZacai (12.01s)
```

```
[snip a ton of reported failures]
    amos_test.go:354: Case zseri yi_idx_4: Float64 mismatch. c = -8.848345645672536e+68, native = -8.796985853913224e+68
         cb: 14861994222645354487, nb: 14861967411583063086
    amos_test.go:354: Case zseri yi_idx_5: Float64 mismatch. c = 2.845067377894076e+68, native = 2.8761262203281526e+68
         cb: 5630936712465022803, nb: 5631001566354080705
--- FAIL: TestZseri (19.93s)
```

```
    unconstrained_test.go:1221: Case 61: error finding minimum (linesearch: failed to converge) for:
        F: ExtendedRosenbrock
        Dim: 2
        Initial X: [100000 100000]
        GradientThreshold: 1e-10
--- FAIL: TestBFGS (0.93s)
```

```
    stat_test.go:1261: Moment mismatch case 3. Expected 1598.600579313326, found 1598.6005793133259
--- FAIL: TestMixedMoment (0.00s)
```

### What version of Go and Gonum are you using?

gonum 0.13.0 and golang go 1.20.5.

### Does this issue reproduce with the current master?

Haven't tested current HEAD, but would expect the same failures as they've been happening for a while now.

**Comment by kortschak** [comment]
s390x is not a supported architecture (see https://github.com/gonum/gonum/#supported-go-versions). We make some effort to ensure that different architectures' floating point implementations work with Gonum implementations, but this depends on dev time and test appliance availability. The first is stretched and the second in the case of s390x is non-existent, so this is not something that we can fix.
