### ISSUE TITLE
gonum/mat: Dense Matrix Multiplication Bug

### ISSUE THREAD

**Issue by OxQuasar** [gonum/gonum#1930]
Multiplying a matrix with correctly matching rows and columns still sometimes throws a dimension mismatch error:

Example: 
```
a := mat.NewDense(3, 2, []float64{1, 2, 3, 4, 5, 6})
b := mat.NewDense(2, 3, []float64{1, 2, 3, 4, 5, 6})
a.Mul(a, b)
panic: mat: dimension mismatch [recovered]
panic: mat: dimension mismatch
```

Interestingly, when the cols of the second matrix also match it does not give error: 
```
a := mat.NewDense(3, 2, []float64{1, 2, 3, 4, 5, 6})
b := mat.NewDense(2, 2, []float64{1, 2, 3, 4})
a.Mul(a, b)
```
works just fine. 

### What version of Go and Gonum are you using?

go version go1.20.1 linux/amd64
gonum.org/v1/gonum v0.14.0 h1:2NiG67LD1tEH0D7kM+ps2V+fXmsAnpUeec7n8tcr4S0=
gonum.org/v1/gonum v0.14.0/go.mod h1:AoWeoz0becf9QMWtE8iWXNXc27fK4fNeHNf/oMejGfU=

### Does this issue reproduce with the current master?
Yes

**Comment by kortschak** [comment]
```
a := mat.NewDense(3, 2, []float64{1, 2, 3, 4, 5, 6})
b := mat.NewDense(2, 3, []float64{1, 2, 3, 4, 5, 6})
a.Mul(a, b)
```
`a.Dims()` does not match the dimension of the product. This is working as intended. The relevant documentation is [here](https://pkg.go.dev/gonum.org/v1/gonum/mat#hdr-Empty_matrix) and in the sentence above that section:

> When a matrix is the destination or receiver for a function or method, the operation will panic if the matrix is not the correct size. An exception to this is when the destination is empty (see below).
