### ISSUE TITLE
gonum/mat: NewTridiag has arguments flipped

### ISSUE THREAD

**Issue by chinsoon12** [gonum/gonum#1936]
### What are you trying to do?
Solving A * x = b where 
```
A = [ 2  1  0  0
      3  2  1  0
      0  3  2  1
      0  0  3  2  ]
```
`b = [3, 6, 6, 5]^T`
x should be `[1, 1, 1, 1]^T`

### What did you do?
From https://pkg.go.dev/gonum.org/v1/gonum/mat#NewTridiag,

func NewTridiag(n [int](https://pkg.go.dev/builtin#int), dl, d, du [][float64](https://pkg.go.dev/builtin#float64)) *[Tridiag](https://pkg.go.dev/gonum.org/v1/gonum/mat#Tridiag)
NewTridiag creates a new n×n tridiagonal matrix with the first sub-diagonal in dl, the main diagonal in d and the first super-diagonal in du.

Code snippet
https://go.dev/play/p/YghQCf7zjr-
```
package main

import (
	"fmt"

	"gonum.org/v1/gonum/mat"
)

func main() {
	triDiag := mat.NewTridiag(4, []float64{3, 3, 3}, []float64{2, 2, 2, 2}, []float64{1, 1, 1})
	b := mat.NewVecDense(4, []float64{3, 6, 6, 5})
	var x mat.VecDense
	triDiag.SolveVecTo(&x, true, b)
	fmt.Println(x.RawVector().Data)

	triDiag = mat.NewTridiag(4, []float64{1, 1, 1}, []float64{2, 2, 2, 2}, []float64{3, 3, 3})
	triDiag.SolveVecTo(&x, true, b)
	fmt.Println(x.RawVector().Data)
}
```

### What did you expect to happen? What actually happened?
I am expecting x to be `[1, 1, 1, 1]`

But instead program is giving
`[5.1818181818181825 -2.454545454545455 1.9090909090909092 1.5454545454545454]`

But if I flip the dl and du, I get the correct answer:
`[1 1 1.0000000000000002 0.9999999999999996]`

### What version of Go and Gonum are you using?
go version go1.21.2 linux/amd64
gonum.org/v1/gonum v0.14.0

**Comment by kortschak** [comment]
The transpose refers to A, not b. This is working as intended. https://go.dev/play/p/l6pvD6l_1uJ

**Comment by chinsoon12** [comment]
Thanks, @kortschak.
