### ISSUE TITLE
spatial/r3: `Example_slerp` failure on arm64

### ISSUE THREAD

**Issue by gibmat** [gonum/gonum#1961]
### What are you trying to do?
When updating the Debian packaging of gonum from 0.14.0 to 0.15.0, the test `Example_slerp` fails on arm64. It passes on other architectures (amd64, armhf, i386). A full log can be viewed at https://ci.debian.net/packages/g/golang-gonum-v1-gonum/testing/arm64/44386624/:

```
--- FAIL: Example_slerp (0.00s)
got:
0.00 {1 -1.425e-16 1.414}
0.10 {1 -0.3301 1.375}
0.20 {1 -0.642 1.26}
0.30 {1 -0.9185 1.075}
0.40 {1 -1.144 0.8313}
0.50 {1 -1.307 0.5412}
0.60 {1 -1.397 0.2212}
0.70 {1 -1.41 -0.111}
0.80 {1 -1.345 -0.437}
0.90 {1 -1.206 -0.7389}
1.00 {1 -1 -1}
want:
0.00 {1 -1.11e-16 1.414}
0.10 {1 -0.3301 1.375}
0.20 {1 -0.642 1.26}
0.30 {1 -0.9185 1.075}
0.40 {1 -1.144 0.8313}
0.50 {1 -1.307 0.5412}
0.60 {1 -1.397 0.2212}
0.70 {1 -1.41 -0.111}
0.80 {1 -1.345 -0.437}
0.90 {1 -1.206 -0.7389}
1.00 {1 -1 -1}
FAIL
```

### What version of Go and Gonum are you using?
`go version go1.22.1 linux/arm64` on Debian sid
gonum v0.15.0

**Comment by kortschak** [comment]
This is the result of float implementation differences between the arm64 GOARCH and others. The fix is to reduce the precision of the example test. This should be in v0.15.1 after it is merged.
