### ISSUE TITLE
mat: calling qr.Factorize leads to OOM for matrixes with many rows

### ISSUE THREAD

**Issue by ericwenn** [gonum/gonum#1968]
### What are you trying to do?

After upgrading gonum to 0.15.0 calls to `(VecDense).SolveVec(a,b)` where `a.Dims() == (10k+, 3)`  leads to OOM.
The stack where OOM happens:
```
runtime.systemstack_switch()
        /nix/store/8yw3g52r95h7cv09lcrran92n212997b-go-1.22.0/share/go/src/runtime/asm_amd64.s:474 +0x8 fp=0xc000087230 sp=0xc000087220 pc=0x4788a8
runtime.(*mheap).alloc(0x3667b52000?, 0x1b33da9?, 0x80?)
        /nix/store/8yw3g52r95h7cv09lcrran92n212997b-go-1.22.0/share/go/src/runtime/mheap.go:958 +0x5b fp=0xc000087278 sp=0xc000087230 pc=0x42fc1b
runtime.(*mcache).allocLarge(0x100?, 0x3667b50b88, 0x1?)
        /nix/store/8yw3g52r95h7cv09lcrran92n212997b-go-1.22.0/share/go/src/runtime/mcache.go:234 +0x85 fp=0xc0000872c0 sp=0xc000087278 pc=0x41ce45
runtime.mallocgc(0x3667b50b88, 0xd67320, 0x1)
        /nix/store/8yw3g52r95h7cv09lcrran92n212997b-go-1.22.0/share/go/src/runtime/malloc.go:1165 +0x597 fp=0xc000087348 sp=0xc0000872c0 pc=0x4141d7
runtime.makeslice(0xc0000124b0?, 0x18?, 0xc0000874b0?)
        /nix/store/8yw3g52r95h7cv09lcrran92n212997b-go-1.22.0/share/go/src/runtime/slice.go:107 +0x49 fp=0xc000087370 sp=0xc000087348 pc=0x459989
gonum.org/v1/gonum/mat.NewDense(...)
        /home/ericwenn/go/pkg/mod/gonum.org/v1/gonum@v0.15.1-0.20240413203616-1b7d9ca04ac9/mat/dense.go:60
gonum.org/v1/gonum/mat.(*QR).updateQ(0xc000087630)
        /home/ericwenn/go/pkg/mod/gonum.org/v1/gonum@v0.15.1-0.20240413203616-1b7d9ca04ac9/mat/qr.go:107 +0x78 fp=0xc0000874c0 sp=0xc000087370 pc=0xb5fd38
gonum.org/v1/gonum/mat.(*QR).factorize(0xc000087630, {0x1070598, 0xc0004c6540}, 0x49)
        /home/ericwenn/go/pkg/mod/gonum.org/v1/gonum@v0.15.1-0.20240413203616-1b7d9ca04ac9/mat/qr.go:101 +0x316 fp=0xc0000875e0 sp=0xc0000874c0 pc=0xb5fc36
gonum.org/v1/gonum/mat.(*QR).Factorize(...)
        /home/ericwenn/go/pkg/mod/gonum.org/v1/gonum@v0.15.1-0.20240413203616-1b7d9ca04ac9/mat/qr.go:82
gonum.org/v1/gonum/mat.(*Dense).Solve(0xc0004c6700, {0x1070598, 0xc0004c6540}, {0x1070598, 0xc0004c6740})
        /home/ericwenn/go/pkg/mod/gonum.org/v1/gonum@v0.15.1-0.20240413203616-1b7d9ca04ac9/mat/solve.go:65 +0x245 fp=0xc000087700 sp=0xc0000875e0 pc=0xb63545
gonum.org/v1/gonum/mat.(*VecDense).SolveVec(0xc000110360, {0x1070598, 0xc0004c6540}, {0x10735c0, 0xc0001103c0})
        /home/ericwenn/go/pkg/mod/gonum.org/v1/gonum@v0.15.1-0.20240413203616-1b7d9ca04ac9/mat/solve.go:118 +0x6fa fp=0xc000087930 sp=0xc000087700 pc=0xb63e9a
``` 
I've traced this down to changes in `mat.QR.updateQ` [here](https://github.com/gonum/gonum/commit/45b74210d616dd61bb893f6e8e4af13879b1d6bb#diff-5bf82974a09725d659ece49d56eff0b81eafc1a476a618949ec743544e329aaeR104-R117).

What `updateQ` does is allocate a new `Dense` with dimensions `MxM`, which for our value on M would mean allocating 100M cell matrix. Based on my understanding of the code, the resulting matrix should have dimensions (`MxN`).

### What version of Go and Gonum are you using?

```
$ go version
go version go1.22.0 linux/amd64

$ grep gonum.org/v1/gonum go.sum
gonum.org/v1/gonum v0.15.0 h1:2lYxjRbTYyxkJxlhC+LvJIx3SsANPdRybu1tGj9/OrQ=
gonum.org/v1/gonum v0.15.0/go.mod h1:xzZVBJBtS+Mz4q0Yl2LJTk+OxOg4jiXZ7qBoM0uISGo=
```

### Does this issue reproduce with the current master?

Yes

**Comment by tvkn** [comment]
I believe the issue arises when one tries to solve very large systems.

The issue is introduced by [this commit](https://github.com/gonum/gonum/commit/45b74210d616dd61bb893f6e8e4af13879b1d6bb) which explicitly computes and store the `Q` matrix (instead of just the reflectors `tau`).

The `Q` matrix doesn't seem to be explicitly needed in the QR `SolveVec`, but the new update forces its computation, which in practice can limit the size of the linear systems the function can solve.

**Comment by ericwenn** [comment]
Minimal reproduction test:
```go
func TestReproduction(t *testing.T) {
	const (
		M = 100_000
		N = 3
	)
	systemMat := mat.NewDense(M, N, make([]float64, M*N))
	measurementsVec := mat.NewVecDense(M, make([]float64, M))

	var results mat.VecDense
	err := results.SolveVec(systemMat, measurementsVec)

	fmt.Println(err)
}
```

On version `0.14.0` and below this correctly returns error `matrix singular or near-singular with condition number +Inf`, on version `0.15.0` it crashes due to OOM.

**Comment by kortschak** [comment]
Thanks. Yeah, for situations where the Q is not needed, this is a problem. I think we can get the performance benefit of the single pre-calculation by lazily calculating, but storing the value so the work is only done once. I'll take a look in the weekend.

**Comment by ericwenn** [comment]
> Thanks. Yeah, for situations where the Q is not needed, this is a problem. I think we can get the performance benefit of the single pre-calculation by lazily calculating, but storing the value so the work is only done once. I'll take a look in the weekend.

That would be great, thanks for the quick response!
