### ISSUE TITLE
Dijkstra  weight function - return false 

### ISSUE THREAD

**Issue by mmolbech** [gonum/gonum#1971]
**What are you trying to do?**

When doing dijkstra or (Yen..), i have made my own weight function - and if a path between two nodes for some reason shouldn't be calc'ed - then i would assume a return false would be accepted as edge not existing, and dijkstra continues with next edge 

But i see a panic instead  ? 

I was wondering if the behavior could be changed to just jump over this edge (if negativ) - and "accept" is a non existing node - that would be logical instead (for me)

https://github.com/gonum/gonum/blob/7bd265b283a3870871f92f50b37864e2d57b0deb/graph/path/dijkstra.go#L142

Just do a continue instead and do a log debug statement

**What version of Go and Gonum are you using?**

go version go1.19 linux/amd64

gonum.org/v1/gonum v0.15.0 h1:2lYxjRbTYyxkJxlhC+LvJIx3SsANPdRybu1tGj9/OrQ=
gonum.org/v1/gonum v0.15.0/go.mod h1:xzZVBJBtS+Mz4q0Yl2LJTk+OxOg4jiXZ7qBoM0uISGo=

But i see a panic instead  ? I was wondering if the behavior could be changed to 

**Does this issue reproduce with the current master?**
Yes

**Comment by kortschak** [comment]
If you want to avoid an edge, either remove it, filter it with a shim graph (this will not return edges within a filter set), or assign it an edge weight of +Inf. The last of these would be the easiest if you do not have other +Inf edge weights. If you do, I'd suggest implementing a filter shim, or just not returning edges that you can't calculate weights for.

The documentation for [`graph.Weighted`](https://pkg.go.dev/gonum.org/v1/gonum/graph#Weighted) explains the semantics here. If there is an edge, the weight must exist and so the weight call must return true.

This behaviour of Dijkstra is not something that will be changed.
