### ISSUE TITLE
Is there a method similar to python numpy eig method to compute the eigenvectors of a complex matrix

### ISSUE THREAD

**Issue by ztx8511** [gonum/gonum#1986]
python numpy code：

`
cmatrix=[....]
np.linalg.eig(cmatrix)
`

I didn't find a similar method in gonum framework. Do you have an answer on how to solve it.  thks.

**Comment by vladimir-ch** [comment]
There's no high-level API in "gonum.org/v1/gonum/mat" nor a pure Go implementation of Zgeev. You could use the low-level, cgo-based interface of "gonum.org/v1/netlib/lapack/lapacke.Zgeev" to call into your local Lapack implementation (like OpenBLAS).

**Comment by JuanVargas** [comment]
Please read my post at  the URL below, where  I provide an example of using Gonum's lapack64.Geev(args) to get the eigenvalues and eigenvectors of a matrix.

https://github.com/gonum/gonum/issues/1991
