### ISSUE TITLE
[graph/multi] ability to update a node

### ISSUE THREAD

**Issue by miparnisari** [gonum/gonum#1996]
### What are you trying to do?
I am trying to build a multigraph and then perform updates to some nodes. My nodes are of a custom type:

```go
type MyCustomNode struct {
	graph.Node
	label       string
}

// ... adding a node ...
node := g.NewNode()
newNode := &MyCustomNode{
	Node:        node,
	label:       "hi",
}
g.AddNode(newNode)
```

### What did you try?
- using `graph.Nodes()`:

```go
    iterNodes := multigraph.Nodes()
	for iterNodes.Next() {
		nextNode, ok := iterNodes.Node().(*MyCustomNodeType)
		if !ok { panic("cannot cast") }
        nextNode.myData = 1
   }
```

This doesn't work because the iterator is giving me a pointer to a copy of the data, not a pointer to the data stored in the graph.

- a custom `updateNode(node)` method that retrieves all the lines linked to this node, then removes `node.ID`, then adds `node` back, and finally re-adds all the lines. This seems terribly inefficient.

### How does Gonum not allow you to achieve your goal?
I can't find a way of updating a node in place.

### What version of Go and Gonum are you using?
0.15.1

### Is this feature absent from the current master?
Yes

### Are you able to help contribute the feature?
Maybe

**Comment by kortschak** [comment]
Can you provide a complete self-contained reproducer?

**Comment by kortschak** [comment]
```
package main

import (
	"fmt"

	"gonum.org/v1/gonum/graph/multi"
)

func main() {
	g := multi.NewUndirectedGraph()
	for i := range 10 {
		g.AddNode(&node{id: int64(i)})
	}

	it := g.Nodes()
	for it.Next() {
		fmt.Println(it.Node())
	}

	it.Reset()
	for it.Next() {
		it.Node().(*node).label = "changed"
	}

	it.Reset()
	for it.Next() {
		fmt.Println(it.Node())
	}
}

type node struct {
	id    int64
	label string
}

func (n *node) ID() int64 { return n.id }
```
```
&{3 }
&{4 }
&{9 }
&{2 }
&{1 }
&{5 }
&{6 }
&{7 }
&{8 }
&{0 }
&{5 changed}
&{6 changed}
&{7 changed}
&{8 changed}
&{0 changed}
&{1 changed}
&{4 changed}
&{9 changed}
&{2 changed}
&{3 changed}
```

**Comment by miparnisari** [comment]
@kortschak thanks for responding so quickly 🙇‍♀️ Yes, a quick demo works, this means that my code has some obscure bug that I cannot find 😢 

If you `git clone git@github.com:openfga/language.git` and then `gh pr checkout 351` you can see my code. Run the tests a couple of times and there is one test that is flaky: `TestWeightedGraphBuilder/nested_userset`. Sometimes, the custom data that I attach to a node is somehow lost and I can't figure out why.

**Comment by miparnisari** [comment]
So when I update a node in the graph, the associated lines to that node cannot "see" the change. Is that what you are saying?

>  I would recommend that you don't use anonymous fields 

Can you clarify this a bit? What anonymous field are you referring to?

**Comment by kortschak** [comment]
Sorry, I should say embedded, [here](https://github.com/openfga/language/blob/62204ec3fe00410e9868ec08ac2d64abb090732b/pkg/go/graph/graph_edge.go#L18).

**Comment by miparnisari** [comment]
Oh, ok. But even after changing that I see the Lines cannot "see" the updates I made to the Nodes. Did I miss something else?

**Comment by kortschak** [comment]
If I were you, I'd implement the interface rather than using the implementations we provide. This reduces the amount of code that's not under your control, and increases the number of locations that you can insert debugging.

**Comment by miparnisari** [comment]
I figured it out! When the graph was like this `a --> b <-- c`, upon creating the first edge `a --> b` i was creating new nodes `a` and `b`, but then on edge `b <-- c` i was _also_ creating a new node `b`, when it should have been the address of the previous node I wrote.
