### ISSUE TITLE
stat: PCA fails with noasm or appengine build tags

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#21]
The failure is due to numerical stability and only really shows up in the lowest valued column.

**Comment by vladimir-ch** [comment]
What shall we do with this?

The smallest singular value is practically zero and the SVD (and thus the principal vectors) is not unique in such case (if I'm not wrong). I think that the "numerical instability" is just the `noasm` tag finding another acceptable vector, which is also supported by the fact that `Mul(vecs.T(), vecs)` gives the identity matrix. Maybe the test should be changed to handle this or we can just continue ignoring the test case.
