### ISSUE TITLE
Add Access to the Negative Cycle found in Bellman Ford Moore

### ISSUE THREAD

**Issue by Noki** [gonum/gonum#217]
Since the Bellman Ford Moore algorithm terminates on finding a negative cycle it is often used for applications that require the detection of a negative cycle (e.g. cycle-cancelling techniques or finding arbitrage opportunities).

Currently the implementation only allows to test for the cycle. It would be great to make it accessible as well.

**Comment by kortschak** [comment]
WE already return the data in the `Shortest` value that `BellmanFordFrom` returns. This value is always populated unless the graph has an invalid weight. You should be able to extract the negative cycles from that using code [like that in the tail of the function](https://github.com/gonum/gonum/blob/d7342e68fbbe64d7dbbdc0feb4ecf60500444cdc/graph/path/bellman_ford_moore.go#L53-L64). If not please suggest changes to the `Shortest` API to help.

This would be a nice example to add to the package if you are interested.

**Comment by Noki** [comment]
Thank you @kortschak for pointing me into that direction. I'm interested in contributing, however it's been some time since I've been dealing with graph algorithms.  ;-)

I'll see if I can manage to wrap my head around.

Best regards
Tobias
