### ISSUE TITLE
blas/gonum:  Incorrect Dger results when NaN is an element of y.

### ISSUE THREAD

**Issue by Kunde21** [gonum/gonum#224]
Found while fuzzing blas:  The `if tmp != 0` short-circuit in `Dger` calculation causes incorrect handling of NaN elements in `y` vector.

**Comment by kortschak** [comment]
What is the expected result?

**Comment by Kunde21** [comment]
The NaN should propagate to the resulting `A` matrix element(s).

**Comment by kortschak** [comment]
Yeah, I think you're right; confirmed by looking at the Fortran [code](http://www.netlib.org/lapack/explore-html/dc/da8/dger_8f_source.html). Note that BLAS is all over the place with NaN handling, since if `alpha == 0`, there is no NaN propagation.

**Comment by vladimir-ch** [comment]
This topic was raised recently also in the reference lapack repository
about gemm and gemv https://github.com/Reference-LAPACK/lapack/issues/179.
BLAS does not seem to be consistent in this and implementations are
encouraged to deviate from the reference.

**Comment by Kunde21** [comment]
I'd think the all-or-none propagation from `alpha === 0` is a easier to understand and reason through.  Skipping propagation on a per-row or per-column basis introduces results that look like Heisenbergs.

**Comment by Kunde21** [comment]
Also, the all-or-none propagation can be done in the asm version, while the per-row/column can't without sacrificing performance.

**Comment by btracey** [comment]
The BLAS spec does not cover NaN, we've had some conversation about this in the past that I could try and find.

I think the most important thing is that we keep the NaN propagation the same between assembly and native Go. Otherwise, I think we do what's reasonable for performance.
