### ISSUE TITLE
all: consider generalising the random source parameter type

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#228]
We use a `*rand.Rand` as the source of randomness for routines we provide that need this. Recently, a new rand package was added to the golang/exp repo. For the most part this is a drop in replacement, but gonum clients can not use this. If we define a rand interface that matches the method set of `*rand.Rand` then that package will be usable. Is this something that we want to do? The alternative is to back up to the `rand.Source`-ish level and take that as the argument - this needs a shim to convert the signatures between the two.

**Comment by kortschak** [comment]
@btracey Do you have a view on this?

**Comment by sbinet** [comment]
I am ok with that even if we should also perhaps check going through an interface call doesn't impact too negatively a few meaningful (real life?) benchmarks.

note there are a few interesting differences between the two, and we should be careful not to paint ourself into a corner while creating our own `Rander` interface.

----

`exp/rand.Rand` and `math/rand.Rand` do have a few differences:

- https://godoc.org/golang.org/x/exp/rand#Rand
- https://godoc.org/math/rand#Rand

ie: `exp/rand.Rand` has:
- `func (r *Rand) Uint64n(n uint64) uint64`
- `func (r *Rand) Seed(seed uint64)`

while `math/rand.Rand` doesn't have `Uint64n` and has the following signature:
- `func (r *Rand) Seed(seed int64)`

**Comment by btracey** [comment]
Yes, I think we should do this.

**Comment by kortschak** [comment]
We should wait for the proposal document that @robpike has said is coming.

**Comment by robpike** [comment]
The proposal is #21835.

**Comment by kortschak** [comment]
Thanks, Rob.

**Comment by kortschak** [comment]
On the basis of the proposal, I'd like to suggest that we use the exp/rand.Source and change from math/rand to exp/rand, and then when the Go standard library makes the shift, change the import paths. This seems like the easiest path to follow.

@robpike The proposal is almost silent on the behaviour of the `rand.Source` that would by used in the Go2 math/rand package; if the implementation being used in exp/rand is used verbatim, there would be a change in the source stream method's signature from `Int64() int64` to `Uint64() uint64`, but this is not explicitly discussed in the proposal. Would that change be part of the proposal (the comment above is contingent on this being true).

**Comment by robpike** [comment]
@kortschak That question is in fact unresolved, but perhaps it will end up that the new Source contains both.

I would be happy to work with you to figure out what exp/rand should look like for you. That is somewhat independent of the proposal.

**Comment by kortschak** [comment]
The shape of exp/rand as it stands at the moment looks good to me. Retaining both looks like a reasonable way to retain backwards compatibility, though it's a little sad to expand the API surface.

I'll wait for others to comment here, but what you've said works for me.

**Comment by btracey** [comment]
I agree with @kortschak , the proposal sounds good and seems to be an improvement.

For your information @robpike , we essentially have the following use cases:
1) Numerical simulations like Monte Carlo rely on the statistical properties of the generator. Being a good random number is much more important that being fast.
2) We provide a lot of probability distributions that are outside the scope of `math/rand` (i.e. Gamma). We would like to support both the case where the user supplier their own random generator (currently we demand a `*math/rand.Rand`), or they do not and we use a default seed.
3) We have a fair number of tests that can fail with some small probability (especially ones testing the probability distributions). We'd like to have consistent tests to avoid the (small chance of flakiness).

It seems like your proposal is in line with all of these goals.

**Comment by kortschak** [comment]
@robpike I just made a now experimental foray into switching to exp/rand and struck a minor problem that will hold this until go1.11 is released. We support 3 Go releases, but exp/rand depends in math/bits for a single call to `bits.RotateLeft64`. Since math/bits was only added in go1.9, we have two releases that would be broken by this change. What is the prospect of a change being accepted to exp/rand that backports the `bits.RotateLeft64` as an unexported function to the rng.go file?

**Comment by robpike** [comment]
Instead, I would suggest we do a version of that code and build-tag it by version.

**Comment by kortschak** [comment]
That sounds good to me: the code is question is only a couple of lines. How far back? Just to 1.7 would work for us - I don't recall the Go support policy.

**Comment by rgeronimi** [comment]
This change, being performed before exp/rand went into the Go2 standard, has the net result in the meantime of making gonum uncompatible with math/rand sources of randomness a host program may have otherwise.

I am in the process of replacing old statistics code with calls to gonum and just realized that I cannot share randomness sources between both sides of my program. Of course I built an adapter in the meantime.

Is there any plan to integrate exp/rand this into Go2? Otherwise will this API decision to drift apart from the Go standard be reconsidered?

**Comment by kortschak** [comment]
Gonum will stay as it is. The question relating to the exp/rand and Go is a question for golang-dev (or less likely at golang/go#21835).
