### ISSUE TITLE
Quaternion math

### ISSUE THREAD

**Issue by ohlsont** [gonum/gonum#229]
Great lib! But using it I found one part missing which I could not find in code/issues. A fast google gave me this [westphae/quaternion](https://github.com/westphae/quaternion) which I'll use for now. Im using Quaternion as a part to test a simulation of a robot moving. Would be great to also have in this lib.

**Comment by sbinet** [comment]
@ohlsont could you tell us what is that "one part" that is missing from `gonum` ?

**Comment by ohlsont** [comment]
It's Quaternion. It's available in e.g. C++ math library Eigen.
https://eigen.tuxfamily.org/dox/classEigen_1_1Quaternion.html
https://en.m.wikipedia.org/wiki/Quaternion

**Comment by kortschak** [comment]
I think a starting point here is what you would like to see in a quaternion package. While it was an April fools joke, the *work* that was done for the math/quat package might be a good starting point. See the CLs here, among others (there is obviously much more in these CLs than needed for a package here):

- [spec](https://go-review.googlesource.com/c/39213/1)
- [runtime and compiler](https://go-review.googlesource.com/c/39217/1)
- [math/quat](https://go-review.googlesource.com/c/39220/1)
