### ISSUE TITLE
graph: add NewNodeID(id int64) Node

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#230]
We need a way for some classes of random graph generation (and other things) to be able to request a specific node ID (we can get away with out it, but it becomes less efficient). Since we removed the `NewNodeID() intT` method, we can now use that name to return a new node with a given ID. There are three obvious possible signatures:

```
// NewNodeID returns a node with the given ID.
// If the node exists in graph it is returned
// otherwise a new Node is returned.
NewNodeID(id int64) Node
```
```
// NewNodeID returns a new node with the given
// ID. If the node exists in the graph n is returned
// nil and ok false.
NewNodeID(id int64) (n Node, ok bool)
```
```
// NewNodeID returns a new node with the given ID if possible.
NewNodeID(id int64) (Node, error)
```

I think I prefer the last one, it is the most general and clearest. The new method would go in `NodeAdder` and be added to the sparse graphs we have in simple.

/cc @mewmew

**Comment by mewmew** [comment]
I prefer the signature

```go
// NewNodeID returns a node with the given ID.
// If the node exists in graph it is returned
// otherwise a new Node is returned.
NewNodeID(id int64) Node
```

mainly because there is currently no way of retrieving a Node from a given node ID. In addition, we may wish to look at refining `Has` to

```go
// Has returns whether the node exists within the graph.
Has(id int64) bool
```

**Comment by mewmew** [comment]
> ... what to do when an ID is not valid for the graph (e.g. the dense matrix-based graphs) ...

For this reason, I think it should be up to the individual graph implementation whether to support a `NewNodeID` method, as such a method would give users control over node ID generation. Graph implementations which support arbitrary node IDs (e.g. maps/adjacency lists) may provide a `NewNodeID` method.

Do you foresee many users of this functionality? Random graph generation and test cases would be the top two I can think of. For test cases at least, it seems reasonable to use a specific graph type, e.g. simple which may provide a `NewNodeID` method; so no need to add it to the `NodeAdder` interface.

In general, I believe we should try to keep the interfaces minimal, intersect of functionality rather than union. This was the same rationale applied when splitting the Graph interface into `graph.Weighted` and `graph.Graph`.

**Comment by kortschak** [comment]
An alternative is to partially go back to where we were with `NewNodeID`. Under this model, `NodeAdder` becomes

```
type NodeAdder interface {
    // NewNode returns a new unique arbitrary ID.
    // The returned ID is only guaranteed to be valid
    // if ok is returned true and no intervening call
    // to AddNode has been made.
    NewNodeID() (id int64, ok bool)

    // Node returns a possibly newly constructed
    // Node with the given ID. If no Node can be
    // created with the specified ID, the returned
    // Node will be nil.
    Node(id int64) Node

    // Adds a node to the graph. AddNode panics if
    // the added node ID matches an existing node ID.
    AddNode(Node)
}
```

Then to add a new node you would have use like

```
id, ok := g.NewNodeID()
if ok {
    g.AddNode(g.Node(id))
}
```

and to get a client defined node for constructing edges you would have

```
g.SetEdge(g.NewEdge(g.Node(i), g.Node(j)))
```

**Comment by kortschak** [comment]
An approach that we can use to keep the current easy node addition while using the API above would be to add a function to graph, 

```
func graph.AddNodeTo(dst graph.NodeAdder) {
    id, ok := dst.NewNodeID()
    if ok {
        dst.AddNode(g.Node(id))
    }
}
```

I'm still not sure about where to put the Node method though. It seems like (from #448) that having it in `graph.Graph` would be good, but that would require that `graph.NodeAdder` would need to embed `graph.Graph`.

**Comment by kortschak** [comment]
An alternative interface would be this. I think this is the best so far.

```
// NodeIDer wraps the NodeID method.
type NodeIDer interface {
    // NodeID returns a Node with the given ID if possible. A
    // nil Node will be returned if no Node exists or can be created.
    // If a non-nil Node is returned that is not already in the graph
    // NodeID will return true for new and the Node must be
    // added to the graph before use.
    NodeID(id int64) (n Node, new bool)
}
```

**Comment by kortschak** [comment]
BTW What cost do you see to adding the interface above? This would not be added into `NodeAdder`.

**Comment by mewmew** [comment]
> BTW What cost do you see to adding the interface above? This would not be added into 

Before doing this, I would like to understand better the *use cases* when you need to specify the ID. It seems like a very internal aspect of the design of each data type (and whether it is sparse or dense depends on that).

Is this only intended to be used for test cases? If so, I don't think this belongs in the standard interface, etc. Simply to keep godoc thin and help *new users* get more easily acquainted with the Gonum graph API. If we do the same thing in more than one way, it will be more difficult to new users. This is the main cost I see.

**Comment by kortschak** [comment]
This is not intended for test cases; we manage to be completely agnostic to node ID at creation there. An example use case would be where the algorithm creates pairs of nodes with signed ID (this is linked in https://github.com/gonum/gonum/issues/230#issuecomment-455677945). It's possible to do these without using the ID directly, so this could be thought of as a optimisation and internal to the algorithm, but not necessarily to the graph implementation.

**Comment by mewmew** [comment]
> It's possible to do these without using the ID directly, so this could be thought of as a optimisation and internal to the algorithm, but not necessarily to the graph implementation.

If it is still possible without using the ID directly, then I think lets keep it as is. If for specific use cases, implementing e.g. `NodeWithID` makes a measurable impact on performance then we can do it on a case by case basis. So, as far as formalization goes, I maintain the position that this does not need a standard interface.

**Comment by kortschak** [comment]
OK. Are we happy to closet this then?

**Comment by mewmew** [comment]
> OK. Are we happy to close this then?

Sure. @kkdd?

**Comment by kkdd** [comment]
I agree. Than you.

**Comment by kortschak** [comment]
OK, we'll close this then. It can be a new issue if it comes up again.
