### ISSUE TITLE
Retrieve backing data from column

### ISSUE THREAD

**Issue by buyology** [gonum/gonum#232]
If I create a matrix like so:

```go
m := mat.NewDense(5, 2, []float64{
    1, 2,
    1, 4,
    2, 6,
    3, 8,
    3, 10,
})
```

and print a view of the column using `Formatted`:
```go
fmt.Println(mat.Formatted(m.ColView(0)))
```

it looks alright:

```
⎡1⎤
⎢1⎥
⎢2⎥
⎢3⎥
⎣3⎦
```

However, if I try to retrieve the underlying data, it seems to be a partial view of the whole original matrix?
```go
fmt.Println(m.ColView(0).(*mat.VecDense).RawVector().Data)
```

```
[1 2 1 4 2 6 3 8 3]
```

Is this expected behaviour?

What's the canonical way of retrieving a single cols data?

**Comment by btracey** [comment]
This is the expected behavior. It is how the data is stored, which is what a `View` is.

You can either use `(*Dense).ColView` to actually get a view like you're seen, or `mat.Col` to extract it into a `[]float64`, and get only the data you would like.

**Comment by buyology** [comment]
Alright, got it. 

Btw, what's the best place for finding usage examples?

(I tend to always end up at the `mat64` docs/examples when searchin and it seems that some stuff in the api have changed a bit)

**Comment by btracey** [comment]
Do you have any specifics? All of the examples should be accurate (as checked by `go test`).

**Comment by kortschak** [comment]
The examples in github.com/gonum/mtraix/mat64 exist in the gonum.org/v1/gonum/mat package as well (updated if needed). Follow the [link from the README](https://godoc.org/gonum.org/v1/gonum/) and navigate to the desired package.
