### ISSUE TITLE
travis: check code generation for dot parser in graph/formats/dot/internal

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#24]
This requires that gocc and make be installed on the builder (and possibly other things that may not be present).

**Comment by mewmew** [comment]
For inspiration, see https://github.com/graphism/dot/blob/master/.travis.yml

**Comment by kortschak** [comment]
Please send a PR. It would probably be good if the PR also had a `go generate` hook in "graph/formats/dot/internal" so we can pretend that make doesn't exist.

**Comment by mewmew** [comment]
> Please send a PR. It would probably be good if the PR also had a go generate hook in "graph/formats/dot/internal" so we can pretend that make doesn't exist.

I'll take a look at it during the following week.

**Comment by mewmew** [comment]
> I'll take a look at it during the following week.

Time flies, especially when its sunny outdoors :)

Just to let you know, I'll be heading out for a trek and should be back towards early August. Will get back to coding then, if not before.

Have a lovely summer.
