### ISSUE TITLE
blas/gonum: 6c3eea introduced inconsistency to ?gemv comments

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#243]
The change to comments for ?gemv in 6c3eea8080f72373ec13c659363559501f3a4cc0 is inconsistent with others, and also makes the netlib generation check fail.

Do we want to revert this comment formatting change or propagate it around the entire blas method set?

/cc @vladimir-ch @btracey

**Comment by vladimir-ch** [comment]
Do you remember what you meant with "this comment formatting change", @kortschak ? Did you refer to the alignment of "if"?

**Comment by kortschak** [comment]
Yes, I think so. I just wound both repositories back to that period and did the check and netlib was using the ragged if alignment. There also appears to be an inconsistency in the use of commas after the first clause of those kinds of enumerations. For example, [Dtrmm](https://godoc.org/gonum.org/v1/gonum/blas/gonum#Implementation.Dtrmm) has commas for all lines, [Dgemv](https://godoc.org/gonum.org/v1/gonum/blas/gonum#Implementation.Dgemv) uses none, and [Ztbsv](https://godoc.org/gonum.org/v1/gonum/blas/gonum#Implementation.Ztbsv) not on the first line.

I'm leaning towards the aligned form without commas for readability, but I'm don't hold this strongly.
