### ISSUE TITLE
gonum: consider making gonum.org/v1/gonum a Go package

### ISSUE THREAD

**Issue by sbinet** [gonum/gonum#260]
right now, there is no `.go` file directly under `gonum.org/v1/gonum`.

beginners trying to install `gonum` with a naive `go get` are met with:

```sh
$> go get gonum.org/v1/gonum
can't load package: package gonum.org/v1/gonum: no Go files in /home/binet/dev/go/gocode/src/gonum.org/v1/gonum
```

`glide` even tells a more confusing story:
```sh
$> glide get gonum.org/v1/gonum
[INFO]    Preparing to install 1 package.
[INFO]    Attempting to get package gonum.org/v1/gonum
[INFO]    --> Gathering release information for gonum.org/v1/gonum
[INFO]    --> Adding gonum.org/v1/gonum to your configuration
[INFO]    Downloading dependencies. Please wait...
[INFO]    --> Fetching updates for github.com/chewxy/gorgonia
[INFO]    --> Fetching updates for github.com/spf13/viper
[INFO]    --> Fetching updates for github.com/spf13/cobra
[INFO]    --> Fetching updates for gopkg.in/cheggaaa/pb.v2
[INFO]    --> Fetching gonum.org/v1/gonum
[INFO]    --> Fetching updates for github.com/chewxy/lingo
[INFO]    --> Fetching updates for github.com/pkg/errors
[INFO]    --> Fetching updates for github.com/olekukonko/tablewriter
[WARN]    Unable to checkout gonum.org/v1/gonum
[ERROR]    Update failed for gonum.org/v1/gonum: https://gonum.org/v1/gonum Not Found
[ERROR]    Failed to checkout packages: https://gonum.org/v1/gonum Not Found
```

we probably should just stick a `gonum.go` file with some documentation to make all of this disappear.

**Comment by kortschak** [comment]
This has been discussed somewhere. For there to be a package, there should be a function that it provides, not just documentation. I'd rather this didn't happen. The install docs do say install `gonum.org/v1/gonum/...` (note that `go get gonum.org/v1/gonum` with a placeholder can lead to more confusing results - gocode will not see any of the packages since they must be built, and that `go get` invocation would not do that).

**Comment by sbinet** [comment]
you can put only documentation:

https://github.com/go-hep/hep/blob/master/hep.go
https://godoc.org/go-hep.org/x/hep

the issue you raise about `gocode` might indeed happen, I guess.
but IMHO, what we should try to strive for is a smooth installation for beginners. the `gocode` issue is for already Go savvy people.

(we could also arange for `gonum.org/v1/gonum` to `_ import` all the packages under `gonum.org/v1/gonum`, making `go get gonum.org/v1/gonum` equivalent to `go get gonum.org/v1/gonum/...`. I wouldn't recommand it though.)

anyways. It's just something I felt we could easily improve upon.
People switching over from `Python` or `R` are not familiar the `...` ellipsis, they expect that `go get gonum` will work as _e.g._ `pip install numpy`.

**Comment by tribeclickgh** [comment]
+1 to a more go friendly approach. Right now I dont even know how to add gonum and its subpackages to glide.

The package should be installable the way the community is used to do so. Assuming that people will read the docs and apply different rules than the ones they are used to for a particular package is a naive assumption that will hurt adoption (remember compiling python numeric libraries and dealing with C flags before conda arrived? I do).

**Comment by kortschak** [comment]
There are a couple of issues here. The first is that gonum.org/v1/gonum
is not a package, it is a filesystem hierarchy. It provides no
functionality other than collecting a group of packages that are
associated on the basis of their authors' identities, nothing more. If
there is a Go functionality that is needed, it should be imported and
pinned. The second is that it is conventional to include collections in
this format. Please take a look at golang.org/x/*/; none of these hold
a Go source file, but everyone of them holds a collection of packages.
Here again, the actually used packages are pinned if needed, not a
marker package at the root of the filesystem.

**Comment by johnmcilwain** [comment]
I tried w/o really knowing what I was doing to get this to work.  I am sure there are many ways to get this to work...but this did get a chart to show for me.

Download libraries (http://www.gonum.org/post/introtogonum/)
go get -u -t gonum.org/v1/gonum/...

How to reference in your go code:
import "gonum.org/v1/plot"

I wonder if the "-u -t" option (above) would have allowed me to get this to work from github:
    import "github.com/gonum/plot"
I didn't try this...

**Comment by tribeclickgh** [comment]
thanks for the clarification @kortschak . In that case, how would be the appropriate way of using gonum with any package manager, lets say, with glide?

**Comment by kortschak** [comment]
That's a difficult thing for me to answer since I don't use glide.

However, if I were in your situation and the docs don't explain it adequately ask on the chat channel and file an issue requesting more information for this case to be added to the docs. At the same time, I'd look at how other projects using glide handle golang.org/x/ package pinning.

**Comment by btracey** [comment]
To expand @tribeclickgh , at least I'm partly confused because our packages work fine with `go get`. I haven't used glide, but why wouldn't it be able to get packages that `go get` can?

**Comment by erwinvaneyk** [comment]
As this is the top search result for this issue: to use gonum with Glide you will currently need to add the repo location. For example:
```yaml
# ...
- package: gonum.org/v1/gonum
  version: 996b88e8f8941c9defdbb338bea5e239a230e742
  repo:    git@github.com:gonum/gonum
# ...
```

**Comment by helinwang** [comment]
Temporary solution for glide users:
```
glide mirror set https://gonum.org/v1/plot https://github.com/gonum/plot
```

**Comment by kortschak** [comment]
With the advent of `debug.ReadBuildInfo` there is actual functionality that could go in a "gonum.org/v1/gonum" package; `gonum.Version()` for go1.12 users building with modules. I have tried this and it works (testing is difficult since you need to be outside the module for it to work). I'm happy to send this, but what do we want to have in the "doc.go"?

**Comment by btracey** [comment]
The text on the front page of the website is a decent place to start. Maybe later we could add something about navigating the packages.

**Comment by kortschak** [comment]
#877 closed this.
