### ISSUE TITLE
stat/distmv: Normal should use upper rather than lower

### ISSUE THREAD

**Issue by btracey** [gonum/gonum#269]
Normal currently stores the lower triangular component of the Cholesky decompostion. This is silly, since `Cholesky` computes the upper triangular decomposition, so constructing the lower triangular component is extra work.

**Comment by kortschak** [comment]
Is this still true? I don't see any reference to the lower triangle in `dismv.Normal`.

**Comment by btracey** [comment]
Yes, this has been fixed.
