### ISSUE TITLE
mat: Add Cholesky.RawU()

### ISSUE THREAD

**Issue by btracey** [gonum/gonum#270]
This is a suggestion to add 
```
// RawU returns the direct Triangular matrix used to store the Cholesky decomposition of
// the original matrix A. If returned matrix is modified, the decomposition is invalid and should
// not be used.
func (c *Cholesky) RawU() Triangular
```

Then, types like `Normal` can save the work of extracting the decomposition. For example, `*Normal.transformNormal` can have
```
dstVec.MulVec(n.chol.RawU().T(), srcVec)
```
and the entire `lower` field can be eliminated altogether, saving time, memory and code complexity.

**Comment by kortschak** [comment]
SGTM
