### ISSUE TITLE
mat: Add Diagonal type

### ISSUE THREAD

**Issue by btracey** [gonum/gonum#282]
We currently have `func NewDiagonal(n int, data []float64) *SymBandDense`. The downside to this is that `*SymBandDense` cannot implement `Triangular`, while `Diagonal` can. This means `Diagonal` cannot be used as a triangular matrix, even though it is.

**Comment by btracey** [comment]
There is one tricky issue with this, which is that a `Diagonal` is both `Upper` and `Lower`, which is currently impossible to express.

**Comment by kortschak** [comment]
A helper could be provided here that is `func(d Diagonal, upper bool) Triangular`.

**Comment by vladimir-ch** [comment]
It looks like this could be closed.

**Comment by kortschak** [comment]
Agreed.
