### ISSUE TITLE
Use of golang.org/x/exp/rand instead of math/rand/

### ISSUE THREAD

**Issue by ctessum** [gonum/gonum#346]
For example in [here](https://github.com/gonum/gonum/blob/master/stat/distmv/normal.go#L10). Is there a continuing reason for this? The two packages appear to be the same but one is in the standard library.

**Comment by ctessum** [comment]
Never mind, I see that there is already discussion about this (#228, #301).

However, the current state of thing is not convenient because goimports will tend to import the wrong version.

**Comment by btracey** [comment]
Yes, it's not ideal. I made a comment about this on https://github.com/golang/go/issues/15471

**Comment by btracey** [comment]
But, having a better and faster random number generator is more important.
