### ISSUE TITLE
mat: {LU,LQ,QR}.{Solve,SolveVec} have confusing signatures

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#364]
I don't use these often, so the misapprehension here has not been corrected until now when I look at dealing with `Vector` parameters. I had always assumed the `trans` parameters here were for the input parameters, but the docs show that it is for the transposition state of the matrix represented by the factorisation. To address this, I would like to propose that we change the signature to the following model:

```
Solve(trans bool, dst *Dense, b Matrix)
SolveVec(trans, dst *VecDense, b Vector)
```

Which would appear as, e.g. `a.Solve(true, x, b)` which more closely reflects the A'X = B or AX = B of the mathematics.

**Comment by btracey** [comment]
I don't know... I understand the argument, but it's always the case that the destination is the first argument. It seems to me breaking that invariant is the worse sin here.

**Comment by kortschak** [comment]
Yes, this is why it also changes `m`=>`dst` (even without the reordering I think that might be worthwhile; the docs are not quite as clear as they could be.

**Comment by kortschak** [comment]
I happy with things how that are now that the `Solve` methods have been renamed.
