### ISSUE TITLE
mat: shadow detection misses some cases

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#377]
I have made some optimisation-driven mistakes in the checks for shadow detection; it is the case that these checks for many cases are only made when all input values are `Raw*` types, this means that we are not doing what we say in the documentation, that all `Raw*` types are checked.

**Comment by btracey** [comment]
Should I look into somehow integrating this into `ListTest` so that we can test that the right overlaps panic?

**Comment by kortschak** [comment]
I don't think this is API stability. And I think I recall that I well through that check whether there were any more cases. I don't think there are.
