### ISSUE TITLE
diff: Derivative Performance

### ISSUE THREAD

**Issue by SellJamHere** [gonum/gonum#380]
I created benchmarks comparing the serial and concurrent Derivative function implementations. It seems the serial implementation will always be faster. 

Here is the benchmark result:
```
# go test -benchtime=10s -bench=.
BenchmarkDerivativeSerial-8          	200000000	        64.5 ns/op
BenchmarkDerivativeConcurrent-8      	10000000	      1937 ns/op
BenchmarkDerivative2ndSerial-8       	100000000	       113 ns/op
BenchmarkDerivative2ndConcurrent-8   	 5000000	      2865 ns/op
PASS
ok  	gonum.org/v1/gonum/diff/fd	69.481s
```

It seems the concurrent [Derivative](https://github.com/gonum/gonum/blob/master/diff/fd/derivative.go#L17) function merely calculates the differential between each `Stencil` point (sans origin) in a separate goroutine. Unfortunately, there are only two points in the first-order approximations, and three points in the second-order. If there were many points, the concurrent implementation could potentially enhance performance. As it is, there is a large overhead for the concurrent path, as we create a `sync.Waitgroup` and lock/unlock a `sync.Mutex` for each of the points. I propose we remove the concurrent path, and always use the unencumbered sequential calculation.

The benchmark code is as follows:
```
func BenchmarkDerivativeSerial(b *testing.B) {
	// run the Derivative benchmark b.N times
	for n := 0; n < b.N; n++ {
		Derivative(xSquared, 10, &Settings{Concurrent: false})
	}
}

func BenchmarkDerivativeConcurrent(b *testing.B) {
	// run the Derivative benchmark b.N times
	for n := 0; n < b.N; n++ {
		Derivative(xSquared, 10, &Settings{Concurrent: true})
	}
}

func BenchmarkDerivative2ndSerial(b *testing.B) {
	// run the Derivative benchmark b.N times
	for n := 0; n < b.N; n++ {
		Derivative(xSquared, 10, &Settings{Formula: Forward2nd, Concurrent: false})
	}
}

func BenchmarkDerivative2ndConcurrent(b *testing.B) {
	// run the Derivative benchmark b.N times
	for n := 0; n < b.N; n++ {
		Derivative(xSquared, 10, &Settings{Formula: Forward2nd, Concurrent: true})
	}
}
```

**Comment by btracey** [comment]
Thanks for the benchmarks. There are two misconceptions. 1) It's not true that there are only two or three points. That is the case in our current stencils, but there are bigger stencils that can be used. 2) It's true that there is significant overhead, but if the function is non-trivial then doing `Derivative` with concurrency enabled can easily be faster. I agree that if your function is `xSquared` you shouldn't, but if you have a function that takes 20s to evaluate (common for me), then concurrency speeds it up. The concurrency should stay in.

That said, as @kortschak mentions in #381 , there are ways to improve the existing code. You can see the current code in `Gradient` for example.

**Comment by SellJamHere** [comment]
Great points. I didn't consider larger stencils or non-trivial functions. I'll take a look at `Gradient` for inspiration.
