### ISSUE TITLE
matrix/mat64: QR and LQ unnecessarily panic with ErrShape

### ISSUE THREAD

**Issue by vladimir-ch** [gonum/gonum#39]
There is no mathematical reason to limit these factorizations to only certain matrix shapes, and panic otherwise. The underlying Lapack routines (Dgeqrf and Dgelqf) handle any input matrix size.

**Comment by vladimir-ch** [comment]
I will close this. The Lapack functions do support any matrix size but our API can return L and R only truly triangular, not trapezoidal.

**Comment by kortschak** [comment]
Following this up. Is there a reason to or not to include a trapezoidal matrix type?

**Comment by btracey** [comment]
Are they that useful? The higher level libraries in Lapack, (DGELS for example), avoid the factorizations that have the trapezoidal outcomes. That was a sign to me that maybe they don't need to be supported very well.
