### ISSUE TITLE
Proposal: integrate an interesting package to gonum

### ISSUE THREAD

**Issue by dongweigogo** [gonum/gonum#399]
I just found an very interesting package [calculus](https://github.com/TheDemx27/calculus)
As it says, "The one and only Golang library for single variable differentiation and integration."
I feel it would be very helpful to integrate this package to gonum.

**Comment by btracey** [comment]
A full symbolic tool is a lot of work to make good. I think we'd only integrate that if we had a team committed to making it good. 

We do have
https://godoc.org/gonum.org/v1/gonum/diff/fd
https://godoc.org/gonum.org/v1/gonum/integrate
https://godoc.org/gonum.org/v1/gonum/integrate/quad
