### ISSUE TITLE
all: harmonise APIs across all packages

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#4]
There is a low level of variety in the conventions we use across the different repos. We should take the opportunity when merging repos and the concomitant breakage that comes with that to fix these into a smaller number of consistent conventions.

For example (feel free to add more):

- [x] https://github.com/gonum/matrix/pull/436
- [x] https://github.com/gonum/stat/issues/179
- [x] https://github.com/gonum/stat/pull/170
- [x] https://github.com/gonum/matrix/issues/403 This is obviously not correct, but I cannot remember/find the correct item.
- [x] #101
- [x] #102

**Comment by btracey** [comment]
There are a bunch of API changes we've discussed. Would you like me to add them here, or should they be different issues?

**Comment by kortschak** [comment]
This is an aggregator for issues that exist in the other repos. If you have issues that exist (or you are writing) and need to be addressed after the merge, then this is the right place to remind us about them. I avoided writing issues here because there is nothing code here to have issues yet.

I don't recall the exact changes, but if they exist in particular repo, write the issue there and link here. If they are general things, write a new issue here.

**Comment by btracey** [comment]
Using this to keep track of the major changes

- [] Moved import paths to gonum.org/v1/gonum/pkg
- [] Moved c-wrappers for BLAS and Lapack out of main repository into gonum.org/v1/netlib/pkg
- [] Plot still it's own repository (not a change, but important to note)

**Comment by btracey** [comment]
Looks like these are all done. Agreed @kortschak ?

**Comment by kortschak** [comment]
Seems so.
