### ISSUE TITLE
Proposal: implement simpson's rule

### ISSUE THREAD

**Issue by millerick** [gonum/gonum#400]
It's been a long while since I've implemented numerical methods, and I wanted to get back to my undergrad roots.  I was looking at the `integrate` portion of the project, and found it odd that there is a very basic trapezoidal rule implemented, robust quadratures, and nothing in between.  Would it be acceptable to add simpson's rule to the integrate package?

**Comment by sbinet** [comment]
Sure, SGTM :)

**Comment by kortschak** [comment]
Closed by #1107.
