### ISSUE TITLE
mat pseudo-inverse

### ISSUE THREAD

**Issue by Aegnor117** [gonum/gonum#409]
Is there a way to compute the inverse of a n by p matrix when n!=p.
Like the moore penrose pseudo inverse or similiar?
I didn't find a pseudo inverse function in the mat package.
Is there a function or a way to use other functions in order to achieve the pseudo inverse?

Thanks in advance.

**Comment by btracey** [comment]
There is no explicit function at the moment. There are ways within the package to compute it. Do you specifically need to see the pseudoinverse matrix for some reason? For instance, in many cases the pseudo-inverse used to solve an overdetermined linear system. This functionality is already provided with the `Solve` method(s)

**Comment by Aegnor117** [comment]
I have a (n,p) matrix A and a (1,p) matrix B. I need to compute and see the following matrix :
C = Transpose[ B x Inverse(A)].

**Comment by kortschak** [comment]
c = [ b Inv(A) ]' -> c = Inv(A)' b' -> A'c = b' which means c can be obtained from a solve.

**Comment by Aegnor117** [comment]
How would you write the code then?
For now i have the following solution :

a := mat.NewDense(2,4,data)
atrans:=mat.Transpose{a}

at :=mat.NewDense(4,2,nil)

for i:=0;i<4;i++{
for j:=0;j<2;j++{
at.Set(i,j,atrans.At(i,j))
}
}

var ata mat.Dense
var aat mat.Dense
var aatinv mat.Dense
var apinv mat.Dense
var atainv mat.Dense
var apinv2 mat.Dense

ata.Mul(at,a)
aat.Mul(a,at)

if mat.Det(&ata) ==0 {
aatinv.Inverse(&aat)
apinv.Mul(at,&aatinv)
} else{
atainv.Inverse(&ata)
apinv.Mul(&atainv,at)
}

don't know how mathematicaly good it is though.

**Comment by btracey** [comment]
```
a := mat.NewDense(n,p)
// Fill in A
b := mat.NewVecDense(p)
// Fill in B
var c mat.VecDense
err := c.SolveVec(A.T(), b)
if err != nil {
    // handle error
}
```

**Comment by btracey** [comment]
Actually, I'm not sure about the `A.T()` part (maybe it should be just `A`), because your original expression doesn't match dimension-wise, but the above is the right idea

**Comment by kortschak** [comment]
I think we have answered this. If you disagree, please reopen.
