### ISSUE TITLE
floats: Nearest() produces strange results with NaNs

### ISSUE THREAD

**Issue by aleh-null** [gonum/gonum#413]
When running this:
```
a := []float64{math.NaN(), 1, 2, 3}
b := 2
c := floats.Nearest(a, b)
```
Nearest returns 0, where I would expect 2. 
Since it's a simple matching, NaN can be also matched to a first occurrence in a slice like 
```
a := []float64{math.NaN(), 1, 2, 3}
b := math.NaN()
c := floats.Nearest(a, b)
// c == 0
```

**Comment by kortschak** [comment]
I agree that the current behaviour is incorrect, but I don't think there is enough information here to discuss what the correct behaviour should be (the issue template is here to help with that).

I think that if b is NaN, the returned index should always be -1, but that is open for discussion; we are using a term nearest which is poorly defined and could either required that the distance between NaN and NaN is 0 or NaN (I lean towards the latter).

**Comment by kortschak** [comment]
The other question to address here is how queries of  +Inf and -Inf are handled. Is Inf "nearer" to Inf than to any other number?

Also NearestWithin needs to be addressed for ranges that include NaN, or are (-Inf,+Inf) or when the query is NaN.

**Comment by aleh-null** [comment]
First of all sorry for not following the template. 
I agree that the distance between NaN and NaN should be NaN. With regards to the Infs, Inf-Inf is not a valid operation and Inf+Inf is Inf, which gives us NaN or Inf as a distance metric. However, I feel it's also not a proper measure for Infs or NaN.
To be more practical, one can restrict `b` to be finite and panic otherwise:
```
if math.NaN(b) || math.IsInf(b, 0) {
    panic("floats: b is not finite")
}
```
Same can be done for `a`. I actually like the way R handles similar situations. A lot of base functions have a logical value indicating whether NaN values should be stripped before the computation proceeds.

> I think that if b is NaN, the returned index should always be -1 (or 0 as is the case now)
Not sure that I follow this one, but it always return 0 when `b` has a NaN, which is also wrong. Here is an example:
```
a := []float64{1, math.NaN(), 2, 3}
b := math.NaN()
fmt.Println(floats.Nearest(a, b))
```
I also think that it would be much harder to discover errors if -1 returned in comparison to panic or error.

**Comment by kortschak** [comment]
I don't think that `Nearest` should ever panic, and NaN can be handled under the current documentation with little lawyering; NaN is equally distant from all values, so the first element is the best match (I disagree that your example is wrong in the comment above).

I propose the following special case behaviours for `Nearest`:

1. query is NaN => index is 0
2. query is +Inf =>  index is for first instance of largest positive value
3. query is -Inf =>  index is for first instance of largest negative value
4. query is finite => index is for closest finite element, or sign-matched Inf element if there is no finite element, or any Inf if not sign-matched.
5. NaN elements only chosen if no non-NaN value is present (except in case 1. above).

For `NearestWithinSpan`:

1. NaN including or  (-Inf,Inf) range will always return -1.
2.  (-Inf,-Inf) or (Inf,Inf) range will always return 0.
3. NaN query will always return -1.

**Comment by kortschak** [comment]
I'm wondering about the -1 index return from `NearestWithinSpan` too. It seems odd; the "within" part of the name suggests it should be there, but the first sentence of the doc comment suggests that out of range queries should return either the low and high span values:

>NearestWithinSpan return the index of a hypothetical vector created by Span with length n and bounds l and u whose value is closest to v.

From this, I would expect `NearestWithinSpan(n, l, u, v)` to behave identically to `Nearest(Span(make([]float64, n), l, u)), v)`.

/cc @btracey

**Comment by btracey** [comment]
SGTM for `Nearest` with the clarifier that +inf is "nearest" to +inf .

For NearestWithinSpan, I think that you're right that we want it to behave identically to the `Nearest` call. This may mean we need to better specify the behavior of NearestWithinSpan. Currently the documentation says that the first element will be `l` and the last will be `u`. In particular, this should mean that `floats.Span(s, math.Inf(-1), math.Inf(1))` returns `[-inf, NaN, NaN, NaN, inf]` (although it doesn't actually). The question is what `Span` should do with `inf` and `NaN` values. In particular, I would think that (-inf, inf) should return all NaNs, and (c, Inf) returns c and then a bunch of Infs. This then matches your suggested behavior for `NearestWithinSpan`

**Comment by kortschak** [comment]
Can we then rename `NearestWithinSpan` to `NearestForSpan`? (We'll get the name right eventually I guess).

**Comment by btracey** [comment]
`NearestForSpan` sounds reasonable.

It could have been in point 2, I just wanted to clarify "positive" meant [0, inf] and not [0, inf). Though, shouldn't it return the index of the largest value (even if not positive)?

**Comment by kortschak** [comment]
Positive includes inf in that case. Revising the test:

2. query is +Inf => index is for first instance of most positive value (may be negative)
3. query is -Inf => index is for first instance of most negative value (may be positive)


Also, the (-inf, inf) case for span is unsettling. An alternative would be half -inf and half inf for even lengthed slices and the same but with a central 0 for odd lengthed slices.

**Comment by btracey** [comment]
I think that sounds reasonable

(-inf, inf) -> [-inf -inf 0 inf inf]
(-inf, 6) -> [-inf, -inf, -inf, -inf, 6]
(6, inf) -> [6, inf, inf, inf, inf]

I would suggest that
(6, NaN) -> [6 NaN NaN NaN NaN]
(NaN, 6) -> [NaN NaN NaN NaN 6]

The reason I suggest that behavior for NaN is it means we can maintain the invariant that `l` is the first element and `u` is the last element. This behavior doesn't necessarily follow from "divide the space and add" due to floating point rounding. Thus, with this NaN behavior there are no exceptions to that invariant, and only one way that imagining "divide and add" will trick you (namely the (-inf, inf) case). This would mean that `NearestWithinSpan(10, NaN, 6, 2)` returns `9` (thus 6 is the nearest value), which doesn't seem unreasonable.

I would also suggest while we're fixing this that we also change to `NearestIdx` and `Nearest`. This would match `Max` and `MaxIdx`.
