### ISSUE TITLE
Proposal: graph: support g6 encoding/decoding

### ISSUE THREAD

**Issue by trelore** [gonum/gonum#431]
Support encoding/decoding of [g6 format](https://users.cecs.anu.edu.au/~bdm/data/formats.txt).

[House of Graphs](https://hog.grinvin.org/) list a lot of definitively interesting graphs. The website provides some large lists of graphs only in the g6 format, for example the [trees](https://hog.grinvin.org/Trees) section in the 'Graphs meta-directory'.

I'd also like to implement this

**Comment by kortschak** [comment]
This SGTM as discussed previously.

I would maybe wait for #424 to go in unless you can be confident that there won't be too much semantic conflict (though I was pleasantly surprise while putting together that set of changes that very few changes were required in encoding - only in the marshaling code). If you want to move that ahead more quickly, please feel free to contribute to the review of that PR.

**Comment by kortschak** [comment]
#424 is in now, so please go ahead with this when you are ready.

**Comment by kortschak** [comment]
This was closed by #906.
