### ISSUE TITLE
blas/gonum: bad index in Dgbmv

### ISSUE THREAD

**Issue by vladimir-ch** [gonum/gonum#436]
In Dgbmv there is the following computation of the upper bound `u` on the valid column index in the row `i`:
```
ld := min(m, n)
for i := 0; i < min(m, n+kL); i++ {
    u := min(nCol, ld+kL-i)
}
```
The offset is where the ~~A[i,n]~~ A[0,n] element would be in the band format so it seems wrong that `u` depends on `m` through `ld`. I think the formula should be simply
```
u := min(nCol, n+kL-i)
```

This is also supported by the tests for Zgbmv in #435 . If I adapt the tests there for `float64`, I get failures that go away with the suggested fix.

**Comment by btracey** [comment]
That sounds right. I agree `u` shouldn't depend on `ld`. When you push a fix, could you also add a test that exposes the problem? It sounds like you already have one ready.
