### ISSUE TITLE
proposal: add ParseFloat64(s string) (v, w float64, err error)

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#44]
We provide weighted value support for tests etc in stat, but there is no handling for textual representation of "NA" provided by stdlib. So I propose we add in either stat or floats a `ParseFloat` or `Parse` respectively that handles this.

Edited to incorporate suggestion below to allow a user-provided na string.

Assume in floats.
```
// Parse converts the string s to a float64 in v. If s equals na, w is returned as 0, otherwise 1.
func Parse(s, na string) (v, w float64, err error) {
    if s == na {
        return 0, 0, nil
    }
    v, err = strconv.ParseFloat(s, 64)
    if err == nil {
        w = 1
    }
    return v, w, err
}
```

This would then be used like so, e.g. single column data:
```
var vals, weights []float64
sc := bufio.NewScanner(r)
for sc.Scan() {
    v, w, err := floats.Parse(sc.Text(), "NA")
    if err != nil { ... }
    vals = append(vals, v)
    weights = append(weights, w)
}
err := sc.Err() ...
mean := stat.Mean(vals, weights)
```

**Comment by btracey** [comment]
I see the appeal of this function, but I think it's too special case. I think it should be `Parse(s, na string)`, where "na" is the representation of NA in the code. I've seen such data represted as "NA", "na", "N/A", "n/a", "NaN", "", " ", and possibly more. This is enough variation to just ask the user to provide the matching string.

I also don't really like the name `Parse`. It's true, but it has more semantic content than that in also setting the weight.

**Comment by kortschak** [comment]
Fair enough for the `na` string parameter. Can we expect that it is always the same in a data set (I think so, otherwise they can copy/paste and add a more flexible assessor.

I think it is parsing. It's not setting the weight, it's providing a value that indicates whether the string was NA. How the user uses that float64 is up to them.

**Comment by kortschak** [comment]
BTW "NaN" should never be used for NA. They deserve what they get there.

**Comment by btracey** [comment]
I don't disagree, but I have had to deal with those data files.

**Comment by btracey** [comment]
Maybe `ParseNA` then. It parses and also returns if not available.

**Comment by kortschak** [comment]
What is the signature of `ParseNA`?

**Comment by kortschak** [comment]
*ping*

**Comment by btracey** [comment]
The same that you propose, just with the different name.

**Comment by kortschak** [comment]
Sorry, from the text it sounded like `ParseNA(s string) (float64, bool)`.

`ParseNA` doesn't capture the intention of the function. I would suggest from things like `ParseFloat64WithNA`. `ParseWithNA` or similar.

**Comment by btracey** [comment]
I like `ParseWithNA`
