### ISSUE TITLE
meta: issues with vgo

### ISSUE THREAD

**Issue by sbinet** [gonum/gonum#454]
this is a "meta" issue to document all the known issues we may have to deal with to get support for `vgo`:

- https://github.com/golang/go/issues/23970: x/vgo: allow cross-module internal imports based on import path prefix
- https://github.com/golang/go/issues/23960: x/vgo: module path contains non-final version element v1

**Comment by pwaller** [comment]
If I run go install on a package which imports `gonum.org/v1/gonum/stat/distmv`, I get this:

```
	import "gonum.org/v1/gonum/stat/distmv" ->
	import "gonum.org/v1/gonum/mat" ->
	test ->
	import "gonum.org/v1/netlib/blas/netlib": cannot find module providing package gonum.org/v1/netlib/blas/netlib
```

If I try to run `go get`, I get a different error:

```
$ GO111MODULE=on go get gonum.org/v1/gonum/mat
go: finding gonum.org/v1/gonum/mat latest
go: finding gonum.org/v1/gonum latest
go get gonum.org/v1/gonum/mat: missing module for import: gonum.org/v1/gonum@v0.0.0-20180722074715-72e79ca98526 provides gonum.org/v1/gonum/mat
```

Anyone figured out this issue?

**Comment by sbinet** [comment]
the first error is something I wanted to investigate.
I *think* it comes from this:

https://github.com/gonum/gonum/blob/023b8e605abb7af160043f692d4313e058bd8a5a/mat/cblas_test.go#L5

```go
// +build cblas

package mat

import (
	"gonum.org/v1/gonum/blas/blas64"
	"gonum.org/v1/netlib/blas/netlib"
)

func init() {
	blas64.Use(netlib.Implementation{})
}
```

where `go mod` doesn't completely follow the build tag (it shouldn't look at that file when no `cblas` build tag is defined.)

or perhaps it's just that we need to add a `go.mod` file to that `gonum.org/v1/netlib` repo ?

**Comment by sbinet** [comment]
or pehaps it's because the _module_ `gonum.org/v1/gonum` needs the _module_ `gonum.org/v1/netlib` which itself *also* needs `gonum.org/v1/gonum` ?

**Comment by kortschak** [comment]
I would like to find out from golang-dev or golang-nuts how to deal with this. The error does come from the cblas test tagged code. I can see why mod does not look at tags, but I'd really rather not require that users pull netlib just to get other things we provide.

**Comment by pwaller** [comment]
I'm also seeing that this seems to work for `go install ./cmd/mybinary` but not `go mod -sync`. I misspoke earlier, I didn't realise I was running `go mod -sync` rather than `go install` as I thought.

**Comment by sbinet** [comment]
@kortschak yeah... this whole business of build-tags in a Go Module context is a bit murky.

**Comment by pwaller** [comment]
@kortschak: Are you going to make the post? I'm tempted to, to golang-dev, with subject "go modules and build tags", linking to this issue, but want to avoid a race with you - and you might be able to explain it better ;-)

**Comment by kortschak** [comment]
I'll leave it to you if you don't mind.

**Comment by pwaller** [comment]
[go-dev thread](https://groups.google.com/forum/#!topic/golang-dev/b0_xwKr5db4) and [go issue](https://github.com/golang/go/issues/26632).

**Comment by pwaller** [comment]
Hmm. This morning I'm unable to reproduce the issue. Is anyone else currently hitting this? If not, I will close the issue on the go tracker.

Unfortunately I don't have a good explanation of why it now works for me. It may be that clearing the mod cache fixed it.

**Comment by kortschak** [comment]
SGTM

**Comment by sbinet** [comment]
SGTM as well.
