### ISSUE TITLE
mat: document that EigenSym decomposition returns values in ascending order

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#461]
See https://github.com/gonum/gonum/pull/458#discussion_r181452960.

**Comment by kortschak** [comment]
Also, it appears that the documentation for `lapack64.Geev` does not state the order of Eigen values.

**Comment by vladimir-ch** [comment]
For `EigenSym` this has been done but for `Eigen`/`Dgeev` there is no defined order. I think this can be closed.
