### ISSUE TITLE
graph/encoding: [proposal] port support in the dot decoder

### ISSUE THREAD

**Issue by 32bitkid** [gonum/gonum#462]
While the dot ast correctly handles/parses dot ports _and_ there is the `Porter` interface for _encoding_ ports to a dot graph, there is no interface/hooks to decode that data from `Unmarshal()`

This is a proposal to add a `PortSetter` interface to expose callbacks for setting the parsed `port:compass` information:

```go
type PortSetter interface {
	SetFromPort(port, compass string)
	SetToPort(port, compass string)
}
```

If an `graph.Edge` implements this interface, it will be invoked during decode after the edge has been added to the graph, similar to how the `DOTIDSetter` interface is handled. If the edge has no ports, then the callbacks will not be called.

---

There is [a proposed branch](https://github.com/gonum/gonum/compare/master...32bitkid:decode-edge-ports?expand=1) with these changes ready for further review and PR, if advisable. 

Other potentially controversial changes in that branch include altering the default `CompassPoint` in `ast/ast.go` to be the token `CompassPointNone`, rather than `CompassPointDefault`. This allows for cleaner replication of when the default port is used explicitly, _i.e_ `foo:p:_ -> bar` can be detected distinctly from `foo:p -> bar` and cleans up some other tests that would strip the default `_` direction off. This would be done in a real-world graph to clear a top-level `edge` declaration.

**Comment by kortschak** [comment]
SGTM
