### ISSUE TITLE
mathext: GammaInc is really GammaIncReg?

### ISSUE THREAD

**Issue by btracey** [gonum/gonum#470]
Based on the documentation, I'm pretty sure what mathext calls the incomplete Gamma integral is really the regularized gamma integral. This should be fixed.

**Comment by dezmondgoff** [comment]
Can't the function simply be renamed and the standard function be added? Other than the Gamma distribution CDF, would any other functions have to be changed?

**Comment by btracey** [comment]
Yes, it should be an easy change, just didn't have time when I opened the issue.
