### ISSUE TITLE
Releases?

### ISSUE THREAD

**Issue by NDari** [gonum/gonum#48]
Hello all.

Are there any plans for explicit versioned releases of Gonum? We are planning to use a package manager (looks like `dep` currently, which will lock us to the master branch right now. We would love to be able to be a bit more explicit about the release tags we are using.

Thank you guys for all your great work!

**Comment by btracey** [comment]
There are plans, but no explicit time horizon. We hope to be able to provide version 1 compatibility for `matrix`, `blas` and `lapack` sub packages soon (though note this will happen after breaking changes to all of these packages which we are in the middle of right now). The timeline for the rest of the packages is unclear.

**Comment by NDari** [comment]
Ok. We will rely on a fork then! I am looking forward to all of the awesome work you guys are doing. Thanks for the prompt response @btracey
