### ISSUE TITLE
optimize: Brent (and some issues)

### ISSUE THREAD

**Issue by chewxy** [gonum/gonum#480]
### What are you trying to do?

Trying to add a [`Brent` optimization method](https://en.wikipedia.org/wiki/Brent%27s_method) to Gonum.

### What did you do?

Attempted to write the implementation. Ran into some issues. Specifically, the Brent optimization function requires access to the evaluation function in order to build its brackets in the initialization stage.  

However, the code as I understand it, does not expose `Problem.Func` anywhere.  And there are no clever workarounds to do so. 

The only other solution would be to pass in the function into the Brent struct. Which would lead to frankly quite a terrible API:

```
fn := func(x []float64) float64 { ... } 
problem := optimize.Problem {Func: fn} // <---- this
method := &optimize.Brent {
    Func: fn, // <----- this needs to be the exact same function as the above. this is terrible API-wise
}

optimize.Local(problem, []float64{...}, nil, method)
````

This solution is terrible because when initializing the `Brent` struct, you'd have to pass in the function for the `Init` method to calculate the correct brackets. Failing to pass in the same exact function as the problem would lead to weird results. 

Ideally, when the `Brent` struct is initialized, it will be given the `Problem.Func` from `minimize`.

This however, requires modifying `minimize` to check for the `Method` type. That's not very nice. 

### Proposal ###

A new interface should be created and checked in minimize. I propose something like this:

```
type RequiresFn interface {
    InitWithFn(fn func ([]float64)float64)
}
```

Thoughts welcome

**Comment by chewxy** [comment]
@btracey solved the issue offline. Thanks. Sketching out solution now

**Comment by btracey** [comment]
To expand upon this a bit, the implementation of `NelderMead` is a good example of how to use the Location struct to make several evaluations before "starting" the optimization.

**Comment by jaybatra26** [comment]
@chewxy . I am trying to implement Brent optimization method. Since this issue was not possible. Can you explain me the workaround for this. I am trying to use it to imitate this https://github.com/cranmer/fast-asimov-utils/blob/master/fasimov/__init__.py#L163 in golang.

Thanks in advance.

**Comment by chewxy** [comment]
@jaybatra26 here's my unmerged working. I don't recall how @btracey and I solved this offline, but I recall forgetting to do merge, or was asked to hold off because of new APIs... either way, long time ago. The kernels can still be used, so feel free to crib as much as you want.

https://github.com/chewxy/gonum/blob/cb9987b6d9c0f4762b9269fcd25ca00c4abd3dd5/optimize/brent.go

Diff: 
https://github.com/gonum/gonum/compare/master...chewxy:brent
