### ISSUE TITLE
internal/asm: Unrecognized instruction "MOVDDUP"

### ISSUE THREAD

**Issue by mackenziedg** [gonum/gonum#505]
I tried to go get gonum using the provided syntax from the README, but installation fails with 

```
# gonum.org/v1/gonum/internal/asm/f32
../../../gonum.org/v1/gonum/internal/asm/f32/ge_amd64.s:384: unrecognized instruction "MOVDDUP"
../../../gonum.org/v1/gonum/internal/asm/f32/ge_amd64.s:447: unrecognized instruction "MOVDDUP"
asm: assembly of ../../../gonum.org/v1/gonum/internal/asm/f32/ge_amd64.s failed
# gonum.org/v1/gonum/internal/asm/f64
../../../gonum.org/v1/gonum/internal/asm/f64/ger_amd64.s:255: unrecognized instruction "MOVDDUP"
../../../gonum.org/v1/gonum/internal/asm/f64/ger_amd64.s:286: unrecognized instruction "MOVDDUP"
../../../gonum.org/v1/gonum/internal/asm/f64/ger_amd64.s:304: unrecognized instruction "MOVDDUP"
../../../gonum.org/v1/gonum/internal/asm/f64/ger_amd64.s:341: unrecognized instruction "MOVDDUP"
../../../gonum.org/v1/gonum/internal/asm/f64/ger_amd64.s:390: unrecognized instruction "MOVDDUP"
../../../gonum.org/v1/gonum/internal/asm/f64/ger_amd64.s:451: unrecognized instruction "MOVDDUP"
../../../gonum.org/v1/gonum/internal/asm/f64/ger_amd64.s:468: unrecognized instruction "MOVDDUP"
../../../gonum.org/v1/gonum/internal/asm/f64/ger_amd64.s:505: unrecognized instruction "MOVDDUP"
../../../gonum.org/v1/gonum/internal/asm/f64/ger_amd64.s:553: unrecognized instruction "MOVDDUP"
asm: assembly of ../../../gonum.org/v1/gonum/internal/asm/f64/ger_amd64.s failed
```

`go version` gives `go1.7.4 linux/amd64`. I have not installed gonum previously, and pulling from the current master gives this error. I searched but was not able to find any references to this particular error online.

**Comment by sbinet** [comment]
hi,

it's perhaps not very clear but this error comes from a too old Go installation.
Gonum tries to stick quite closely to the Go releases and supports the last 3 versions of Go.

Go-1.10 was released in February 2018, so Gonum now explicitly supports `1.8.x`, `1.9.x` and `1.10.x`.

we test this explicitly in the `.travis.yml` file:

```yaml
language: go

# Versions of go that are explicitly supported by gonum plus go tip.
go:
 - 1.8.x
 - 1.9.x
 - 1.10.x
 - master
```

would it be possible for you to migrate at least to `1.8.x` ?
(but I'd recommend to migrate to `1.10.x`...)

**Comment by kortschak** [comment]
Gonum on ly supports the current and two previous Go releases which at the monent is 1.8, 1.9 and 1.10. The code in asm makes use of improvements in the Go assembler instruction set complement that were added in Go 1.8, so gonum packages that depend on asm will not compile before 1.8 (this includes gonum/blas/gonom and (depending on build options) mat and others that depend on that.

I would suggest you upgrade your Go installation.
