### ISSUE TITLE
README: add blurb explaining supported Go versions

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#506]
We should have a sentence explaining the Go version support policy for Gonum and a link to the relevant [lines of .travis.yml](https://github.com/gonum/gonum/blob/master/.travis.yml#L5-L10).

**Comment by sbinet** [comment]
also perhaps add a comment in `.travis.yml` to keep `README.md` in sync whenever we modify the list of supported Go versions.

**Comment by kortschak** [comment]
A comment in the travis file to not move the lives should be enough. I wasn't panning to explicitly state the versions, just something along the lines of "Gonum supports and tests on the [most recent trhee major of Go](https://github.com/gonum/gonum/blob/master/.travis.yml#L5-L10)."

**Comment by kortschak** [comment]
Yes. That;s what the comment would be for.
