### ISSUE TITLE
[Proposal] Want to collaborate with ODE integrator

### ISSUE THREAD

**Issue by Daniel-M** [gonum/gonum#532]
### What are you trying to do?
Hey, I did a go package for ODE integration with some basic methods. I came aware today of this project and I'd like to propose or adapt this to gonum package
My package is at  [https://github.com/Daniel-M/odeint](https://github.com/Daniel-M/odeint) it started as an excercise but I figure it could grow as something useful.

**Comment by Daniel-M** [comment]
@vladimir-ch thanks for the comments and the reading recommendation, I'm grateful for that.

* Though `complex128` or `complex64` aren't really popular numerical types to problem solving, I feel that an integrator without complex numbers integrators would be incomplete.

* I think that implementing float64 and complex128 methods would be enough to provide standard ODE integrators.

* I'm aware that the package might lack a proper coding style. It started as an excercise to learn more about Go, and I figured it could be useful someday. I lack the proper technical formation in Go (and general programming) to better implement the numerical methods in a resource efficient fashion and I really would like to collaborate in adding ODE integrators support to gonum, if you could provide guidance of some sort, I'd be glad to give it a try.

**Comment by vladimir-ch** [comment]
Not updated in a long time, there is now a new initiative in https://github.com/gonum/exp/pull/54, closing.
