### ISSUE TITLE
travis: add check for presence of copyright header

### ISSUE THREAD

**Issue by vladimir-ch** [gonum/gonum#537]

**Comment by kortschak** [comment]
There are a number of files in the repo that will not have a copyright notice and cannot - these are testdata files and documentation. Should we limit the check to Go files?

**Comment by vladimir-ch** [comment]
What is the current status here, @kortschak ? I think we do the check now, don't we?

**Comment by kortschak** [comment]
We do: https://github.com/gonum/gonum/blob/master/.travis/check-copyright.sh
