### ISSUE TITLE
graph/formats/dot: Does not handle `[dir=both]` edges for pathfinding

### ISSUE THREAD

**Issue by wesalvaro** [gonum/gonum#544]
`[dir=both]` edges are not treated as two-way for pathfinding.

### What are you trying to do?

I would like to use pathfinding for a graph that has `[dir=both]` edges defined.

### What did you do?

```dot
A -> B [dir=both]
A -> C
```
When pathfinding, there is no edge `B -> A`.

### What did you expect to happen?

Pathfinding should be able to traverse `[dir=both]` edges in either direction.

### What actually happened?

No path was found.

### What version of Go and Gonum are you using?

go version go1.10.3 darwin/amd64
ff99a9821f0fc7e0d40749b5148e54a57ea97d6e

### Does this issue reproduce with the current master?

Yes.

**Comment by kortschak** [comment]
The edge's will retain their attributes if the edge is an `encoding.AttributeSetter`. Any other approach would break roundtripping; we cannot interpret `dir=both` as a directed to write two edges into the graph and then `A -> B [dir=both]` would be the same as `A -> B; B -> A` which it's not. The `dir=both` is a rendering directive, not a graph topology statement.

If you *do* want to make the graph topology reflect the `dir` attribute, then you can either write in the attribute to the edge by making edges in the graph satisfy `encoding.AttributeSetter` and then after unmarshaling perform a pass over the graph's edges and set edges in reverse for those that have been marked `dir=both`, or you can make the edges aware of their containing graph and then have them set the reverse edge themselves when `Attribute(encoding.Attribute{"dir", "both"})` is called.

**Comment by wesalvaro** [comment]
Thanks so much for your ideas on how to address this!
I just can't add the edges to the actual graph file, so this helps a lot.
