### ISSUE TITLE
mat: Vectors magnitude

### ISSUE THREAD

**Issue by gmiejski** [gonum/gonum#574]
I would like to add Magnitude() to mat.Vector

```
type Vector interface {
    ...
    Magnitude() float64
}
```

Would you be interested in such change?

**Comment by sbinet** [comment]
I suppose computing the magnitude of a vector is indeed something valuable.
but I don't think we'd add that at the `Vector` interface level.

it would probably make more sense to:
- directly define that method on `*VecDense`
- optionally define an additional `Magnituder interface { Magnitude() float64 }`.

**Comment by kortschak** [comment]
How is magnitude defined? There are many definitions of magnitude for vectors.

We have `mat.Dot(v, v)` or `mat.Norm(v, 2)` and others can be defined by users for their particular use cases.

It should not go in an interface, or on `*VecDense`.
