### ISSUE TITLE
graph/encoding/dot: harmonise encoding/decoding API

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#61]
See comment at #58.

/cc @mewmew

**Comment by mewmew** [comment]
Good.

Do you wish to propose how we may change the API, to get a starting point for discussion?

**Comment by kortschak** [comment]
There are two ways to go. Either towards the `UnmarshalX`/`MarshalX` approach that you have, or to the `X() X`/`SetX(X)` that I have. I don't know which is better at this stage. get/set is easier to deal with, but is less flexible.

**Comment by kortschak** [comment]
Having spent some more time on this (while writing some teaching code that depends on encoding/dot), I think the `X() X`/`SetX(X)` approach is going to be better from an API usability perspective. The main issue is that attributes are a list of arbitrary key/value pairs, so it is not possible for the marshaler to call a `n.MarshalAttr(key)` method without knowing the value of `key` ahead of time - by which time, it may as well have just got a `[]dot.Attribute`.

**Comment by mewmew** [comment]
> Having spent some more time on this (while writing some teaching code that depends on encoding/dot),

If you feel like sharing, I'd be curious to take a look at the code used for teaching. It would be a great basis for discussion, if we could have that code implemented using both the current (marshal/unmarshal) API and the proposed (get/set) API, so we may use it for comparison on readability, extensibility and other aspects of the API.

**Comment by kortschak** [comment]
https://github.com/kortschak/graphprac

**Comment by mewmew** [comment]
> https://github.com/kortschak/graphprac

Thanks for providing a use case that we can use for comparison.

How would the code of `graphprac` differ, if `encoding/dot` used the X/SetX approach instead?

With this diff, we could discuss the benefits and drawbacks for a real use case, and could also see if there are specific limitations to either one of the approaches.

I've always been taught that you should not define an API without a clear use case in mind, so lets use this for discussion.

**Comment by kortschak** [comment]
The model for the `{Unm,M}arshalAttr` methods is "encoding/xml"; there is no equivalent in "encoding/json". The basis for use of this approach in the xml package is that it is only able to unmarshal into `struct`, `[]T` or string types appropriately matched to the XML encoding. slice and string types are trivial, being either a direct assignment (to the string var) or an integer-indexed assignment into the slice. For the `struct` types there is a need to be able to know the attribute/element name association with the fields be marshaled or unmarshaled. The xml package uses reflection to get this information (or via the xml encoding interfaces, though 'MarshalXMLAttr is used only for struct fields with the "attr" option in the field tag.'). So we can see that the single biggest issue here is that while it is trivial to unmarshal into a value from a set of statements or other attributes in a src stream, it is not possible to do the converse unless there is an available index of keys to marshal and unmarshal.

So to implement the MarshalAttr cognate for the dot package we would need to either require that nodes and edges be `struct`s (this is not currently a requirement, a map is the minimum for an edge and an integer type is the minimum for a node), or we require that marshalable types have an attribute list-returning method, thus needing three methods for round tripping. The equivalent for the alternative approach is two, a `SetAttribute(Attribute) error` and an `Attributes() []Attribute` method.

On this basis, I think we should go with the set/get approach rather than the approach used in xml. There is an additional allocation cost because of the use of slices, but graph/... is already reasonably allocation heavy (by necessity), so I don't think this adds too much additional burden relatively.

**Comment by mewmew** [comment]
Just got back from travels, I'll ponder on this during the days to come and get back to you. On a first glance, what you propose seems reasonable.

**Comment by kortschak** [comment]
Another aspect of this, is that I think it makes sense to move the `dot.Attribute` type into the graph package, and most of the set/get API interfaces into the encoding package (I'm writing a graphql JSON codec package that will make use of the same methods).
