### ISSUE TITLE
graph/encoding/dot: reconsider strict parameter on Marshal

### ISSUE THREAD

**Issue by 32bitkid** [gonum/gonum#625]
### Background

The `Marshal()` function takes a final boolean parameter that will prefix the emitted DOT encoded graph with the `strict` keyword. This, according to the DOT documentation:

> ...forbids the creation of multi-edges, i.e., there can be at most one edge with a given tail node and head node in the directed case. For undirected graphs, there can be at most one edge connected to the same two nodes. Subsequent edge statements using the same two nodes will identify the edge with the previously defined one and apply any attributes given in the edge statement.

Given that a `graph.Graph` is the interface for a _simple_ graph, it is not really _possible_ to construct a _non_-strict DOT graph in this form. A `graph.Multigraph` may, or _may not_, be a strict graph, it depends on the topology of the graph.

### Proposal

- Remove the `strict` parameter from `Marshal()`, and make `Marshal(graph.Graph)` _always_ serialize a `strict` dot graph.
- Remove the `strict` parameter from `MarshalMulti()` and make `MarshalMulti(graph.Multigraph)` _always_ serialize a non-strict graph

This would simplify the arguments for both functions, and reduce the likelihood of serializing an invalid DOT graph.

- Introduce a new pair of helper functions to convert a `graph.Graph` to a `graph.Multigraph` and _vice-versa_. This has an advantage over doing `strict` checking during serialization, as it is an explicit action to perform/verify the conversion, and errors can be handled explicitly, _e.g._ loading a multigraph and altering it in a way that should result in a simple graph, then outputting it is a `strict` DOT graph. 

### Potential implementation challenges

I'm not quite sure how to transfer custom DOT serialization properties through the conversion process.

### Potential impact of proposal

The signature of `Marshal()` will change and be incompatible with previous versions.

**Comment by kortschak** [comment]
I think the loss of control over the strict keyword is reasonable - the user can always `TrimPrefix` or prepend as needed.

I don't think a helper function set is needed though. The best way of handling these kinds of conversions is via an embedding type and these are best written by the user as they know what things are important in their use case.
