### ISSUE TITLE
stat/distuv/Laplace Fit panics when weights is nil

### ISSUE THREAD

**Issue by mestorlx** [gonum/gonum#638]
### What are you trying to do?
According to the documentation 
```golang
// If weights is nil, then all the weights are 1.
func (l *Laplace) Fit(samples, weights []float64) 
```

### What did you do?

However the following code panics
```golang
package main

import (
		"gonum.org/v1/gonum/stat/distuv"

)

func main() {
	var d distuv.Laplace
	d.Fit([]float64{1}, nil)
}
```

### What did you expect to happen?

Nothing
### What actually happened?
`panic: distuv: slice length mismatch`

### What version of Go and Gonum are you using?
go version go1.11.1 darwin/amd64
513db5a0a3aa4236f0ace2604a014c157876c32e

### Does this issue reproduce with the current master?

Yes

What is the intended behavior nil should or should not be accepted. I can submit a patch if required.

**Comment by kortschak** [comment]
Yes, that's definitely an omission. Please feel free to send a PR (stat/stat.go has a variety of approaches depending on what work needs to be done, so choose an appropriate approach or make one up). Please also add a test.
