### ISSUE TITLE
stat/distuv/Laplace Fit not properly estimating scaling factor

### ISSUE THREAD

**Issue by mestorlx** [gonum/gonum#639]
### What are you trying to do?
Want to fit a Laplace distribution to a set of sample data
According to the documentation 
```golang
// Fit sets the parameters of the probability distribution from the
// data samples x with relative weights w.
func (l *Laplace) Fit(samples, weights []float64) {
```

### What did you do?

```golang
package main

import (
	"gonum.org/v1/gonum/stat/distuv"
)

func main() {
	d.Fit(data, weights)
}
```

### What did you expect to happen?
According to the [wiki](https://en.wikipedia.org/wiki/Laplace_distribution) the scaling factor should be 
b=(1/n)sum|xi-m| 
### What actually happened?
the method is implemented with 
```golang 
// The scale parameter is the average absolute distance
// between the sample and the mean
absError := stat.MomentAbout(1, samples, l.Mu, weights)
```
However the moment is computed with
```golang
m += weights[i] * math.Pow(v-mean, moment)
```
Because we are at moment 1 so `Pow` is just `v-mean` hence m converge to zero. 

### What version of Go and Gonum are you using?
go version go1.11.1 darwin/amd64
513db5a0a3aa4236f0ace2604a014c157876c32e

### Does this issue reproduce with the current master?

Yes

I understand that the moment is correctly computed. The Fit function should be updated. If its of interest I can submit a patch.

**Comment by kortschak** [comment]
Yes, that's definitely an omission. If you want to send a PR, there are a variety of different approaches to handling the absence of `weights` depending on what needs to be done, the stat/stat.go is a pretty good gallery. Please add a test as well.

**Comment by kortschak** [comment]
Can you please post a complete reproducer?

**Comment by mestorlx** [comment]
### Sample
```golang
package main

import (
	"bufio"
	"fmt"
	"gonum.org/v1/gonum/stat/distuv"
	"io"
	"strconv"
)

func main() {

	s := []float64{251, 178, 342, 252, 253, 213, 335, 273, 250, 325, 253, 252, 254, 252, 240, 248,
		253, 250, 250, 247, 257, 259, 250, 254, 251, 250, 251, 254, 248, 265, 239, 260,
		253, 311, 252, 311, 250, 249, 251, 212, 289, 243, 253, 252, 254, 249, 250,
		259, 268, 346, 312, 263, 287, 281, 334, 239, 218, 280, 5, 255, 251, 255,
		266, 325, 248, 249, 250, 251, 171, 326, 195, 198, 281, 271, 265, 267, 250, 251,
		278, 264, 252, 265, 250, 243, 267, 250, 252, 253, 244, 252, 259, 132, 275, 182,
		336, 250, 251, 253, 358, 252, 276, 281, 255, 252, 191, 277, 283, 193, 213,
		268, 277, 250, 236, 241, 296, 242, 249, 251, 250, 262, 250, 219, 263, 267, 245,
		254, 251, 251, 234, 259, 264, 261, 246, 254, 264, 276, 236, 245, 253, 222, 240,
		250, 250, 252, 239, 254, 250, 263, 267, 251, 255, 256, 252, 243, 257,
		251, 252, 252, 242, 229, 250, 265, 252, 237, 270, 212, 268, 290, 256, 239, 239,
		263, 251, 248, 252, 249, 241, 268, 261, 254, 256, 258, 250, 251, 250, 259, 257, 197,
		282, 461, 257, 250, 250, 250, 251, 253, 253, 251, 250, 263, 247, 254,
		251, 256, 250, 250, 177, 305, 275, 203, 260, 250, 251, 252, 239, 274, 167, 262,
		251, 272, 251, 264, 250, 256, 226, 257, 270, 240, 239, 255}
	fmt.Println(len(s))
	w := make([]float64, len(s))
	for i := 0; i < len(w); i++ {
		w[i] = 1
	}
	var d distuv.Laplace
	d.Fit(s, w)
	fmt.Println("Function estimates:", d)
}
```
### Expected output
`Function estimates: {252 17.795652173913044 <nil>}`
### Current output
`Function estimates: {252 0.009319470699432892 <nil>}`

**Comment by akahard2dj** [comment]
Hi all gonum users,

First of all, I am new user of gonum.

In my option, this problem is caused by misleading a result.
Current output shows a result for fitting a density function. 

Expected output is result for curve to x versus y data(eg. histogram.).
The estimation is depicted in stackexchage.
https://stats.stackexchange.com/questions/281682/how-to-fit-a-data-against-a-laplace-double-exponential-distribution-and-check

**Comment by btracey** [comment]
My thought process back then was probably that the first moment is the average deviation, but that's clearly false. This is definitely a bug.
