### ISSUE TITLE
Greatest Common Denominator for integers

### ISSUE THREAD

**Issue by benfdking** [gonum/gonum#646]
### What are you trying to do?

Trying to solve a simple problem of highest common divisor in a set of integers

### What did you try?

Something like:
```go
x := []int{15,25,30}
gcd := GCD(x)
```

where gcd is 5

### How does Gonum not allow you to achieve your goal?

No function found that fulfils this.

### What version of Go and Gonum are you using?

n/a

### Is this feature absent from the current master?

yes

### Are you able to help contribute the feature?

Yes, would need some guidance on where to place it but currently the best algorithm seems to be the Euclidean wrapped as follows.

https://stackoverflow.com/questions/1231733/euclidean-greatest-common-divisor-for-more-than-two-numbers

**Comment by sbinet** [comment]
it would seem `math/big` has already that kind of feature:
- https://godoc.org/math/big#Int.GCD

wouldn't that fulfill your use case?

**Comment by kortschak** [comment]
ISTM that given that GCD(a, b, c) = GCD(a, GCD(b, c)), and that this is generalisable to longer lists of numbers, this is not really needed. There is a GCD for big ints in math/big, and @cznic has GCD for a variety of machine sized integers [here](https://godoc.org/github.com/cznic/mathutil#GCDByte) and below that..

For some implementation of GCD(a, b T),
```
func GCDMany(car byte, cdr ...byte) byte {
	if len(cdr) == 0 {
		return car
	}
	gcd := car
	for _, v := range cdr {
		gcd = mathutil.GCDByte(gcd, v)
	}
	return gcd
}
```
(The math/big.Int-based implementation is left as an exercise for the reader.)

**Comment by cznic** [comment]
On Tue, Nov 13, 2018 at 12:52 PM Dan Kortschak <notifications@github.com>
wrote:

> There is a GCD for big ints in math/big, and @cznic
<https://github.com/cznic> has GCD for a variety of machine sized integers
here <https://godoc.org/github.com/cznic/mathutil#GCDByte> and below that..

The link above points to https://godoc.org/github.com/cznic/mathutil#GCDByte,
I'd like to suggest that users of github.com/cznic/* switch to import paths
modernc.org/* instead. The link
https://godoc.org/modernc.org/mathutil#GCDByte works as expected. For
example, please replace


        import "github.com/cznic/mathutil"

by

        import "modernc.org/mathutil"

in your code.

FTR, the current hosting modernc.org redirects to is
https://gitlab.com/cznic. Please report any issues there, thank you.

-- 

-j

**Comment by ksbeking** [comment]
Is there a particular reason why we would not put basic math functions in the gonum package. I personally was under the impression that gonum is aiming to become the go to numerical package for golang similar to numpy. Would it be worth adding basic functionality such as that found in https://github.com/bxcodec/saint? Or does gonum very much aim to stick with float64 vectors and matrices?

**Comment by kortschak** [comment]
We don't have a goal to be the single repository of all numerical packages for Go. There are already good implementations for the function that you want and the code that takes that to be almost exactly what you asked for (and actually what you want) is posted above and is only 9 lines of code.

We have limited resources and have to spend them judiciously.

**Comment by btracey** [comment]
I agree with @kortschak . In addition, while we do not exclusively deal with matrices and vectors (as can clearly be seen by our packages), we are primarily motivated by statistical and numerical use cases. GCD feels like it belongs in a package about number theory or other relations among integers.
