### ISSUE TITLE
optimize: Consider adding Method.Supports(Function) (bool, error)

### ISSUE THREAD

**Issue by vladimir-ch** [gonum/gonum#665]
@btracey 's comment from #45 : Given we do use some magic, I can see the need for support. It seems like the better case is for the optimizer to have a Support function that either returns a boolean (if it supports), or an error which is nil if it supports, and provides a detailed explanation if it isn't, i.e. "Bfgs requires the Function to have a Gradient. Function does not implement either Gradient or FunctionGradient."

**Comment by vladimir-ch** [comment]
We have added `Method.Needs` since this issue was created. I've transferred it here because it contains some ideas about `Method.Supports` that could come in handy when we get to constrained optimization.

**Comment by btracey** [comment]
This was (hopefully) fixed with #779
