### ISSUE TITLE
lapack/testlapack: rationalise helpers

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#678]
There are a variety of helpers in testlapack that can be used but are not (for example `isOrthonormal`). I have contributed to this, but it should probably be cleaned up/factored out.

In the case of `isOrthonormal` the in-line implementations, e.g. in `dgelq2.go`, do more and have difference tolerances to `isOrthonormal`, These parameterisations might want to be incorporated into the `general.go` helper.

**Comment by vladimir-ch** [comment]
`isOrthonormal` has been done but is there anything else that you'd like to include here? The contents of `general.go` and `matgen.go` could be improved but again, where to stop and where is best to invest time?

**Comment by kortschak** [comment]
I'm pretty happy with how things are now. The test code is vastly more readable (thank you) and what remains can be done as it's noticed/cared about.

**Comment by vladimir-ch** [comment]
Does it mean we can close this?
