### ISSUE TITLE
lapack/gonum: improve information for parameter check panics

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#683]
For example, the `checkMatrix` signature could be extended to `checkMatrix(m, n int, a []float64, lda int, name string)` and have `": " + name` appended to the panic string.

**Comment by vladimir-ch** [comment]
I've become a fan of not using the `checkMatrix` function at all and doing all the checks explicitly in each Lapack function.

**Comment by kortschak** [comment]
Yes, this can be closed. I'm happy with the approach you've been using.
