### ISSUE TITLE
stat/distmv: Add Nu() method to MV Student's T

### ISSUE THREAD

**Issue by btracey** [gonum/gonum#702]
It cannot be extracted at present, but it can get created unobserved with Conditional

**Comment by LogaNick** [comment]
@btracey can this be closed? I see a Nu() function [here](https://github.com/gonum/gonum/blob/84c458a64e38cd00673c4d76b83066cc95eb6808/stat/distmv/studentst.go#L315) -- unless I'm misunderstanding? (I'm looking for a good first issue.)

**Comment by sbinet** [comment]
yes, it seems this was fixed w/ https://github.com/gonum/gonum/pull/356

**Comment by sbinet** [comment]
(but the correct bug labeling was lost when transitioning from the multi gonum repo to the single mono-repo structure).

nice catch.
