### ISSUE TITLE
stat: Fix distmv to allow zero-matrices

### ISSUE THREAD

**Issue by btracey** [gonum/gonum#705]
For example in Normal.CovarianceMatrix

**Comment by btracey** [comment]
I'm repurposing this issue, because I think this is what I meant at that point and then forgot.

For `[]float64` methods, we typically have the receiver as the first argument, allow it to be nil, and allocate and return otherwise. 

In the suite, in some places we do the same for matrix receivers, `stat.CovarianceMatrix` being another example. There is no need to do this. The convention is that zero-sized matrices get automatically adjusted in size to the right thing. Instead, the user should just allocate a zero-value and use it

```
var cov mat.SymDense
stat.CoviarianceMatrix(&cov, data, weights)
```
This is roughly as easy as the current `cov := stat.CovarianceMatrix(nil, data, weights)`, but has a simpler signature.

**Comment by kortschak** [comment]
SGTM
