### ISSUE TITLE
stat: ROC signature

### ISSUE THREAD

**Issue by Armadilloa16** [gonum/gonum#708]
I came up with what I think is an improvement to the ROC function, 
in which the cutoffs are defined explicitly instead of the number of cutoffs n.
This allows for unequally-spaced cutoffs, allows for all cutoffs to be used
more naturally, and simplifies the code itself.

Is this a good idea -- should I put a PR in for it, @sbinet @kortschak ?

Also, I was thinking maybe ROC should output an error as well, instead of all
the panic statements? Or is it appropriate that it panic?

What I did is here, in case you wanted to look at the specifics of what I am 
suggesting:
https://github.com/Armadilloa16/stat/tree/roc

**Comment by kortschak** [comment]
@Armadilloa16 I have salvaged the branch you had at your fork of stat and cleaned it up and rebased it onto master. I've also (I think correctly - though not convinced) altered the tests so that they pass.

Are you happy to have that sent as a PR and would you have a quick look over the changes to the test expectation that I've made to see if you agree with them.

The branch is [here](https://github.com/gonum/gonum/tree/stat/roc).

**Comment by Armadilloa16** [comment]
Hey @kortschak sorry for the sluggish responses...

Yes I'm happy for you to send this as a PR, however I took a quick look at the tests: these are all cases in which the issue is the FPR when there are no true negatives, and the TPR when there are no true positives. Returning 0 in these cases doesn't necessarily make sense, although returning 1 might not either... I feel like deciding what to return in these cases should probably be a deliberate decision, maybe returning nil or NA or something like that would be more appropriate in these cases. I.e. maybe there should be a check for these cases. This could be done pretty easily at lines 103 and 106 of roc.go, the condition we are checking for is the else clause: nNeg == 0 or nPos == 0.

**Comment by Armadilloa16** [comment]
Nice example of good testing bringing up special cases worth addressing. :)

**Comment by kortschak** [comment]
OK. So previously it was that the final element was 1. I'm reluctant to add a NaN and we don't have an NA, so I'll revert the test and change the behaviour to match.

**Comment by Armadilloa16** [comment]
Yeah I dunno NaN might be appropriate, you're essentially dividing by zero in that case. Or couldn't you just return an empty vector or something? It makes sense to not calculate FPR when there are no true negatives and not calculate TPR when there are no true positives.

**Comment by kortschak** [comment]
OK, I'll place a NaN. A float division by zero gives Inf BTW.

**Comment by Armadilloa16** [comment]
That makes sense, the documentation should probably also be updated to reflect this functionality.

**Comment by kortschak** [comment]
It looks like it's expected behaviour. From sklearn:
```
>>> from sklearn import metrics
>>> y = [1, 2]
>>> c = [1, 1]
>>> metrics.roc_curve(y_score=y, y_true=c)
/usr/lib/python2.7/dist-packages/sklearn/metrics/ranking.py:526: UndefinedMetricWarning: No negative samples in y_true, false positive value should be meaningless
  UndefinedMetricWarning)
(array([nan, nan]), array([0.5, 1. ]), array([2, 1]))
```

**Comment by Armadilloa16** [comment]
Yeah cool that makes sense, good to be inline with what other people are doing as well I suppose.

**Comment by kortschak** [comment]
Funny thing happened on the way to the shop. I found that the behaviour here was because I incorrectly fixed a test discordance; the test cases [0, 0, 0 ..., 1] were wrong and I added the condition the match them.

**Comment by Armadilloa16** [comment]
Hahaha nice one! Although I think saying they where "wrong" might be a bit strong, I think it is an edge case in which it's not entirely obvious what "correct" behaviour ought to be.

**Comment by Armadilloa16** [comment]
Sorry about this by the way... I had forgotten these Issues were still open when I deleted my fork of gonum/stat, I had thought since i hadn't done anything on it in so long it must have all been resolved haha... lesson learnt. That said, this has also reminded me about how I enjoy contributing to such things... maybe I should try to budget time for this kind of development more.

**Comment by kortschak** [comment]
I have it still. I'm finding this more complicated than I had expected though.
