### ISSUE TITLE
graph: consider SetEdge() returning an error

### ISSUE THREAD

**Issue by vladimir-ch** [gonum/gonum#717]
The motivation is that for some graphs (e.g., planar) not every edge is legal and checking if setting an edge is possible can be the same amount of work as setting it and seeing if it fails.

However, that would mean adding error checking and responding to errors from SetEdge() all over the place for a very minor application.

**Comment by vladimir-ch** [comment]
I would close this. My motivation for this were planar graphs but my understanding of the graph package and design in Go at that time was limited.

**Comment by kortschak** [comment]
Is there some prospect of the planar graph thing coming back? What API would you need to be able to do that?

**Comment by vladimir-ch** [comment]
I don't think so, at least not from me for the foreseeable future.

**Comment by kortschak** [comment]
I think that if a planar graph type were to be implemented we could have a `SetPlanarEdge(graph.Edge) error` and that would satisfy the cases needed. I have an interested in this that I also probably can't scratch for doing meshing and model manipulations.

I'll close this now.

**Comment by vladimir-ch** [comment]
> `SetPlanarEdge(graph.Edge) error`

That was my idea also.
