### ISSUE TITLE
No cross product?

### ISSUE THREAD

**Issue by macmason** [gonum/gonum#725]
vector: No cross product?

I can find `Dot` at `matrix.go:340` but no equivalent `Cross`. Have I just missed it?

**Comment by kortschak** [comment]
This is really a question.

```
var m mat.Dense
m.Mul(v1, v2.T())
```

**Comment by btracey** [comment]
While there are extensions, the cross product is only really well defined for vectors of size 3. This is more appropriate for a type that is specifically that length.


Package vec3

func Dot(a, b [3]float64) float64 {
    return a[0]*b[0] + a[1]*b[1] + a[2]*b[2]
}

Func Cross(a, b [3]float64) [3]float64 {
    return [3]float64{a[1]*b[2] - a[2]*b[1], a[2]*b[0] - a[0]*b[2], a[0]*b[1] - a[1]*b[0]}
}


This will be faster and cannot panic.

**Comment by btracey** [comment]
Note that @kortschak 's answer gives you the Cartesian product, which you can also use
```
var m mat.Dense
m.Outer(1, v, v2)
```
