### ISSUE TITLE
unit: Intermittent test failure in TestFormat

### ISSUE THREAD

**Issue by jonlawlor** [gonum/gonum#729]
I seem to be getting an occasional test failure in TestFormat (and travis-ci does as well):

--- FAIL: TestFormat (0.00 seconds)
    unit_test.go:44: Format "%#v": got: "&unit.Unit{dimensions:unit.Dimensions{6:-1, 4:2}, formatted:\"\", value:6.62606957e-34}" expected: "&unit.Unit{dimensions:unit.Dimensions{4:2, 6:-1}, formatted:\"\", value:6.62606957e-34}"
FAIL

go test -race doesn't find anything wrong.

**Comment by vladimir-ch** [comment]
I think we could close this. It's been more than 4 years.

**Comment by kortschak** [comment]
Done
