### ISSUE TITLE
mat: Remove Transpose methods?

### ISSUE THREAD

**Issue by btracey** [gonum/gonum#735]
I was wondering if we really need the `T()` method on Matrix (and related types). The previous discussion is https://github.com/gonum/matrix/issues/123 . 

I know at one point I thought `T()` as a method was really important, but I don't really remember why. In light of actually using the methods, we still need to deal with `Untranspose`, still have a bunch of types, and we have a lot more methods, especially now that `Banded` is in. I wonder if it's better to just have functions as @kortschak originally proposed.

Essentially, the proposal is to delete the transpose methods from the types and interfaces. We would replace them with functions that are akin to 

```
func T(m Matrix) Matrix {
   if u, ok := m.(Untransposer); ok {
        return u.Untranspose()
   }
   return Transpose{m}
}
```

Using the `Untranspose` interfaces ensures that a "Russian doll" of transposes isn't created.

I don't think this changes any functionality, with the minor exception that now `SymDense` and friends would be wrapped by Transpose (though we could add that fast path if we wanted). We already have all of the `Transpose` types in the package, so that part is the same. The only difference is shifting `T`, `TBand`, `TTri`, etc. to package-level functions instead of methods. The upsides are making the package slightly simpler. There is now exactly one right way to do a transpose with the Matrix interface , rather than the behavior being implementation dependent. We gain greater simplicity in the interfaces (almost always a win), and make it slightly less cumbersome to implement the interfaces.

I think the loss is that the code looks slightly less pretty, i.e. `c.Mul(mat.T(a), b)` instead of `c.Mul(a.T(), b)`. It may be that the code improvement is worth the (moderate) extra complexity here.

I wanted to bring it up before we're locked in, now that we've seen what it looks like with the core set of types.

**Comment by kortschak** [comment]
I feel that the legibility from having a `.T()` rather than a `mat.T(...)` is worth the cost of having the methods.

**Comment by btracey** [comment]
Okay. Sounds reasonable.
