### ISSUE TITLE
blas/blas64: Vector doesn't contain length?

### ISSUE THREAD

**Issue by btracey** [gonum/gonum#736]
Is there a good reason `blas64.Vector` doesn't contain information about it's length? This seems inconsistent with the rest of the types, and I don't see any discussion on the matter.

**Comment by vladimir-ch** [comment]
I remember asking this but cannot find it now.

I agree that it is inconsistent with the other types and I would add it to `blas64.Vector`. I think we should then add checks to `blas64`.

**Comment by btracey** [comment]
This is true in `gonum/lapack/gonum`, which calls the blas function directly (not through blas64). As far as I know everything that uses `blas64` specifies a size, and making that change passes all of the tests.
