### ISSUE TITLE
go get -u -v gonum.org/v1/gonum/...

### ISSUE THREAD

**Issue by jedi108** [gonum/gonum#784]
go get -u -v gonum.org/v1/gonum/...
```
Fetching https://gonum.org/v1/gonum?go-get=1
https fetch failed: Get https://gonum.org/v1/gonum?go-get=1: net/http: TLS handshake timeout
package gonum.org/v1/gonum/...: unrecognized import path "gonum.org/v1/gonum/..." (https fetch: Get https://gonum.org/v1/gonum?go-get=1: net/http: TLS handshake timeout)
```

**Comment by btracey** [comment]
If you know how to fix the problem without manually adding pages for every
subdirectory we will happily fix. AFAIK we're doing it like the Go team
does and we encounter these issues getting the /x repos. I don't know what
to do about it.

**Comment by sbinet** [comment]
I don't know if it's "the" way to address this but inserting a thin Go server fit the bill for the 'go-hep.org/x/...' vanity imports.

See github.com/go-hep/go-hep.org

**Comment by jefersonprediza** [comment]
Are you change the server? The error is the file or directory not found. Check the web server configurations (redirects, alias, document root, etc).

If the directory and files exists, then check your go-repo. A reference In https://golang.org/cmd/go/#hdr-Remote_import_paths and you can check with https://github.com/cskr/gorepos

**Comment by cedric-cordenier** [comment]
Hi there :)

Has this issue been resolved? Some of our builds broke today because of the following:

go get -u gonum.org/v1/gonum/...

go get gonum.org/v1/gonum/...: unrecognized import path "gonum.org/v1/gonum" (https fetch:
 Get https://gonum.org/v1/gonum?go-get=1: dial tcp 104.248.63.231:443: i/o timeout)

**Comment by MikeSchlosser16** [comment]
Same for me, builds are failing due to the same issue today

**Comment by kortschak** [comment]
This is really not something that we can fix. Can I suggest that if it continues to be a significant problem, file an issue against the go tool.

**Comment by mottyc** [comment]
Workaround:

I had the same issue, the workaround is simply to move the entire gonum.org folder to a "vendor" folder under your project root - this way go shall look for the gonum dependencies in the vendor folder first and will not try to get it from https://gonum.org/v1/gonum?go-get=1

**Comment by sbinet** [comment]
in a Go-module setup, another workaround might be to put this `replace` directive in your `go.mod` file:

```
replace gonum.org/v1/gonum => github.com/gonum/gonum v0.6.2
```

_ie:_
https://play.golang.org/p/IolH7f-b0kK

**Comment by vladimir-ch** [comment]
Not something that we can fix and not updated in a long time, closing.
