### ISSUE TITLE
mat: Add Zero() function

### ISSUE THREAD

**Issue by btracey** [gonum/gonum#817]
Right now we have `Reset` which resets the matrix to zero-sized to be used for operations. Perhaps we should also have `Zero` which sets the data to zero (which is like `Reset`, but preserves the size information)

**Comment by kortschak** [comment]
A possibility (for consideration only) is to provide a `Zero(r, c int) Matrix` function that returns an unexported type `zero struct { r, c int }` that only returns zero elements. The could be copied onto matrices to zero them, possibly with an optimisation in `Copy` and other operations.
