### ISSUE TITLE
stat,all: Create Bounds package and type

### ISSUE THREAD

**Issue by btracey** [gonum/gonum#833]
Right now we have a `Bound` type in `stat/distmv`, but really this is a more general concept than distmv. In particular, an equivalent type is needed in `optimize` (for bounded optimization problems), and I could see a type easily being useful in a future `root` package. I think we should have a `gonum.org/v1/gonum/bound` package that contains that type. The signature for `distmv.NewUniform` would then be `func NewUniform(bnds bound.Bound, src rand.Source)`. This allows the same data structure to be used across packages.

**Comment by sbinet** [comment]
SGTM

**Comment by btracey** [comment]
There are more routines to add, see https://github.com/gonum/gonum/pull/845#discussion_r255359176

**Comment by btracey** [comment]
Removing the stability tag because the API changes from this issue are done.

**Comment by btracey** [comment]
Created #939 because it's really a separate issue from this one which is now done.
