### ISSUE TITLE
mat: hogsvd inefficiencies (possible incorrectness)

### ISSUE THREAD

**Issue by btracey** [gonum/gonum#848]
HOGSVD is at least inefficient, but it seems incorrect. Right now there is this segment:
```
var cv VecDense
for j := 0; j < c; j++ {
	cv.ColViewOf(v, j)
	cv.ScaleVec(1/blas64.Nrm2(cv.mat), &cv)
}
```
which is not used anywhere, so at least should be deleted, but I suspect it was supposed to be used for something. The output of `VTo` just copies the output from Eigen. The current eigen form is the weird transformed form which may have complex eigenvalues, and this is not at all handled in the implementation. Do we know that S is positive definite?

**Comment by kortschak** [comment]
That block is not a no-op. `cv` aliases `v`'s columns and so the loop scales the columns by their Frobenius norm. This is reflected in v after the completion of the loop.

I can add a comment that work done on `cv` is reflected in `v`.

The mathematical properties of the system are described in the [paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0028072). The paper claims "S is nondefective ... and its eigensystem is real".

**Comment by btracey** [comment]
Ahh, sorry. I'll add the comment, I have a PR almost ready updating Eigen

**Comment by kortschak** [comment]
Suggested text:
```diff
  v := eig.Vectors()
+ // Rescale the columns of v by their Frobenius norms.
+ // Work done in cv is reflected in v.
  var cv VecDense
```
