### ISSUE TITLE
Versions of go supported

### ISSUE THREAD

**Issue by bvwells** [gonum/gonum#852]
The readme for this repo states:

'Gonum supports and tests on the three most recent major versions of Go on Linux and Windows.'

This should state that the three most recent minor versions of go are supported.

**Comment by kortschak** [comment]
No, I don't think so. The three most recent minor versions would be go1.11.5, go1.11.4 and go1.11.3. We support go1.11.x, go1.10.x and go1.9.x until go1.12 comes out.

**Comment by kortschak** [comment]
Ah, I see what you mean. You are using the formal semver definition of major and minor. Yes. you are correct. I will fix that. Thanks.

**Comment by bvwells** [comment]
Thanks @kortschak!
