### ISSUE TITLE
unit: add type for torque

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#915]
We should probably add a unit for torque.

However, I don't see a nice way to do this. In order to prevent the length dim in Nm from interacting with `LengthDim` we would need to make a new length dimension (`OrthoLengthDim`). This would have the same symbol (probably — or maybe something else, "₥"?) which would make things impossible.

Thoughts?

/cc @btracey

**Comment by btracey** [comment]
We want it to interact with the length dimension. The units are N-m, and the meaning of "meter" is the same in both cases. The unit as a whole is conceptually distinct from the N-m in energy, but that's a limitation of the units system. There are a lot of conceptual orthogonalities when it comes to units, and we can barely fix any of them, let alone all of them.

**Comment by kortschak** [comment]
The situation is soluble, but not with the system we have. We would need to have vectors associated with each of the dimensions. The relevant orthogonality that differentiates Nm (T) from Nm (E) is that the vectors on N and m in the E case are parallel, while they are orthogonal in the T case. The OrthoLengthDim above doesn't work for fixing this.

**Comment by btracey** [comment]
It's a really tough problem to solve in the general case. If you want to go the vector route, you really need a tensor for the higher dimensions. It needs to be dynamically sizeable, because there are possibly many ways for items to be conceptually, if not literally, orthogonal. The easiest thing to do is to keep the dimensions as they are, and rely on typing to make harder to make mistakes

**Comment by kortschak** [comment]
Agreed. This means we don't add this and let users do it if they need.

**Comment by btracey** [comment]
Great. Agreed. I think we can still add a Torque type though.

**Comment by kortschak** [comment]
I feel uncomfortable about it, but this is the stanza for the generator:
```
	{
		Name:        "Torque",
		Receiver:    "t",
		PrintString: "N m",
		Suffix:      "newtonmeter",
		Singular:    "Newtonmeter",
		TypeComment: "Torque represents a torque in Newton meters. Care should be used when calculating with this type",
		Dimensions: []Dimension{
			{Name: LengthName, Power: 2},
			{Name: MassName, Power: 1},
			{Name: TimeName, Power: -2},
		},
	},
```

**Comment by btracey** [comment]
Does it really need that extra warning? I agree that it's easy to make mistakes, but it's not that different from other unit errors.  For instance multiplying (0.012 kg / mol * 5mol = 60kg) when the first is mass/mol of Carbon but I actually measured mol-Hydrogen. Or measuring the rate-of-change in a viscosity and accidentally adding it to a pressure value. There's lots of dragons in relying on units alone.

**Comment by kortschak** [comment]
The difference is the in Nm one of the m is perpendicular to the other. That is not what is going on in the apples versus oranges case above.
