### ISSUE TITLE
Gonum.org is blocked in Russia

### ISSUE THREAD

**Issue by vitalyisaev2** [gonum/gonum#944]
This is actually not a bug, but it brings significant obstacles for russian `gonum` users. Unfortunately, it's not possible to `go get` the library:

```
go get -u -v github.com/gonum/gonum/...
Fetching https://gonum.org/v1/gonum?go-get=1
https fetch failed: Get https://gonum.org/v1/gonum?go-get=1: dial tcp 167.99.129.42:443: connect: connection refused
go: gonum.org/v1/gonum@v0.0.0-20190325211145-e42c1265cdd5: unrecognized import path "gonum.org/v1/gonum" (https fetch: Get https://gonum.org/v1/gonum?go-get=1: dial tcp 167.99.129.42:443: connect: connection refused)
go: error loading module requirements
```

This happens due to these reasons:
1. There is a redirect from `github.com/gonum/gonum` to `gonum.org/v1/gonum`;
2. `gonum.org` (167.99.129.42) was blocked in 2018 because of Telegram ban (you may visit https://blocklist.rkn.gov.ru/ to check IP status). Perhaps this IP was previously used for Telegram infrastructure or proxy server hosting, but now it's yours, and the ban is still ongoing.

Surely it's not your fault, but I will very appreciate it if you could fix this problem on your side: either avoid redirect, or change the external IP of `gonum.org` to another one that is not banned in Russia.

Sincerely,
Vitaly

**Comment by sbinet** [comment]
@btracey being the current owner of `gonum.org` (IIRC) will probably need to do something (I think.)

in the meantime, you can do:
```
$> cd $GOPATH/src
$> git clone https://github.com/gonum/gonum gonum.org/v1/gonum
$> git clone https://github.com/gonum/plot gonum.org/v1/plot
```

hth

**Comment by btracey** [comment]
Thanks for the report. I’m not really sure what to do about this. We are hosted at Netlify, I found this thread which seems to confirm we aren’t the only ones

https://www.reddit.com/r/Netlify/comments/9lvdvg/netlify_is_partly_blocked_by_censorship_in_russia/ <https://www.reddit.com/r/Netlify/comments/9lvdvg/netlify_is_partly_blocked_by_censorship_in_russia/>

**Comment by vitalyisaev2** [comment]
@sbinet @btracey thanks for the prompt response. Yes, there are several possible workarounds, but none of them can fix `go module` issues. For example, if my project depends on `gonum.org/v1/gonum`, I can't track dependency changes:

```
go get changes       
go: gonum.org/v1/gonum@v0.0.0-20190325211145-e42c1265cdd5: unrecognized import path "gonum.org/v1/gonum" (https fetch: Get https://gonum.org/v1/gonum?go-get=1: dial tcp 167.99.129.42:443: connect: connection refused)
go: error loading module requirements
```

**Comment by vitalyisaev2** [comment]
My colleagues helped me to recognize that `gonum.org` is actually resolves in several IP addresses, some of them are not blocked. Putting this line in `/etc/hosts` should help:

```
142.93.108.123 gonum.org www.gonum.org
```

**Comment by kortschak** [comment]
Hosting via NumFOCUS might help here.

**Comment by btracey** [comment]
Yes. I realize I've dropped the ball, I'll move it up my list.

**Comment by kortschak** [comment]
Sorry, that wasn't meant to be pointed.

**Comment by btracey** [comment]
Don't worry, it wasn't taken that way

**Comment by dewey** [comment]
Same issue but not from Russia. This is from Germany.

```
go get: upgrading gonum.org/v1/gonum@v0.0.0-20181121035319-3f7ecaa7e8ca: unrecognized import path "gonum.org/v1/gonum" (https fetch: Get https://www.gonum.org/v1/gonum?go-get=1: dial tcp 104.248.78.23:443: i/o timeout)
```

**Comment by Mart-Bogdan** [comment]
@vitalyisaev2, You should write a letter to RKN prompting them to remove IP from the blacklist, as it's another service.

The most correct solution, instead of changing hosting for maintainers.

**Comment by savalin** [comment]
I solved this by putting replace in go.mod:
`gonum.org/v1/gonum => github.com/gonum/gonum v0.6.0`

**Comment by awsl-dbq** [comment]
you may need goproxy 
try `GOPROXY=https://goproxy.cn go get  `
or `GOPROXY=https://goproxy.baidu.com/      go get`
This two proxy site hosted in china ...
hope they are fast and not blocked.
