### ISSUE TITLE
bound: consider renaming Bound to Interval

### ISSUE THREAD

**Issue by kortschak** [gonum/gonum#956]
Merely to reduce stutter.

**Comment by vladimir-ch** [comment]
Or rename it to `r1` and move to `spatial`.

**Comment by kortschak** [comment]
SGTM

**Comment by btracey** [comment]
I guess I don't like `r1`, but r2 and r3 are there, as is https://godoc.org/github.com/golang/geo/r1  , so I'm probably wrong (i.e. I'm not going to veto it). It's not clear that `r1.Bound` makes sense though. `r1.Interval` seems to be better, but it's a lot of characters. Maybe `r1.Range`?

**Comment by kortschak** [comment]
`Range` has more semantic content than `Interval`. Considering https://github.com/gonum/gonum/pull/982#issuecomment-491822888, I'd push for `Interval`.
