### ISSUE TITLE
mat: Helper routine(s) for resizing zero matrices

### ISSUE THREAD

**Issue by btracey** [gonum/gonum#963]
We have a pattern that Zero matrices can be resized. This is both receivers of methods, but also as inputs to functions, for example in `stat` and `optimize`. It would be nice to implement methods necessary to make this pattern easy to implement. This would encourage outside packages to follow the same pattern.

**Comment by kortschak** [comment]
1. What is the proposed behaviour when `!m.IsZero()`?
2. What is the behaviour of e.g. `m.ReuseAs(0, 0)`? (presumable `panic(ErrZeroLength)`, but this may ask why have `Reset` which could be expressed that way)

**Comment by btracey** [comment]
1. I think it would panic. I think the goal is to be explicit about the behavior (we also have `Slice` and `Grow` for other purposes)
2. I agree with your proposed behavior. I think "why Reset" is because using zero-sized values in mathematical operations is not allowed in Gonum (except as overwriteable). `Reset` says "make this value blank again" while `ReuseAs` says "give me a usable value of a certain size"

**Comment by kortschak** [comment]
SGTM
