### ISSUE TITLE
mat: Add Freivalds() function

### ISSUE THREAD

**Issue by corona10** [gonum/gonum#967]
I'd like to propose a probability algorithm `func Freivalds(a, b, c Matrix, count int) bool` for `mat` package.
It would be useful for users who want to know a X b == c.

**Comment by kortschak** [comment]
Can you please provide more details for this? For a proposal/feature request, there is a template to follow that helps provide the answers to questions that we are likely to need. Would you revise the proposal to follow that please.

**Comment by corona10** [comment]
@kortschak Okay I will rewrite the proposal after I get more familiar with the codebase
